name: covid19_abm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - expat=2.2.9
  - fontconfig=2.13.0
  - freetype=2.10.2
  - glib=2.65.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - joblib=0.16.0
  - jpeg=9b
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.1
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - prompt-toolkit=3.0.7
  - ptyprocess=0.6.0
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.2
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=5.0.4
  - wcwidth=0.2.5
  - wheel=0.35.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - arrow==0.16.0
    - attrs==20.2.0
    - binaryornot==0.4.4
    - chardet==3.0.4
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.5.0
    - cookiecutter==1.7.2
    - fiona==1.8.17
    - geopandas==0.8.1
    - idna==2.10
    - ipython-autotime==0.1
    - jinja2==2.11.2
    - jinja2-time==0.2.0
    - markupsafe==1.1.1
    - mesa==0.8.7
    - munch==2.5.0
    - networkx==2.5
    - poyo==0.5.0
    - pyproj==2.6.1.post1
    - python-slugify==4.0.1
    - requests==2.24.0
    - shapely==1.7.1
    - text-unidecode==1.3
    - tqdm==4.50.0
    - urllib3==1.25.10
    - xlrd==1.2.0
