infix using "C:\COUNTRIES\ZW52\ZWPR52FL.dct"

label variable hhid     "Case Identification"
label variable hvidx    "Line number"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "Field editor"
label variable hv032    "Office editor"
label variable hv033    "Ultimate area selection pro-NA"
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "Cluster altitude in meters"
label variable hv041    "Total adults measured"
label variable hv042    "Selection for hemoglobin"
label variable hv043    "Selection for women's statu-NA"
label variable hv044    "Selection for domestic violence module"
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Rooms used for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Have bednet for sleeping"
label variable hv228    "Children under 5 slept under bednet last night"
label variable hv234    "Test salt for Iodine       -NA"
label variable hv235    "Location of source for water"
label variable hv236    "Person fetching water"
label variable hv237    "Anything done to water to make safe to drink"
label variable hv237a   "Water usually treated by: boil"
label variable hv237b   "Water usually treated by: add bleach/chlorine"
label variable hv237c   "Water usually treated by: strain through a cloth"
label variable hv237d   "Water usually treated by: use water filter"
label variable hv237e   "Water usually treated by: solar disinfection"
label variable hv237f   "Water usually treated by: let it stand and settle"
label variable hv237g   "Water usually treated by: C-NA"
label variable hv237h   "Water usually treated by: C-NA"
label variable hv237i   "Water usually treated by: C-NA"
label variable hv237j   "Water usually treated by: C-NA"
label variable hv237k   "Water usually treated by: C-NA"
label variable hv237x   "Water usually treated by: other"
label variable hv237z   "Water usually treated by: don't know"
label variable hv238    "Number of households sharing toilet"
label variable hv239    "Food cooked on stove or ope-NA"
label variable hv240    "Household has a chimney, ho-NA"
label variable hv241    "Food cooked in the house / in separate building / outdoors"
label variable hv242    "Household has separate room used as kitchen"
label variable hv243a   "Has a mobile telephone"
label variable hv243b   "Has a watch"
label variable hv243c   "Has an animal-drawn cart"
label variable hv243d   "Has a boat with a motor"
label variable hv244    "Own land usable for agriculture"
label variable hv245    "Hectares for agricultural land"
label variable hv246    "Livestock, herds or farm animals"
label variable hv246a   "Cattle own"
label variable hv246b   "Cows, bulls own            -NA"
label variable hv246c   "Horses, donkeys, mules own"
label variable hv246d   "Goats own"
label variable hv246e   "Sheep own"
label variable hv246f   "Chickens own"
label variable hv246g   "Pigs own (CS)"
label variable hv246h   "CS own                     -NA"
label variable hv246i   "CS own                     -NA"
label variable hv246j   "CS own                     -NA"
label variable hv246k   "CS own                     -NA"
label variable hv247    "Owns a bank account"
label variable hv248    "Number of sick people 18-59"
label variable hv249    "Member of the HH died last 12 months"
label variable hv250    "Number of members who died last 12 months"
label variable hv251    "Number of orphans and vulnerable children"
label variable hv270    "Wealth index"
label variable hv271    "Wealth index factor score (5 decimals)"
label variable hml1     "Number of mosquito nets"
label variable hml1a    "Number of mosquito nets with specific information"
label variable hml2     "Number of children under bednet previous night"
label variable shdist   "District"
label variable sheacode "Cluster number             -NA"
label variable shlangq  "Language of questionnaire"
label variable shlangin "Language of interview"
label variable shinterp "Translator used            -NA"
label variable sh113    "Food cooked on stove or open fire"
label variable sh116    "Type of dwelling unit"
label variable sh120a   "Any windows"
label variable sh120b   "Windows with glass"
label variable sh120c   "Windows with screens"
label variable sh120d   "Windows with curtains/shutters"
label variable sh122g   "Wheelbarrow"
label variable sh128    "Sprayed interior walls against mosquitos"
label variable sh129    "House sprayed by"
label variable hv101    "Relationship to head"
label variable hv102    "Usual resident"
label variable hv103    "Slept last night"
label variable hv104    "Sex of household member"
label variable hv105    "Age of household members"
label variable hv106    "Highest educational level"
label variable hv107    "Highest year of education"
label variable hv108    "Education in single years"
label variable hv109    "Educational attainment"
label variable hv110    "Member still in school     -NA"
label variable hv111    "Mother alive"
label variable hv112    "Mother's line number"
label variable hv113    "Father alive"
label variable hv114    "Father's line number"
label variable hv115    "Current marital status"
label variable hv116    "Currently, formerly, never m."
label variable hv117    "Eligibility for female interview"
label variable hv118    "Eligibility for male interview"
label variable hv120    "Children eligibility for height/weight and hemoglobin"
label variable hv121    "Member attended school during current school year"
label variable hv122    "Educational level during current school year"
label variable hv123    "Grade of education during current school year"
label variable hv124    "Education in single years - current school year"
label variable hv125    "Member attended school during previous school year"
label variable hv126    "Educational level during previous school year"
label variable hv127    "Grade of education during previous school year"
label variable hv128    "Education in single years - previous school year"
label variable hv129    "School attendance status"
label variable hv130    "Member has been very sick for 3+ months last year"
label variable hv131    "Mother has been very sick for 3+ months last year"
label variable hv132    "Father has been very sick for 3+ months last year"
label variable hv133    "Mother/father dead or been very sick for 3+ months"
label variable hv134    "Both parents alive"
label variable hv135    "Has brothers/sisters under 18 of the same father and mother"
label variable hv136    "Brothers/sisters under 18 that don't live in household"
label variable hv137    "Member has a blanket"
label variable hv138    "Member has a pair of shoes"
label variable hv139    "Member has 2+ sets of clothes"
label variable hv140    "Member has a birth certificate"
label variable idxh4    "Index to household schedule"
label variable sh1309   "Blood storage consent statement parent/responsible adult"
label variable sh1312   "Anemia consent statement respondent"
label variable sh1315   "HIV consent statement respondent"
label variable sh1316   "Blood storage consent statement respondent"
label variable sh1317   "Provide informational brochure about VCT"
label variable sh1318   "Recheck for consent"
label variable sh1323   "Respondent pregnant"
label variable sh1325   "Agrees to referral"
label variable sh1006   "Blood storage consent statement parent/responsible adult"
label variable sh1013   "Blood storage consent statement respondent"
label variable sh1014   "Number of HIV vouchers provided for test at nearest facility"
label variable sh1015   "Recheck for consent"
label variable sh1021   "Agrees to referral"
label variable ha0      "Index to household schedule"
label variable ha1      "Women's age in years"
label variable ha2      "Respondent's weight (kilos-1d)"
label variable ha3      "Respondent's height (cms-1d)"
label variable ha4      "Ht/A Percentile (resp.)"
label variable ha5      "Ht/A Standard deviations (resp"
label variable ha6      "Ht/A Percent ref. median (resp"
label variable ha11     "Wt/Ht Std deviations(resp) DHS"
label variable ha12     "Wt/Ht Percent ref. median (DHS"
label variable ha12a    "Wt/Ht Percent ref. median (Fog"
label variable ha12b    "Wt/Ht Percent ref. median (WHO"
label variable ha13     "Result of measurement of resp."
label variable ha32     "Date of birth (cmc)"
label variable ha33     "Completeness of information"
label variable ha35     "Smoking"
label variable ha40     "Body mass index for respondent"
label variable ha41     "Rohrer's index for respondent"
label variable ha50     "Under age 18"
label variable ha51     "Line no. of parent/caretaker"
label variable ha52     "Read consent statement"
label variable ha53     "Hemoglobin level (g/dl - 1 decimal)"
label variable ha54     "Currently pregnant"
label variable ha55     "Result of measuring (Hemoglobin)"
label variable ha56     "Hemoglobin level adjusted by altitude(g/dl - 1 decimal)"
label variable ha57     "Anemia level"
label variable ha58     "Agrees to referral         -NA"
label variable ha60     "Marital status"
label variable ha61     "Read consent statement (HIV)"
label variable ha62     "Blood sample ID number"
label variable ha63     "Result of measuring (HIV)"
label variable ha64     "Consent for additional test-NA"
label variable ha65     "Result of woman individual interview"
label variable ha66     "Woman's highest educational level"
label variable ha67     "Woman's highest year of education"
label variable ha68     "Highest educational level (CS for prelimnary & final report)"
label variable ha69     "HIV weight (6 decimals)"
label variable hc0      "Index to household schedule"
label variable hc1      "Age in months"
label variable hc2      "Weight in kilograms (1 dec.)"
label variable hc3      "Height in centimeters (1 dec.)"
label variable hc4      "Ht/A Percentile"
label variable hc5      "Ht/A Standard deviations"
label variable hc6      "Ht/A Percent of ref. median"
label variable hc7      "Wt/A Percentile"
label variable hc8      "Wt/A Standard deviations"
label variable hc9      "Wt/A Percent of ref. median"
label variable hc10     "Wt/Ht Percentile"
label variable hc11     "Wt/Ht Standard deviations"
label variable hc12     "Wt/Ht Percent of ref. median"
label variable hc13     "Reason not measured"
label variable hc15     "Height: lying or standing"
label variable hc16     "Day of birth of child"
label variable hc17     "Date measured (day)"
label variable hc18     "Date measured (month)"
label variable hc19     "Date measured (year)"
label variable hc27     "Sex"
label variable hc30     "Month of birth of child"
label variable hc31     "Year of birth of child"
label variable hc32     "Date of birth (cmc)"
label variable hc33     "Completeness of information"
label variable hc51     "Line no. of parent/caretaker"
label variable hc52     "Read consent statement"
label variable hc53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hc55     "Result of measuring (Hemoglobin)"
label variable hc56     "Hemoglobin level adjusted by altitude(g/dl - 1 decimal)"
label variable hc57     "Anemia level"
label variable hc58     "Agrees to referral         -NA"
label variable hc60     "Mother's line number from woman's questionnaire"
label variable hc61     "Mother's highest educational level"
label variable hc62     "Mother's highest year of education"
label variable hc63     "Preceding birth interval"
label variable hc64     "Birth order number"
label variable hc68     "Highest educational level (CS for prelimnary & final report)"
label variable hc70     "Ht/A Standard deviations (according to WHO)"
label variable hc71     "Wt/A Standard deviations (according to WHO)"
label variable hc72     "Wt/Ht Standard deviations (according to WHO)"
label variable hc73     "BMI Standard deviations (according to WHO)"
label variable hb0      "Index to household schedule"
label variable hb1      "Men's age in years"
label variable hb2      "Respondent's weight (kilos--NA"
label variable hb3      "Respondent's height (cms-1d-NA"
label variable hb4      "Ht/A Percentile (resp.)   -NA"
label variable hb5      "Ht/A Standard deviations (r-NA"
label variable hb6      "Ht/A Percent ref. median (r-NA"
label variable hb11     "Wt/Ht Std deviations(resp) -NA"
label variable hb12     "Wt/Ht Percent ref. median (-NA"
label variable hb12a    "Wt/Ht Percent ref. median (-NA"
label variable hb12b    "Wt/Ht Percent ref. median (-NA"
label variable hb13     "Result of measurement of re-NA"
label variable hb32     "Date of birth (cmc)"
label variable hb33     "Completeness of information"
label variable hb35     "Smoking"
label variable hb40     "Body mass index for respondent"
label variable hb41     "Rohrer's index for respondent"
label variable hb50     "Under age 18"
label variable hb51     "Line no. of parent/caretaker"
label variable hb52     "Read consent statement"
label variable hb53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hb55     "Result of measuring (Hemoglobin)"
label variable hb56     "Hemoglobin level adjusted by altitude(g/dl - 1 decimal)"
label variable hb57     "Anemia level"
label variable hb58     "Agrees to referral         -NA"
label variable hb60     "Marital status             -NA"
label variable hb61     "Read consent statement (HIV)"
label variable hb62     "Blood sample ID number"
label variable hb63     "Result of measuring (HIV)"
label variable hb64     "Consent for additional test-NA"
label variable hb65     "Result of man individual interview"
label variable hb66     "Man's highest educational level"
label variable hb67     "Man's highest year of education"
label variable hb68     "Highest educational level (CS for prelimnary & final report)"
label variable hb69     "HIV weight (6 decimals)"
label variable hmlidx   "Net number"
label variable hml3     "Net observed"
label variable hml4     "Months ago obtained mosquito net"
label variable hml5     "Was net treated with insecticide when bought"
label variable hml6     "Mosquito net treated with insecticide"
label variable hml7     "Brand of bednet"
label variable hml8     "Bednet treated since receiving"
label variable hml9     "Months ago re-treated"
label variable hml10    "ITN net"
label variable hml11    "Number of persons who slept under this net"
label variable hml21    "Did someone sleep under bednet last night"
label variable hmla     "Person who slept in mosquito net"
label variable hmlb     "Person who slept in mosquito net"
label variable hmlc     "Person who slept in mosquito net"
label variable hmld     "Person who slept in mosquito net"
label variable hmle     "Person who slept in mosquito net"
label variable hmhidx   "Index to household schedule"
label variable hml12    "Type of bednet(s) person slept under last night"
label variable hml13    "1st net number for net person slept under last night"
label variable hml14    "2nd net number for net person slept under last night"
label variable hml15    "3rd net number for net pers-NA"
label variable hml16    "Corrected age from individual questionnaire"
label variable hml17    "Flag for AH07 age from individual file"
label variable hml18    "Pregnancy from individual questionnaire"
label variable hml19    "Person sleep under an ever treated bednet"
label variable hskidx   "Index to household schedule"
label variable hs100    "Free medical support last 12 months"
label variable hs101    "Medical support at least once a month"
label variable hs102    "Free emotinal support last 12 months"
label variable hs103    "Emotional support last 30 days"
label variable hs104    "Free material support last 12 months"
label variable hs105    "Material support last 30 days"
label variable hs106    "Free social support last 12 months"
label variable hs107    "Social support last 30 days"
label variable hs108    "Pain last 30 days"
label variable hs109    "Able to reduce the pain"
label variable hs110    "Nausea last 30 days"
label variable hs111    "Able to reduce the nausea"
label variable hovidx   "Index to household schedule"
label variable ho100    "Age of child"
label variable ho101    "Free medical support last 12 months"
label variable ho102    "Free emotional support last 12 months"
label variable ho103    "Emotional support last 3 months"
label variable ho104    "Free material support last 12 months"
label variable ho105    "Material support last 3 months"
label variable ho106    "Free social support last 12 months"
label variable ho107    "Social support last 3 months"
label variable ho108    "Free any support"
label variable sh415    "Free schooling support"

#delimit ;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define HV024   
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV042   
     0 "Not selected"
     1 "Selected"
;
label define HV044   
     0 "Household not selected"
     1 "Household selected"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into tap in yard/plot"
    13 "Public tap"
    20 "OPEN WELL WATER"
    21 "Tube well or borehole"
    30 "COVERED WELL/BOREHOLE"
    31 "Protected dug well"
    32 "Unprotected dug well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    51 "Rainwater"
    61 "Tanker truck"
    71 "Cart with small tank"
    81 "Surface water(river/dam/lake/pond/stream/canal/irrigation channel"
    91 "Bottled water"
    96 "Other"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into tap in yard/plot"
    13 "Public tap"
    20 "OPEN WELL WATER"
    21 "Tube well or borehole"
    30 "COVERED WELL/BOREHOLE"
    31 "Protected dug well"
    32 "Unprotected dug well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    51 "Rainwater"
    61 "Tanker truck"
    71 "Cart with small tank"
    81 "Surface water(river/dam/lake/pond/stream/canal/irrigation channel"
    91 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
   998 "Don't know"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flushed to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to latrine"
    14 "Flush other"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated improved pit/latrine (VIP Blair toilet)"
    22 "Non-VIP pit latrine with slab"
    23 "Non-VIP pit latrine without slab"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    90 "OTHER"
    91 "Composting toilet/Arbo loo"
    92 "Bucket toilet"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth, sand/dung"
    20 "RUDIMENTARY"
    21 "Rudimentary wood planks"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "OTHER"
;
label define HV214   
    10 "NATURAL"
    11 "Cane/trunks"
    12 "Mud"
    20 "RUDIMENTARY"
    22 "Stone with mud"
    23 "Plywood"
    24 "Carton"
    25 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Wood planks"
    96 "OTHER"
;
label define HV215   
    10 "NATURAL"
    11 "No roof"
    12 "Thatch"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    23 "Wood planks"
    30 "FINISHED"
    31 "Metal"
    32 "Wood"
    33 "Asbestos"
    34 "Tiles"
    35 "Cement"
    96 "OTHER"
;
label define HV216   
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "Liquid propane gas"
     3 "Natural gas"
     4 "Biogas"
     5 "Paraffin/Kerosine"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Maize or other crop waste"
    11 "Animal dung"
    95 "Do not cook"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV234   
   999 "Missing"
;
label define HV235   
     1 "In own dwelling"
     2 "In own yard/plot"
     3 "Elsewhere"
;
label define HV236   
     1 "Adult woman"
     2 "Adult man"
     3 "Female child under 15 years old"
     4 "Male child under 15 years old"
     6 "Other"
;
label define HV237   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define HV237A  
     0 "No"
     1 "Yes"
;
label define HV237B  
     0 "No"
     1 "Yes"
;
label define HV237C  
     0 "No"
     1 "Yes"
;
label define HV237D  
     0 "No"
     1 "Yes"
;
label define HV237E  
     0 "No"
     1 "Yes"
;
label define HV237F  
     0 "No"
     1 "Yes"
;
label define HV237G  
     9 "Missing"
;
label define HV237H  
     9 "Missing"
;
label define HV237I  
     9 "Missing"
;
label define HV237J  
     9 "Missing"
;
label define HV237K  
     9 "Missing"
;
label define HV237X  
     0 "No"
     1 "Yes"
;
label define HV237Z  
     0 "No"
     1 "Yes"
;
label define HV238   
    95 "10 or more households"
    98 "Don't know"
;
label define HV239   
     1 "Open fire"
     2 "Open stove"
     3 "Closed stove with chimney"
     6 "Other"
;
label define HV240   
     9 "Missing"
;
label define HV241   
     1 "In the house"
     2 "In a separate building"
     3 "Outdoors"
     6 "Other"
;
label define HV242   
     0 "No"
     1 "Yes"
;
label define HV243A  
     0 "No"
     1 "Yes"
;
label define HV243B  
     0 "No"
     1 "Yes"
;
label define HV243C  
     0 "No"
     1 "Yes"
;
label define HV243D  
     0 "No"
     1 "Yes"
;
label define HV244   
     0 "No"
     1 "Yes"
;
label define HV245   
    95 "More than 95"
    98 "Unknown"
;
label define HV246   
     0 "No"
     1 "Yes"
;
label define HV246A  
     0 "None"
    98 "Unknown"
;
label define HV246B  
    99 "Missing"
;
label define HV246C  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246D  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246E  
     0 "None"
    95 "More than 95"
    98 "Unknown"
;
label define HV246F  
     0 "None"
    98 "Unknown"
;
label define HV246G  
     0 "None"
    97 "More than 97 *"
    98 "Unknown"
;
label define HV246H  
    99 "Missing"
;
label define HV246I  
    99 "Missing"
;
label define HV246J  
    99 "Missing"
;
label define HV246K  
    99 "Missing"
;
label define HV247   
     0 "No"
     1 "Yes"
;
label define HV249   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV250   
     8 "DK"
;
label define HV270   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define HML1    
    98 "Don't know"
;
label define HML2    
    99 "Missing"
;
label define SHLANGQ 
     1 "Shona"
     2 "Ndebele"
     3 "English"
     4 "Other"
;
label define SHLANGIN
     1 "Shona"
     2 "Ndebele"
     3 "English"
     6 "Other"
;
label define SH113   
     1 "Open fire or stove without chimney/hood"
     2 "Open fire or stove with chimney/hood"
     3 "Closed stove with chimney"
     6 "Other"
;
label define SH116   
     1 "Traditional"
     2 "Mixed"
     3 "Detached"
     4 "Semi-detached"
     5 "Flat/townhome"
     6 "Shack"
    96 "Other"
;
label define SH120A  
     0 "No"
     1 "Yes"
;
label define SH120B  
     0 "No"
     1 "Yes"
;
label define SH120C  
     0 "No"
     1 "Yes"
;
label define SH120D  
     0 "No"
     1 "Yes"
;
label define SH122G  
     0 "No"
     1 "Yes"
;
label define SH128   
     0 "Less than one month"
    95 "Not sprayed"
;
label define SH129   
     1 "Government program"
     2 "Private company"
     3 "Household member"
     6 "Other"
     8 "Don't know"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nehew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    97 "97+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     9 "Missing"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV115   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define HV130   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV131   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV132   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV133   
     0 "No"
     1 "Yes"
;
label define HV134   
     0 "No"
     1 "Yes"
;
label define HV135   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV136   
     0 "No"
     1 "Yes"
;
label define HV137   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV138   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV139   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV140   
     0 "Neither certificate or registered"
     1 "Has certificate"
     2 "Registered"
     8 "DK"
;
label define SH1309  
     0 "Refused"
     1 "Consent signed"
     8 "No adult present"
;
label define SH1312  
     0 "Refused"
     1 "Consent signed"
;
label define SH1315  
     0 "Refused"
     1 "Consent signed"
;
label define SH1316  
     0 "Refused"
     1 "Consent signed"
;
label define SH1317  
     0 "Refused"
     1 "Accepted"
;
label define SH1318  
     1 "Consented to both"
     2 "Anemia test only"
     3 "HIV test only"
     4 "Both refused"
;
label define SH1323  
     1 "Woman pregnant"
     2 "Woman not pregnant/not sure"
;
label define SH1325  
     0 "No"
     1 "Yes"
;
label define SH1006  
     0 "Refused"
     1 "Consent signed"
     8 "No adult present"
;
label define SH1013  
     0 "Refused"
     1 "Consent signed"
;
label define SH1014  
     9 "Missing"
;
label define SH1015  
     1 "Consented to both"
     2 "Anemia test only"
     3 "HIV test only"
     4 "Both refused"
;
label define SH1021  
     0 "No"
     1 "Yes"
;
label define HA2     
  9999 "Missing"
;
label define HA3     
  9999 "Missing"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HA35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HA50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HA51    
     0 "Not in household"
;
label define HA52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "No adult present ***"
;
label define HA53    
   999 "Missing"
;
label define HA54    
     0 "No/don't know"
     1 "Yes"
;
label define HA55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "Technical problem **"
     6 "Other"
;
label define HA56    
   999 "Missing"
;
label define HA57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HA58    
     9 "Missing"
;
label define HA60    
     1 "Never in union"
     2 "Other"
;
label define HA61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "No adult present"
;
label define HA63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Technical problem ***"
     5 "Sample not found in the lab data ***"
     6 "Other"
     7 "Specimen collected but could not be tested ***"
;
label define HA64    
     9 "Missing"
;
label define HA65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HA66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HA67    
    99 "Missing"
;
label define HA68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC2     
  9999 "Missing"
;
label define HC3     
  9999 "Missing"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     1 "Lying"
     2 "Standing"
;
label define HC16    
    99 "Missing"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
;
label define HC33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HC51    
     0 "Not in household"
;
label define HC52    
     1 "Granted"
     2 "Refused"
;
label define HC53    
   999 "Missing"
;
label define HC55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC56    
   999 "Missing"
;
label define HC57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HC58    
     9 "Missing"
;
label define HC60    
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC62    
    99 "Missing"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HC70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HC73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HB2     
  9999 "Missing"
;
label define HB3     
  9999 "Missing"
;
label define HB4     
  9998 "Flagged cases"
;
label define HB5     
  9998 "Flagged cases"
;
label define HB6     
 99998 "Flagged cases"
;
label define HB11    
  9998 "Flagged cases"
;
label define HB12    
 99998 "Flagged cases"
;
label define HB12A   
 99998 "Flagged cases"
;
label define HB12B   
 99998 "Flagged cases"
;
label define HB13    
     9 "Missing"
;
label define HB33    
     1 "Month and year"
     2 "Month and age"
     3 "Year and age"
     4 "Year"
     6 "Age"
     7 "Month"
     8 "None"
;
label define HB35    
     0 "Doesn't smoke"
    80 "80+"
    94 "Smokes pipes, cigars, etc"
;
label define HB40    
  9998 "Flagged cases"
;
label define HB41    
  9998 "Flagged cases"
;
label define HB50    
     1 "Under age 18"
     2 "Age 18 or older"
;
label define HB51    
     0 "Not in household"
;
label define HB52    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "No adult present ***"
;
label define HB53    
   999 "Missing"
;
label define HB55    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "Technical problem **"
     6 "Other"
;
label define HB56    
   999 "Missing"
;
label define HB57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HB58    
     9 "Missing"
;
label define HB61    
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "No adult present ***"
;
label define HB63    
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Technical problem ***"
     5 "Sample not found in the lab data ***"
     6 "Other"
     7 "Specimen collected but could not be tested ***"
;
label define HB64    
     9 "Missing"
;
label define HB65    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define HB66    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HB67    
    99 "Missing"
;
label define HB68    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define HML3    
     0 "Not seen"
     1 "Yes, seen"
;
label define HML4    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML5    
     0 "No"
     1 "Yes"
     8 "Not sure ***"
;
label define HML6    
     0 "Not pretreated"
     1 "Pretreated, permanent tx"
     2 "Pretreated, requiring future tx"
     3 "Not pretreated, came with kit and treated at home"
     4 "Pretreated, treatment type not known"
     6 "Other"
     8 "Don't know"
;
label define HML7    
    11 "Permanent long lasting net"
    21 "Ordinary net"
    31 "Other"
    98 "Don't know"
;
label define HML8    
     0 "No"
     1 "Yes"
     2 "Permanent net"
     8 "Not sure"
;
label define HML9    
    96 "More than 3 years ago"
    98 "Don't know"
;
label define HML10   
     0 "No, don't know"
     1 "Yes"
;
label define HML11   
     5 "5+"
;
label define HML21   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HMLA    
     0 "No one"
;
label define HMLB    
    99 "Missing"
;
label define HMLC    
    99 "Missing"
;
label define HML12   
     0 "No bednet"
     1 "Only treated bednets"
     2 "Both treated and untreated bednets"
     3 "Only untreated bednets"
;
label define HML13   
     0 "Did not sleep under net"
;
label define HML16   
    97 "97+"
    98 "DK"
;
label define HML17   
     0 "No completed individual questionnaire"
     1 "Age same, sex same"
     2 "Age same, (BH) sex different"
     3 "Age < 5 years different, sex same"
     4 "Age < 5 years different, (BH) sex different"
     5 "Age 5+ years different, sex same"
     6 "Age 5+ years different, (BH) sex different"
;
label define HML18   
     0 "Not pregnant, don't know"
     1 "Pregnant"
;
label define HML19   
     0 "No"
     1 "Yes"
;
label define HS100   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS101   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS102   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS103   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS104   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS105   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS106   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS107   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HS108   
     0 "Not at all"
     1 "Severe"
     2 "Mild"
     8 "DK"
;
label define HS109   
     0 "Not at all"
     1 "Most of the time"
     2 "Some time"
;
label define HS110   
     0 "No"
     1 "Yes, severe"
     2 "Yes, never severe"
;
label define HS111   
     0 "Not at all"
     1 "Most of the time"
     2 "Some time"
;
label define HO100   
    99 "Missing"
;
label define HO101   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO102   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO103   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO104   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO105   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO106   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO107   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HO108   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SH415   
     0 "No"
     1 "Yes"
     8 "DK"
;

#delimit cr
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv042    HV042   
label values hv044    HV044   
label values hv201    HV201   
label values hv202    HV202   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv235    HV235   
label values hv236    HV236   
label values hv237    HV237   
label values hv237a   HV237A  
label values hv237b   HV237B  
label values hv237c   HV237C  
label values hv237d   HV237D  
label values hv237e   HV237E  
label values hv237f   HV237F  
label values hv237x   HV237X  
label values hv237z   HV237Z  
label values hv238    HV238   
label values hv239    HV239   
label values hv241    HV241   
label values hv242    HV242   
label values hv243a   HV243A  
label values hv243b   HV243B  
label values hv243c   HV243C  
label values hv243d   HV243D  
label values hv244    HV244   
label values hv245    HV245   
label values hv246    HV246   
label values hv246a   HV246A  
label values hv246c   HV246C  
label values hv246d   HV246D  
label values hv246e   HV246E  
label values hv246f   HV246F  
label values hv246g   HV246G  
label values hv247    HV247   
label values hv249    HV249   
label values hv250    HV250   
label values hv270    HV270   
label values hml1     HML1    
label values shlangq  SHLANGQ 
label values shlangin SHLANGIN
label values sh113    SH113   
label values sh116    SH116   
label values sh120a   SH120A  
label values sh120b   SH120B  
label values sh120c   SH120C  
label values sh120d   SH120D  
label values sh122g   SH122G  
label values sh128    SH128   
label values sh129    SH129   
label values hv101    HV101   
label values hv102    HV102   
label values hv103    HV103   
label values hv104    HV104   
label values hv105    HV105   
label values hv106    HV106   
label values hv107    HV107   
label values hv108    HV108   
label values hv109    HV109   
label values hv111    HV111   
label values hv112    HV112   
label values hv113    HV113   
label values hv114    HV114   
label values hv115    HV115   
label values hv116    HV116   
label values hv117    HV117   
label values hv118    HV118   
label values hv120    HV120   
label values hv121    HV121   
label values hv122    HV122   
label values hv123    HV123   
label values hv124    HV124   
label values hv125    HV125   
label values hv126    HV126   
label values hv127    HV127   
label values hv128    HV128   
label values hv129    HV129   
label values hv130    HV130   
label values hv131    HV131   
label values hv132    HV132   
label values hv133    HV133   
label values hv134    HV134   
label values hv135    HV135   
label values hv136    HV136   
label values hv137    HV137   
label values hv138    HV138   
label values hv139    HV139   
label values hv140    HV140   
label values sh1309   SH1309  
label values sh1312   SH1312  
label values sh1315   SH1315  
label values sh1316   SH1316  
label values sh1317   SH1317  
label values sh1318   SH1318  
label values sh1323   SH1323  
label values sh1325   SH1325  
label values sh1006   SH1006  
label values sh1013   SH1013  
label values sh1015   SH1015  
label values sh1021   SH1021  
label values ha4      HA4     
label values ha5      HA5     
label values ha6      HA6     
label values ha11     HA11    
label values ha12     HA12    
label values ha12a    HA12A   
label values ha12b    HA12B   
label values ha13     HA13    
label values ha33     HA33    
label values ha35     HA35    
label values ha40     HA40    
label values ha41     HA41    
label values ha50     HA50    
label values ha51     HA51    
label values ha52     HA52    
label values ha54     HA54    
label values ha55     HA55    
label values ha57     HA57    
label values ha60     HA60    
label values ha61     HA61    
label values ha63     HA63    
label values ha65     HA65    
label values ha66     HA66    
label values ha68     HA68    
label values hc4      HC4     
label values hc5      HC5     
label values hc6      HC6     
label values hc7      HC7     
label values hc8      HC8     
label values hc9      HC9     
label values hc10     HC10    
label values hc11     HC11    
label values hc12     HC12    
label values hc13     HC13    
label values hc15     HC15    
label values hc27     HC27    
label values hc30     HC30    
label values hc31     HC31    
label values hc33     HC33    
label values hc51     HC51    
label values hc52     HC52    
label values hc55     HC55    
label values hc57     HC57    
label values hc60     HC60    
label values hc61     HC61    
label values hc68     HC68    
label values hc70     HC70    
label values hc71     HC71    
label values hc72     HC72    
label values hc73     HC73    
label values hb4      HB4     
label values hb5      HB5     
label values hb6      HB6     
label values hb11     HB11    
label values hb12     HB12    
label values hb12a    HB12A   
label values hb12b    HB12B   
label values hb33     HB33    
label values hb35     HB35    
label values hb40     HB40    
label values hb41     HB41    
label values hb50     HB50    
label values hb51     HB51    
label values hb52     HB52    
label values hb55     HB55    
label values hb57     HB57    
label values hb61     HB61    
label values hb63     HB63    
label values hb65     HB65    
label values hb66     HB66    
label values hb68     HB68    
label values hml3     HML3    
label values hml4     HML4    
label values hml5     HML5    
label values hml6     HML6    
label values hml7     HML7    
label values hml8     HML8    
label values hml9     HML9    
label values hml10    HML10   
label values hml11    HML11   
label values hml21    HML21   
label values hmla     HMLA    
label values hml12    HML12   
label values hml13    HML13   
label values hml16    HML16   
label values hml17    HML17   
label values hml18    HML18   
label values hml19    HML19   
label values hs100    HS100   
label values hs101    HS101   
label values hs102    HS102   
label values hs103    HS103   
label values hs104    HS104   
label values hs105    HS105   
label values hs106    HS106   
label values hs107    HS107   
label values hs108    HS108   
label values hs109    HS109   
label values hs110    HS110   
label values hs111    HS111   
label values ho101    HO101   
label values ho102    HO102   
label values ho103    HO103   
label values ho104    HO104   
label values ho105    HO105   
label values ho106    HO106   
label values ho107    HO107   
label values ho108    HO108   
label values sh415    SH415   
