infix using "C:\COUNTRIES\ZW52\ZWMR52FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Sample weight"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Respondent's month of birth"
label variable mv010    "Respondent's year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age - respondent"
label variable mv013    "Age 5-year groups"
label variable mv014    "Completeness of information"
label variable mv015    "Result of individual interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv033    "Ultimate area selection pro-NA"
label variable mv034_1  "Line numbers of wives, partners"
label variable mv034_2  "Line numbers of wives, partners"
label variable mv034_3  "Line numbers of wives, partners"
label variable mv034_4  "Line numbers of wives, partners"
label variable mv034_5  "Line numbers of wives, partners"
label variable mv034_6  "Line numbers of wives, partners"
label variable mv034_7  "Line numbers of wives, partners"
label variable mv034_8  "Line numbers of wives, partners"
label variable mv034a_1 "Wife or partner            -NA"
label variable mv034a_2 "Wife or partner            -NA"
label variable mv034a_3 "Wife or partner            -NA"
label variable mv034a_4 "Wife or partner            -NA"
label variable mv034a_5 "Wife or partner            -NA"
label variable mv034a_6 "Wife or partner            -NA"
label variable mv034a_7 "Wife or partner            -NA"
label variable mv034a_8 "Wife or partner            -NA"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives, partners"
label variable mv801    "Time interview started"
label variable mv802    "Time interview ended"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "Childhood place of residenc-NA"
label variable mv104    "Years lived in place of res."
label variable mv105    "Type of place of previous res."
label variable mv106    "Highest educational level"
label variable mv107    "Highest year of education"
label variable mv130    "Religion"
label variable mv131    "Ethnicity                  -NA"
label variable mv133    "Education in single years"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members"
label variable mv138    "Number of eligible men in HH"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "Ever participated in a literacy program outside of primary"
label variable mv157    "Frequency of reading newpaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "Current pregnancy wanted   -NA"
label variable mv245    "Women fathered children with"
label variable mv246    "Married to mother when firs-NA"
label variable mv247    "Age of youngest child"
label variable mv248    "Antenatal check-ups for the-NA"
label variable mv249    "Respondent present during c-NA"
label variable mv250    "Place of birth of youngest -NA"
label variable mv251    "Reason for not delivering y-NA"
label variable mv252    "Drinking pattern when child-NA"
label variable mv301    "Knowledge of any method"
label variable mv302    "Ever use of any method"
label variable m304a_01 "Type of method"
label variable m304a_02 "Type of method"
label variable m304a_03 "Type of method"
label variable m304a_04 "Type of method"
label variable m304a_05 "Type of method"
label variable m304a_06 "Type of method"
label variable m304a_07 "Type of method"
label variable m304a_08 "Type of method"
label variable m304a_09 "Type of method"
label variable m304a_10 "Type of method"
label variable m304a_11 "Type of method"
label variable m304a_12 "Type of method"
label variable m304a_13 "Type of method"
label variable m304a_14 "Type of method"
label variable m304a_15 "Type of method"
label variable m304a_16 "Type of method"
label variable m304a_17 "Type of method"
label variable m304a_18 "Type of method"
label variable m304a_19 "Type of method"
label variable m304a_20 "Type of method"
label variable mv304_01 "Knows method"
label variable mv304_02 "Knows method"
label variable mv304_03 "Knows method"
label variable mv304_04 "Knows method"
label variable mv304_05 "Knows method"
label variable mv304_06 "Knows method"
label variable mv304_07 "Knows method"
label variable mv304_08 "Knows method"
label variable mv304_09 "Knows method"
label variable mv304_10 "Knows method"
label variable mv304_11 "Knows method"
label variable mv304_12 "Knows method"
label variable mv304_13 "Knows method"
label variable mv304_14 "Knows method"
label variable mv304_15 "Knows method"
label variable mv304_16 "Knows method"
label variable mv304_17 "Knows method"
label variable mv304_18 "Knows method"
label variable mv304_19 "Knows method"
label variable mv304_20 "Knows method"
label variable mv305_01 "Ever used method"
label variable mv305_02 "Ever used method"
label variable mv305_03 "Ever used method"
label variable mv305_04 "Ever used method"
label variable mv305_05 "Ever used method"
label variable mv305_06 "Ever used method"
label variable mv305_07 "Ever used method"
label variable mv305_08 "Ever used method"
label variable mv305_09 "Ever used method"
label variable mv305_10 "Ever used method"
label variable mv305_11 "Ever used method"
label variable mv305_12 "Ever used method"
label variable mv305_13 "Ever used method"
label variable mv305_14 "Ever used method"
label variable mv305_15 "Ever used method"
label variable mv305_16 "Ever used method"
label variable mv305_17 "Ever used method"
label variable mv305_18 "Ever used method"
label variable mv305_19 "Ever used method"
label variable mv305_20 "Ever used method"
label variable mv307_01 "Method currently used"
label variable mv307_02 "Method currently used"
label variable mv307_03 "Method currently used"
label variable mv307_04 "Method currently used"
label variable mv307_05 "Method currently used"
label variable mv307_06 "Method currently used"
label variable mv307_07 "Method currently used"
label variable mv307_08 "Method currently used"
label variable mv307_09 "Method currently used"
label variable mv307_10 "Method currently used"
label variable mv307_11 "Method currently used"
label variable mv307_12 "Method currently used"
label variable mv307_13 "Method currently used"
label variable mv307_14 "Method currently used"
label variable mv307_15 "Method currently used"
label variable mv307_16 "Method currently used"
label variable mv307_17 "Method currently used"
label variable mv307_18 "Method currently used"
label variable mv307_19 "Method currently used"
label variable mv307_20 "Method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current use by method type"
label variable mv323a   "Brand of condom used"
label variable mv325b   "Cost of condoms last time obtained"
label variable mv372a   "Shown condom package       -NA"
label variable mv384a   "Heard FP on radio last months"
label variable mv384b   "Heard FP on TV last months"
label variable mv384c   "Heard FP newspaper last months"
label variable mv395    "Discuused FP with health worker last few months"
label variable mv396    "Can a woman who is breastfeeding get pregnant"
label variable mv3a09b  "How many condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Cheweing  tobacco"
label variable mv463d   "Smokes Snuff"
label variable mv463e   "Smokes country specific    -NA"
label variable mv463f   "Smokes country specific    -NA"
label variable mv463g   "Smokes country specific    -NA"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "Heard of Tuberculosis or TB"
label variable mv474a   "Tuberculosis spread by: air when coughing or sneezing"
label variable mv474b   "Tuberculosis spread by: sharing utensils"
label variable mv474c   "Tuberculosis spread by: touching a person with TB"
label variable mv474d   "Tuberculosis spread through food"
label variable mv474e   "Tuberculosis spread by: sexual contact"
label variable mv474f   "Tuberculosis spread by: mosquito bites"
label variable mv474g   "Tuberculosis spread by: Smoking (CS)"
label variable mv474h   "Tuberculosis spread by: CS -NA"
label variable mv474i   "Tuberculosis spread by: CS -NA"
label variable mv474j   "Tuberculosis spread by: CS -NA"
label variable mv474x   "Tuberculosis spread by: other"
label variable mv474z   "Tuberculosis spread by: don't know"
label variable mv475    "Can tuberculosis be cured"
label variable mv476    "Keep secret when family member gets TB"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Injections administered by a health worker"
label variable mv479    "Source for injection by health worker"
label variable mv480    "Syinge and needle from new, unopened package"
label variable mv481    "Covered by health insurance-NA"
label variable mv481a   "Health insurance type: mutu-NA"
label variable mv481b   "Health insurance type: prov-NA"
label variable mv481c   "Health insurance type: soci-NA"
label variable mv481d   "Health insurance type: priv-NA"
label variable mv481e   "Health insurance type: CS  -NA"
label variable mv481f   "Health insurance type: CS  -NA"
label variable mv481g   "Health insurance type: CS  -NA"
label variable mv481h   "Health insurance type: CS  -NA"
label variable mv481x   "Health insurance type: othe-NA"
label variable mv482a   "Arrange care of biological -NA"
label variable mv482b   "Primary caregiver of childr-NA"
label variable mv482c   "Arrange care of non-biologi-NA"
label variable mv483    "Is respondent circumcised"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never marr."
label variable mv503    "Number of unions"
label variable mv504    "Wife/partner lives with respondent"
label variable mv505    "Number of wives, partners"
label variable mv507    "Month of first marriage"
label variable mv508    "Year of first marriage"
label variable mv509    "Date of first marriage (CMC)"
label variable mv510    "Completeness of date inform."
label variable mv511    "Age at first marriage"
label variable mv512    "Years since first marriage"
label variable mv513    "Marital duration (grouped)"
label variable mv525    "Age at first intercourse"
label variable mv527    "Time since last intercourse"
label variable mv528    "Time since last intercourse(g)"
label variable mv529    "Time since last intercourse(imputed)"
label variable mv531    "Age at first intercourse (imp)"
label variable mv532    "Flag for MV531"
label variable mv535    "Have ever been married"
label variable mv536    "Recent sexual activity"
label variable mv541    "Intend to wait until married to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time"
label variable mv604    "Preferred waiting time (grpd)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grp)"
label variable mv616    "Time for future birth"
label variable mv621    "Wifes desire for children  -NA"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "Problem if became pregnant -NA"
label variable mv633a   "Reason for not having sex: Husband has STD"
label variable mv633b   "Reason for not having sex: Husband has other women"
label variable mv633c   "Reason for not having sex: Recent birth"
label variable mv633d   "Reason for not having sex: Tired, mood"
label variable mv633e   "Reason for not having sex: -NA"
label variable mv633f   "Reason for not having sex: -NA"
label variable mv633g   "Reason for not having sex: -NA"
label variable mv634a   "Husband has right to: get angry"
label variable mv634b   "Husband has right to: refuse financial support"
label variable mv634c   "Husband has right to: use force for unwanted sex"
label variable mv634d   "Husband has right to: have sex with another women"
label variable mv714    "Respondent currently working"
label variable mv714a   "Have a job from which respondent was absent"
label variable mv716    "Respondent's occupation"
label variable mv717    "Respondent's occupation"
label variable mv719    "Work for family, others, se-NA"
label variable mv721    "Works at home or away      -NA"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasona-NA"
label variable mv739    "Who decides how to spend mo-NA"
label variable mv740    "Type of land where resp. works"
label variable mv741    "Type of earnings for work"
label variable mv743a   "Final say on own health car-NA"
label variable mv743b   "Final say on making large h-NA"
label variable mv743c   "Final say on making househo-NA"
label variable mv743d   "Final say on visits to fami-NA"
label variable mv743e   "Final say on food to be coo-NA"
label variable mv743f   "Final say on deciding what -NA"
label variable mv743g   "Final say on deciding how m-NA"
label variable mv744a   "Wife beating justified if she goes out without telling him"
label variable mv744b   "Wife beating justified if she neglects the children"
label variable mv744c   "Wife beating justified if she argues with him"
label variable mv744d   "Wife beating justified if she refuses to have sex with him"
label variable mv744e   "Wife beating justified if she burns the food"
label variable mv747a   "Childbearing is a woman's c-NA"
label variable mv747b   "Important for mother/child -NA"
label variable mv750    "Heard sexual transmit. disease"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "Reduce risk of getting AIDS by not having sex at all"
label variable mv754cp  "Reduce chances of AIDS by always using condoms during sex"
label variable mv754dp  "Reduce chance of AIDS: have 1 sex partner with no oth partnr"
label variable mv754jp  "Get AIDS from mosquito bites"
label variable mv754wp  "Get AIDS by sharing food with person who has AIDS"
label variable mv756    "Can a healthy person have AIDS"
label variable mv761    "Last intercourse used condom"
label variable mv761b   "Intercourse with other woman (1) used condom"
label variable mv761c   "Intercourse with other woman (2) used condom"
label variable mv762aa  "Source for condoms: Government hospital"
label variable mv762ab  "Source for condoms: Government health center/post"
label variable mv762ac  "Source for condoms: Family planning clinic"
label variable mv762ad  "Source for condoms: Mobile clinic"
label variable mv762ae  "Source for condoms: Public -NA"
label variable mv762af  "Source for condoms: Other public"
label variable mv762ag  "Source for condoms: Rural health center (CS)"
label variable mv762ah  "Source for condoms: ZNFPC CBD/Depot holder(CS)"
label variable mv762ai  "Source for condoms: Public -NA"
label variable mv762aj  "Source for condoms: Private hosp, clinic"
label variable mv762ak  "Source for condoms: Pharmacy"
label variable mv762al  "Source for condoms: Private doctor"
label variable mv762am  "Source for condoms: Private-NA"
label variable mv762an  "Source for condoms: Private-NA"
label variable mv762ao  "Source for condoms: Other private"
label variable mv762ap  "Source for condoms: Community Based Distribution (CBD) (CS)"
label variable mv762aq  "Source for condoms: Mission Facility (CS)"
label variable mv762ar  "Source for condoms: Private-NA"
label variable mv762as  "Source for condoms: Shop"
label variable mv762at  "Source for condoms: Church"
label variable mv762au  "Source for condoms: Friends, relatives"
label variable mv762av  "Source for condoms: Service Station (CS)"
label variable mv762aw  "Source for condoms: Other retail (CS)"
label variable mv762ax  "Source for condoms: Other"
label variable mv762az  "Source for condoms: DK source for condom"
label variable mv762ba  "Source for female condoms: Government hospital"
label variable mv762bb  "Source for female condoms: Government health center/post"
label variable mv762bc  "Source for female condoms: Family planning clinic"
label variable mv762bd  "Source for female condoms: Mobile clinic"
label variable mv762be  "Source for female condoms: -NA"
label variable mv762bf  "Source for female condoms: Other public"
label variable mv762bg  "Source for female condoms: Public CS"
label variable mv762bh  "Source for condoms: ZNFPC CBD/Depot holder(CS)"
label variable mv762bi  "Source for female condoms: -NA"
label variable mv762bj  "Source for female condoms: Private hosp, clinic"
label variable mv762bk  "Source for female condoms: Pharmacy"
label variable mv762bl  "Source for female condoms: Private doctor"
label variable mv762bm  "Source for female condoms: -NA"
label variable mv762bn  "Source for female condoms: -NA"
label variable mv762bo  "Source for female condoms: Other private"
label variable mv762bp  "Source for condoms: Community Based Distribution (CBD) (CS)"
label variable mv762bq  "Source for female condoms: Mission Facility (CS)"
label variable mv762br  "Source for female condoms: -NA"
label variable mv762bs  "Source for female condoms: Shop"
label variable mv762bt  "Source for female condoms: Church"
label variable mv762bu  "Source for female condoms: Friends, relatives"
label variable mv762bv  "Source for condoms: Service Station (CS)"
label variable mv762bw  "Source for condoms: Other retail (CS)"
label variable mv762bx  "Source for female condoms: Other"
label variable mv762bz  "Source for female condoms: DK source for condom"
label variable mv763a   "Had any STD in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "Last 12 months had CS STD  -NA"
label variable mv763e   "Last 12 months had CS STD  -NA"
label variable mv763f   "Last 12 months had CS STD  -NA"
label variable mv763g   "Last 12 months had CS STD  -NA"
label variable mv766a   "No. other than wife had sex in last 12 months"
label variable mv766b   "No. had sex including wife in last 12 months"
label variable mv767a   "Relationship with last sex partner"
label variable mv767b   "Relationship with other sex partner (1)"
label variable mv767c   "Relationship with other sex partner (2)"
label variable mv768a   "Length of time knows last partner"
label variable mv768b   "Length of time knows other partner (1)"
label variable mv768c   "Length of time knows other partner (2)"
label variable mv769    "Could get a condom"
label variable mv769a   "Could get a female condom"
label variable mv770    "Seek advice for last disease"
label variable mv770a   "Seek advice ITS: govt hospital"
label variable mv770b   "Seek advice ITS: health center"
label variable mv770c   "Seek advice ITS: public VCT-NA"
label variable mv770d   "Seek advice ITS: FP clinic"
label variable mv770e   "Seek advice ITS: mobile cli-NA"
label variable mv770f   "Seek advice ITS: fieldworke-NA"
label variable mv770g   "Seek advise ITS: Provincial hospital (CS)"
label variable mv770h   "Seek advise ITS: District /rural hospital (CS)"
label variable mv770i   "Seek advice ITS: CS public -NA"
label variable mv770j   "Seek advice ITS: other public"
label variable mv770k   "Seek advice ITS: private hosp/clinic/doctor"
label variable mv770l   "Seek advice ITS: private VC-NA"
label variable mv770m   "Seek advice ITS: pharmacy"
label variable mv770n   "Seek advice ITS: mobile cli-NA"
label variable mv770o   "Seek advice ITS: fieldworke-NA"
label variable mv770p   "Seek advise ITS: Mission Facility (CS)"
label variable mv770q   "Seek advice ITS: CS private-NA"
label variable mv770r   "Seek advice ITS: CS private-NA"
label variable mv770s   "Seek advice ITS: other private"
label variable mv770t   "Seek advice ITS: shop"
label variable mv770u   "Seek advice ITS: Relative, friend (CS)"
label variable mv770v   "Seek advice ITS: Traditional healer (CS)"
label variable mv770w   "Seek advice ITS: CS other  -NA"
label variable mv770x   "Seek advice other"
label variable mv774a   "AIDS transmit. during pregnancy"
label variable mv774b   "AIDS transmit. during delivery"
label variable mv774c   "AIDS transmit. by breastfeeding"
label variable mv775    "Knows someone who has or died of AIDS"
label variable mv777    "Allowed to keep AIDS infection secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "Person with AIDS allowed to continue teaching"
label variable mv780    "Should children be taught about condoms"
label variable mv781    "Ever been tested for AIDS"
label variable mv783    "Know a place to get AIDS test"
label variable mv784a   "Place for AIDS test: govt hospital"
label variable mv784b   "Place for AIDS test:health center"
label variable mv784c   "Place for AIDS test: public-NA"
label variable mv784d   "Place for AIDS test: FP clinic"
label variable mv784e   "Place for AIDS test: mobile-NA"
label variable mv784f   "Place for AIDS test: fieldw-NA"
label variable mv784g   "Place for AIDS test: Provincial Hospital (CS)"
label variable mv784h   "Place for AIDS test: District/Rural hospital (CS)"
label variable mv784i   "Place for AIDS test: CS pub-NA"
label variable mv784j   "Place for AIDS test: other public"
label variable mv784k   "Place for AIDS test: private hosp/clinic/doctor"
label variable mv784l   "Place for AIDS test: private VCT center"
label variable mv784m   "Place for AIDS test: pharma-NA"
label variable mv784n   "Place for AIDS test: mobile-NA"
label variable mv784o   "Place for AIDS test: fieldw-NA"
label variable mv784p   "Place for AIDS test: Mission facility (CS)"
label variable mv784q   "Place for AIDS test: Other Private VCT center"
label variable mv784r   "Place for AIDS test: CS pri-NA"
label variable mv784s   "Place for AIDS test: other private"
label variable mv784t   "Place for AIDS test: CS oth-NA"
label variable mv784u   "Place for AIDS test: CS oth-NA"
label variable mv784v   "Place for AIDS test: CS oth-NA"
label variable mv784x   "Place for AIDS test: other"
label variable mv785    "Heard about other STDs"
label variable mv793    "Paid for sex last 12 months"
label variable mv793a   "Condom used when paid for sex last 12 months"
label variable mv793b   "Condom used every time paid for sex last 12 months"
label variable mv820    "Condom used at first sexual intercourse"
label variable mv822    "Wife justified to ask husband to use condom if he has STD"
label variable mv823    "Can get AIDS by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid AIDS transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with AIDS"
label variable mv826    "When was last time you were tested"
label variable mv827    "Last test was on your own, offered or required"
label variable mv828    "Did get results for last test"
label variable mv829    "Place were last AIDS test was taken"
label variable mv832b   "Time since last intercourse with next to last sexual partner"
label variable mv832c   "Time since last intercourse with second to last sexual partner"
label variable mv833a   "Used condom every time had sex with last sex partner (last 12 months)"
label variable mv833b   "Used condom every time had sex with next to last sex partner (last 12 months)"
label variable mv833c   "Used condom every time had sex with second to last sex partner (last 12 months)"
label variable mv835a   "Alcohol consumption last time had sex"
label variable mv835b   "Alcohol consumption next to last time had sex"
label variable mv835c   "Alcohol consumption second to last time had sex"
label variable mv836    "Total lifetime number of sexual partners"
label variable mv837    "Heard of drugs to help infected people to live longer"
label variable mv844    "Knows someone denied health services because of AIDS last 12 months"
label variable mv845    "Knows someone denied social events because of AIDS last 12 months"
label variable mv846    "Knows someone verbally abused because of AIDS last 12 months"
label variable mv847    "People with AIDS should be ashamed of themselves"
label variable mv848    "People with AIDS should be blamed for bringing disease to community"
label variable mv849    "Children 12-14 should wait for sex until marriage"
label variable mv851a   "Young men should wait for s-NA"
label variable mv851b   "Most young men wait for sex-NA"
label variable mv851c   "Unmarried sexually active m-NA"
label variable mv851d   "Most unmarried sexually act-NA"
label variable mv851e   "Married men should only hav-NA"
label variable mv851f   "Most married men only have -NA"
label variable mv851g   "Young women should wait for-NA"
label variable mv851h   "Most young women wait for s-NA"
label variable mv851i   "Unmarried sexually active w-NA"
label variable mv851j   "Most unmarried sexually act-NA"
label variable mv851k   "Married women should only h-NA"
label variable mv851l   "Most married women only hav-NA"
label variable smlangq  "Language of questionnaire"
label variable smlangint "Language of interview"
label variable sminterp "Translator used"
label variable sm102    "Time lived in current place of residence in months/years (CS)"
label variable sm213    "Primary care giver for any children"
label variable sm215    "Made child care arrangements when unable to care for children"
label variable sm119    "How many services attended in last month"
label variable sm311c   "Woman can get pregnant, so she should be sterilized"
label variable sm313    "Male condom protects against pregnancy"
label variable sm315    "Female condom protects agai-NA"
label variable sm418    "Age of first sexual partner"
label variable sm419    "First sexual partner older, same age or younger"
label variable sm420    "First sexual partner 10 years older"
label variable sm423aa  "Reason used condom in last intercourse"
label variable sm423ab  "Reason used condom with other woman (1)"
label variable sm423ac  "Reason used condom with other woman (2)"
label variable sm428a   "Age of last sexual partner"
label variable sm429a   "Last sexual partner older, same age or younger"
label variable sm430a   "Last sexual partner 10 years older"
label variable sm428b   "Age of other sexual partner (1)"
label variable sm429b   "Other sexual partner (1) older, same age or younger"
label variable sm430b   "Other sexual partner (1) 10 years older"
label variable sm428c   "Age of other sexual partner (2)"
label variable sm429c   "Other sexual partner (2) older, same age or younger"
label variable sm430c   "Other sexual partner (2) 10 years older"
label variable sm441    "Privacy obtained"
label variable sm442    "Anyone forced respondent to intercourse in last 12 months"
label variable sm443    "Was physically forced to have sex"
label variable sm445    "Who obtained condom during last sex"
label variable sm451    "Used FP during last intercourse"
label variable sm452a   "Used during last intercourse : Female sterilization"
label variable sm452b   "Used during last intercourse : Male Sterilization"
label variable sm452c   "Used during last intercourse : Pill"
label variable sm452d   "Used during last intercourse : IUD"
label variable sm452e   "Used during last intercourse : Injections"
label variable sm452f   "Used during last intercourse : Implants"
label variable sm452g   "Used during last intercourse : Condom"
label variable sm452h   "Used during last intercourse : Female condom"
label variable sm452i   "Used during last intercourse : Diaphragm"
label variable sm452j   "Used during last intercourse : Foam, jelly"
label variable sm452k   "Used during last intercourse : Lactational amenorrhea"
label variable sm452l   "Used during last intercourse : Rhythm, periodic abstinence"
label variable sm452m   "Used during last intercourse : Withdrawal"
label variable sm452x   "Used during last intercourse : Other"
label variable sm452y   "Used during last intercourse : No method"
label variable sm456o   "Source for condoms: Supermarket"
label variable sm456p   "Source for condoms: Tuck shop"
label variable sm456n   "Source for condoms: General Dealer"
label variable sm459o   "Source for female condoms: Supermarket"
label variable sm459p   "Source for female condoms: Tuck shop"
label variable sm459n   "Source for female condoms: General Dealer"
label variable sm461a   "Decision on large HH purchases"
label variable sm461b   "Decision on small daily HH purchases"
label variable sm461c   "Decision to visit family, friends"
label variable sm461d   "Decision on use of wife's earnings"
label variable sm461e   "Decision on how many and when to have children"
label variable sm602    "Sex of last born child"
label variable sm603m   "Time of last birth (Month)"
label variable sm603y   "Time of last birth (Year)"
label variable sm604    "Child still alive"
label variable sm605    "Age at death"
label variable sm606    "Line number of mother of last born"
label variable sm609    "Relationship with last born's mother"
label variable sm610p   "Pregnancy : Mother received advice or care"
label variable sm611p   "Pregnancy : Provider of money or  goods to pay for the care"
label variable sm612p   "Pregnancy : Reason did not receive care"
label variable sm610d   "Delivery : Mother received advice or care"
label variable sm611d   "Delivery : Provider of money or  goods to pay for the care"
label variable sm612d   "Delivery : Reason did not receive care"
label variable sm610pd  "m"
label variable sm611pd  "Post-Delivery : Provider of money or  goods to pay for the care"
label variable sm612pd  "Post-Delivery : Reason did not receive care"
label variable sm613    "Post-Delivery : Talked to health provider about mother's health during preg."
label variable sm709a   "Means of avoiding AIDS : Abstain from sex"
label variable sm709b   "Means of avoiding AIDS : Use condoms"
label variable sm709c   "Means of avoiding AIDS : Limit sex to 1 partner"
label variable sm709d   "Means of avoiding AIDS : Limit number of partner"
label variable sm709e   "Means of avoiding AIDS : Avoid prostitutes"
label variable sm709f   "Means of avoiding AIDS : Avoid sex w/person with more than 1 partner"
label variable sm709g   "Means of avoiding AIDS : Avoid sex with homosexuals"
label variable sm709h   "Means of avoiding AIDS : Avoid sex with intravenous drug users"
label variable sm709i   "Means of avoiding AIDS : Avoid blood transfusions"
label variable sm709j   "Means of avoiding AIDS : Avoid injections"
label variable sm709k   "Means of avoiding AIDS : Avoid sharing razors"
label variable sm709l   "Means of avoiding AIDS : Avoid kissing"
label variable sm709m   "Means of avoiding AIDS : Avoid mosquito bites"
label variable sm709n   "Means of avoiding AIDS : Seek protection of traditional healer"
label variable sm709w   "Means of avoiding AIDS : Other"
label variable sm709x   "Means of avoiding AIDS : Other"
label variable sm709z   "Means of avoiding AIDS : Don't know"
label variable sm710    "Risk of getting AIDS"
label variable sm722    "Informed partner about result of HIV test"
label variable sm723    "Main reason have not been tested for HIV"
label variable sm727    "Husband/partner ever have HIV test"
label variable sm728    "Husband tell you results of his HIV test"
label variable sm732a   "Male teacher with AIDS virus allowed to continue teaching"
label variable sm740    "Agree that 1 married partner can be HIV+ and not infect the other"
label variable sm813    "Condom protects agains STD's"
label variable sm815    "Female condom protects against STD's"
label variable smmc1    "Number of siblings of resp."
label variable smmc2    "Preceding births before resp."
label variable smmc5    "Cut off age"
label variable smidx_01 "Maternal mortality index"
label variable smidx_02 "Maternal mortality index"
label variable smidx_03 "Maternal mortality index"
label variable smidx_04 "Maternal mortality index"
label variable smidx_05 "Maternal mortality index"
label variable smidx_06 "Maternal mortality index"
label variable smidx_07 "Maternal mortality index"
label variable smidx_08 "Maternal mortality index"
label variable smidx_09 "Maternal mortality index"
label variable smidx_10 "Maternal mortality index"
label variable smidx_11 "Maternal mortality index"
label variable smidx_12 "Maternal mortality index"
label variable smidx_13 "Maternal mortality index"
label variable smidx_14 "Maternal mortality index"
label variable smidx_15 "Maternal mortality index"
label variable smidx_16 "Maternal mortality index"
label variable smidx_17 "Maternal mortality index"
label variable smidx_18 "Maternal mortality index"
label variable smidx_19 "Maternal mortality index"
label variable smidx_20 "Maternal mortality index"
label variable smm1_01  "Sex of sibling"
label variable smm1_02  "Sex of sibling"
label variable smm1_03  "Sex of sibling"
label variable smm1_04  "Sex of sibling"
label variable smm1_05  "Sex of sibling"
label variable smm1_06  "Sex of sibling"
label variable smm1_07  "Sex of sibling"
label variable smm1_08  "Sex of sibling"
label variable smm1_09  "Sex of sibling"
label variable smm1_10  "Sex of sibling"
label variable smm1_11  "Sex of sibling"
label variable smm1_12  "Sex of sibling"
label variable smm1_13  "Sex of sibling"
label variable smm1_14  "Sex of sibling"
label variable smm1_15  "Sex of sibling"
label variable smm1_16  "Sex of sibling"
label variable smm1_17  "Sex of sibling"
label variable smm1_18  "Sex of sibling"
label variable smm1_19  "Sex of sibling"
label variable smm1_20  "Sex of sibling"
label variable smm2_01  "Sibling's survival status"
label variable smm2_02  "Sibling's survival status"
label variable smm2_03  "Sibling's survival status"
label variable smm2_04  "Sibling's survival status"
label variable smm2_05  "Sibling's survival status"
label variable smm2_06  "Sibling's survival status"
label variable smm2_07  "Sibling's survival status"
label variable smm2_08  "Sibling's survival status"
label variable smm2_09  "Sibling's survival status"
label variable smm2_10  "Sibling's survival status"
label variable smm2_11  "Sibling's survival status"
label variable smm2_12  "Sibling's survival status"
label variable smm2_13  "Sibling's survival status"
label variable smm2_14  "Sibling's survival status"
label variable smm2_15  "Sibling's survival status"
label variable smm2_16  "Sibling's survival status"
label variable smm2_17  "Sibling's survival status"
label variable smm2_18  "Sibling's survival status"
label variable smm2_19  "Sibling's survival status"
label variable smm2_20  "Sibling's survival status"
label variable smm3_01  "Sibling's current age"
label variable smm3_02  "Sibling's current age"
label variable smm3_03  "Sibling's current age"
label variable smm3_04  "Sibling's current age"
label variable smm3_05  "Sibling's current age"
label variable smm3_06  "Sibling's current age"
label variable smm3_07  "Sibling's current age"
label variable smm3_08  "Sibling's current age"
label variable smm3_09  "Sibling's current age"
label variable smm3_10  "Sibling's current age"
label variable smm3_11  "Sibling's current age"
label variable smm3_12  "Sibling's current age"
label variable smm3_13  "Sibling's current age"
label variable smm3_14  "Sibling's current age"
label variable smm3_15  "Sibling's current age"
label variable smm3_16  "Sibling's current age"
label variable smm3_17  "Sibling's current age"
label variable smm3_18  "Sibling's current age"
label variable smm3_19  "Sibling's current age"
label variable smm3_20  "Sibling's current age"
label variable smm6_01  "Years ago sibling died"
label variable smm6_02  "Years ago sibling died"
label variable smm6_03  "Years ago sibling died"
label variable smm6_04  "Years ago sibling died"
label variable smm6_05  "Years ago sibling died"
label variable smm6_06  "Years ago sibling died"
label variable smm6_07  "Years ago sibling died"
label variable smm6_08  "Years ago sibling died"
label variable smm6_09  "Years ago sibling died"
label variable smm6_10  "Years ago sibling died"
label variable smm6_11  "Years ago sibling died"
label variable smm6_12  "Years ago sibling died"
label variable smm6_13  "Years ago sibling died"
label variable smm6_14  "Years ago sibling died"
label variable smm6_15  "Years ago sibling died"
label variable smm6_16  "Years ago sibling died"
label variable smm6_17  "Years ago sibling died"
label variable smm6_18  "Years ago sibling died"
label variable smm6_19  "Years ago sibling died"
label variable smm6_20  "Years ago sibling died"
label variable smm7_01  "Sibling's age at death"
label variable smm7_02  "Sibling's age at death"
label variable smm7_03  "Sibling's age at death"
label variable smm7_04  "Sibling's age at death"
label variable smm7_05  "Sibling's age at death"
label variable smm7_06  "Sibling's age at death"
label variable smm7_07  "Sibling's age at death"
label variable smm7_08  "Sibling's age at death"
label variable smm7_09  "Sibling's age at death"
label variable smm7_10  "Sibling's age at death"
label variable smm7_11  "Sibling's age at death"
label variable smm7_12  "Sibling's age at death"
label variable smm7_13  "Sibling's age at death"
label variable smm7_14  "Sibling's age at death"
label variable smm7_15  "Sibling's age at death"
label variable smm7_16  "Sibling's age at death"
label variable smm7_17  "Sibling's age at death"
label variable smm7_18  "Sibling's age at death"
label variable smm7_19  "Sibling's age at death"
label variable smm7_20  "Sibling's age at death"
label variable smm9_01  "Sibling's death & pregnancy"
label variable smm9_02  "Sibling's death & pregnancy"
label variable smm9_03  "Sibling's death & pregnancy"
label variable smm9_04  "Sibling's death & pregnancy"
label variable smm9_05  "Sibling's death & pregnancy"
label variable smm9_06  "Sibling's death & pregnancy"
label variable smm9_07  "Sibling's death & pregnancy"
label variable smm9_08  "Sibling's death & pregnancy"
label variable smm9_09  "Sibling's death & pregnancy"
label variable smm9_10  "Sibling's death & pregnancy"
label variable smm9_11  "Sibling's death & pregnancy"
label variable smm9_12  "Sibling's death & pregnancy"
label variable smm9_13  "Sibling's death & pregnancy"
label variable smm9_14  "Sibling's death & pregnancy"
label variable smm9_15  "Sibling's death & pregnancy"
label variable smm9_16  "Sibling's death & pregnancy"
label variable smm9_17  "Sibling's death & pregnancy"
label variable smm9_18  "Sibling's death & pregnancy"
label variable smm9_19  "Sibling's death & pregnancy"
label variable smm9_20  "Sibling's death & pregnancy"
label variable sm913_01 "Death due to accident"
label variable sm913_02 "Death due to accident"
label variable sm913_03 "Death due to accident"
label variable sm913_04 "Death due to accident"
label variable sm913_05 "Death due to accident"
label variable sm913_06 "Death due to accident"
label variable sm913_07 "Death due to accident"
label variable sm913_08 "Death due to accident"
label variable sm913_09 "Death due to accident"
label variable sm913_10 "Death due to accident"
label variable sm913_11 "Death due to accident"
label variable sm913_12 "Death due to accident"
label variable sm913_13 "Death due to accident"
label variable sm913_14 "Death due to accident"
label variable sm913_15 "Death due to accident"
label variable sm913_16 "Death due to accident"
label variable sm913_17 "Death due to accident"
label variable sm913_18 "Death due to accident"
label variable sm913_19 "Death due to accident"
label variable sm913_20 "Death due to accident"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV023   
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define MV024   
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in HH"
;
label define MV034A  
     9 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     9 "Missing"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
    99 "Missing"
;
label define MV130   
     1 "Traditional"
     2 "Roman Catholic"
     3 "Protestant"
     4 "Pentecostal"
     5 "Apostolic Sect"
     6 "Other Christian"
     7 "Muslim"
     8 "None"
    96 "Other"
;
label define MV131   
    99 "Missing"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nehew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "DK"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
    97 "Inconsistent"
    98 "DK"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     9 "Missing"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     9 "Missing"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     9 "Missing"
;
label define MV249   
     9 "Missing"
;
label define MV250   
     9 "Missing"
;
label define MV251   
    99 "Missing"
;
label define MV252   
     9 "Missing"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
     1 "Choice assorted"
     2 "Durex"
     3 "Ecstasy"
     4 "Protecta"
     5 "Public sector dist."
     6 "Rough rider"
     7 "Other male condom"
     8 "Male condom, don't know"
     9 "Care"
    10 "Other female condom"
    12 "Female condom, don't know"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     9 "Missing"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "DK"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "DK"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    10 "PUBLIC SECTOR"
    11 "Government hospital/clinic"
    12 "Rural/Municipal clinic"
    13 "Rural Health centre"
    14 "ZNFPC clinic"
    15 "MOH Mobile Clinic"
    16 "ZNFPC CBD/Depot holder"
    17 "Other public"
    20 "PRIVATE MEDICAL SECTOR"
    21 "Private Hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "CBD"
    25 "Mission facility"
    26 "Other private medical"
    30 "OTHER SOURCE"
    31 "Church"
    32 "Friend/relative"
    33 "General dealer"
    34 "Supermarket"
    35 "Tuck shop"
    36 "Service station"
    37 "Other retail"
    96 "OTHER"
    98 "Don't know"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "DK"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "DK"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     9 "Missing"
;
label define MV463F  
     9 "Missing"
;
label define MV463G  
     9 "Missing"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    99 "Missing"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     9 "Missing"
;
label define MV474I  
     9 "Missing"
;
label define MV474J  
     9 "Missing"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know / not sure / depends"
;
label define MV477   
     0 "None"
    95 "95+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    11 "Government hospital/clinic"
    12 "Rural/Municipal clinic"
    13 "Rural Health centre"
    14 "ZNFPC clinic"
    15 "MOH Mobile clinic"
    16 "ZNFPC CBD/Depot holder"
    17 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private Hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "CBD"
    25 "Mission facility"
    26 "Other private medical"
    30 "OTHERS NON-MEDICAL"
    31 "General dealer"
    32 "Supermarket"
    33 "Tuck stop"
    34 "Other retail"
    35 "Church"
    36 "Friend/relative"
    37 "Service station"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     9 "Missing"
;
label define MV481A  
     9 "Missing"
;
label define MV481B  
     9 "Missing"
;
label define MV481C  
     9 "Missing"
;
label define MV481D  
     9 "Missing"
;
label define MV481E  
     9 "Missing"
;
label define MV481F  
     9 "Missing"
;
label define MV481G  
     9 "Missing"
;
label define MV481H  
     9 "Missing"
;
label define MV481X  
     9 "Missing"
;
label define MV482A  
     9 "Missing"
;
label define MV482C  
     9 "Missing"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV501   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define MV502   
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infecund"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "DK"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
;
label define MV621   
     9 "Missing"
;
label define MV627   
    96 "Other"
    98 "DK"
;
label define MV628   
    96 "Other"
    98 "DK"
;
label define MV629   
    96 "Other"
    98 "DK"
;
label define MV631   
     9 "Missing"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV633E  
     9 "Missing"
;
label define MV633F  
     9 "Missing"
;
label define MV633G  
     9 "Missing"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "DK, Depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working"
    11 "Armed Forces"
   111 "Legislators"
   112 "Senior Government Officials"
   113 "Traditional Chiefs And Heads Of Villages"
   114 "Senior Officials Of Special Interest Groups"
   115 "Other Government And Senior Officials"
   121 "Directors And Chief Executives"
   122 "Managers And Company Secretaries"
   211 "Physicists And Related Professional"
   212 "Mathematicians, Statisticians And Related Professionals"
   213 "Computing Professionals And Associates"
   214 "Architects And Associated Professionals"
   215 "Engineers - All Types"
   221 "Life Science Professionals"
   222 "Medical Doctors - All Types Except Dentists"
   223 "Nursing And Midwifery Professionals"
   224 "Dentists"
   225 "Veterinarians - All Types"
   226 "Pharmaceuticals Chemists, Pharmacists, Pharmacologists"
   227 "Other Health Professionals"
   231 "College/ University And Higher Education Teaching"
   232 "Secondary Education Teaching Professionals"
   233 "Primary Education Teaching Professionals"
   234 "Special Education Teaching Professionals"
   235 "Other Teaching Professionals"
   236 "Pre-Primary Teachers Including Associates"
   237 "Adult Education And Literacy Teachers"
   241 "Business Professionals"
   242 "Legal Professionals"
   243 "Archivists, Librarians And Related Professionals"
   244 "Social Science And Related Professionals"
   245 "Writers And Creative Or Performance Artists"
   246 "Religion"
   247 "Artistic/ Entertainment And Sports Associate Professiona"
   311 "Physical And Engineering Science Technicians"
   313 "Optical And Electronic Machine Operators"
   314 "Ship And Aircraft Controllers And Technicians"
   315 "Safety Quality Inspectors"
   316 "Technicians - Uncertified"
   321 "Life Science Technicians And Related Professionals"
   322 "Modern Health Associated Professionals (Except Nurses)"
   323 "Medical Assistants"
   324 "Traditional Medicine Practitioners And Faith Healers"
   325 "Temporary (Untrained) Secondary Teachers"
   332 "Temporary (Untrained) Primary Teachers"
   334 "Other Teaching Associate Professionals"
   341 "Finance And Sales Associate Professionals"
   342 "Business Services Agents And Trade Brokers"
   343 "Administrative Associate Professionals"
   344 "Customs, Tax And Related (Govt.) Associate Professional"
   345 "Police Inspectors And Detectives"
   411 "Secretaries And Keyboard Operator Clerks"
   412 "Numerical Clerks"
   413 "Material-Recording And Transport Clerks"
   414 "Library/ Mail And Related Clerks"
   419 "Other Office Clerks"
   421 "Cashiers/ Tellers And Related Clerks"
   422 "Client Information Clerks"
   423 "Other Clerks"
   511 "Travel Attendants And Related Workers"
   512 "Housekeeping And Restaurant Services Workers (Based In I"
   513 "Personal Care And Related Workers"
   514 "Other Personal Services Workers Hairdresser"
   515 "Astrologers/ Fortune-Tellers And Related Workers"
   516 "Protective Services Workers"
   517 "Domestic Workers (Private Homes)"
   521 "Fashion And Other Models"
   522 "Shop Salespersons And Demonstrators"
   523 "Stall And Market Salespersons"
   524 "Businesspersons"
   611 "Commercial Farmers"
   614 "Forestry And Related Workers"
   615 "Fishery Workers, Hunters And Trappers"
   621 "Communal Subsistence Agricultural Workers"
   711 "Miners/ Short-Firers, Stone Cutters And Carvers"
   712 "Building Frame And Related Trades Workers"
   713 "Building Finishers And Related Trades Workers"
   714 "Painters/ Building Structure Cleaners And Related Trades"
   715 "Gold Panners"
   721 "Metal Moulders/ Welders/ Sheet-Metal Workers, Structural"
   722 "Blacksmiths/ Tool-Makers And Related Trades Workers"
   723 "Machinery Mechanics And Fitters"
   724 "Electrical And Electronic Equipment Mechanics And Fitter"
   725 "Workshop Attendants"
   731 "Precision Workers In Metal And Related Materials"
   732 "Potters, Glass-Makers And Related Trades Workers"
   733 "Handicraft Workers In Wood, Textile, Leather And Related"
   734 "Printing And Related Trades Workers"
   741 "Food Processing And Related Trades Workers"
   742 "Wood Treaters Cabinet-Makers And Related Trades Workers"
   743 "Textile, Garment And Related Trades Workers"
   744 "Pelt, Leather And Shoe Making Trades Workers"
   811 "Plant And Machine Operators (All Types)"
   828 "Plant And Machine Assemblers (All Types)"
   829 "Other Machine Operators And Assemblers"
   831 "Locomotive Engine Drivers And Related Workers"
   832 "Motor Vehicle Drivers"
   833 "Agricultural And Other Mobile Plant Operators"
   834 "Ships Deck Crews And Related Workers"
   911 "Street Vendors And Related Workers (Goods)"
   912 "Shoe Cleaning And Other Street Services-Elementary Occup"
   913 "Domestic And Related Helpers, Cleaners And Launderers (N"
   914 "Building Caretakers/ Window And Related Cleaners"
   915 "Messengers/ Porters/ Doorkeepers And Related Workers"
   916 "Garbage Collectors And Related Labourers"
   921 "Agricultural/ Fishery And Related Labourers"
   931 "Mining And Construction Labourers"
   932 "Manufacturing Labourers"
   933 "Transport Labourers And Freight Handlers"
   996 "Not Elsewhere Classified"
;
label define MV717   
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define MV719   
     9 "Missing"
;
label define MV721   
     9 "Missing"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     9 "Missing"
;
label define MV739   
     9 "Missing"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and kind"
     3 "In kind only"
;
label define MV743A  
     9 "Missing"
;
label define MV743B  
     9 "Missing"
;
label define MV743C  
     9 "Missing"
;
label define MV743D  
     9 "Missing"
;
label define MV743E  
     9 "Missing"
;
label define MV743F  
     9 "Missing"
;
label define MV743G  
     9 "Missing"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV747A  
     9 "Missing"
;
label define MV747B  
     9 "Missing"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Reduce chances of AIDS by always using condoms during sex"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Reduce chance of AIDS: have 1 sex partnr with no oth partner"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Get AIDS from mosquito bites"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Get AIDS by sharing food with person who has AIDS"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV762AA 
     0 "No"
     1 "Yes: Government hospital"
;
label define MV762AB 
     0 "No"
     1 "Yes: Government health center/post"
;
label define MV762AC 
     0 "No"
     1 "Yes: Family planning clinic"
;
label define MV762AD 
     0 "No"
     1 "Yes: Mobile clinic"
;
label define MV762AE 
     9 "Missing"
;
label define MV762AF 
     0 "No"
     1 "Yes: Other public"
;
label define MV762AG 
     0 "No"
     1 "Yes: Rural health center (CS)"
;
label define MV762AH 
     0 "No"
     1 "Yes: ZNFPC CBD/Depot holder(CS)"
;
label define MV762AI 
     9 "Missing"
;
label define MV762AJ 
     0 "No"
     1 "Yes: Private hosp, clinic"
;
label define MV762AK 
     0 "No"
     1 "Yes: Pharmacy"
;
label define MV762AL 
     0 "No"
     1 "Yes: Private doctor"
;
label define MV762AM 
     9 "Missing"
;
label define MV762AN 
     9 "Missing"
;
label define MV762AO 
     0 "No"
     1 "Yes: Other private"
;
label define MV762AP 
     0 "No"
     1 "Yes: Community Based Distribution (CBD) (CS)"
;
label define MV762AQ 
     0 "No"
     1 "Yes: Mission Facility (CS)"
;
label define MV762AR 
     9 "Missing"
;
label define MV762AS 
     0 "No"
     1 "Yes: Shop"
;
label define MV762AT 
     0 "No"
     1 "Yes: Church"
;
label define MV762AU 
     0 "No"
     1 "Yes: Friends, relatives"
;
label define MV762AV 
     0 "No"
     1 "Yes: Service Station (CS)"
;
label define MV762AW 
     0 "No"
     1 "Yes: CS"
;
label define MV762AX 
     0 "No"
     1 "Yes: Other"
;
label define MV762AZ 
     0 "No"
     1 "Yes: DK source for condom"
;
label define MV762BA 
     0 "No"
     1 "Yes: Government hospital"
;
label define MV762BB 
     0 "No"
     1 "Yes: Government health center/post"
;
label define MV762BC 
     0 "No"
     1 "Yes: Family planning clinic"
;
label define MV762BD 
     0 "No"
     1 "Yes: Mobile clinic"
;
label define MV762BE 
     9 "Missing"
;
label define MV762BF 
     0 "No"
     1 "Yes: Other public"
;
label define MV762BG 
     0 "No"
     1 "Yes: Rural health center (CS)"
;
label define MV762BH 
     0 "No"
     1 "Yes: ZNFPC CBD/Depot holder(CS)"
;
label define MV762BI 
     9 "Missing"
;
label define MV762BJ 
     0 "No"
     1 "Yes: Private hosp, clinic"
;
label define MV762BK 
     0 "No"
     1 "Yes: Pharmacy"
;
label define MV762BL 
     0 "No"
     1 "Yes: Private doctor"
;
label define MV762BM 
     9 "Missing"
;
label define MV762BN 
     9 "Missing"
;
label define MV762BO 
     0 "No"
     1 "Yes: Other private"
;
label define MV762BP 
     0 "No"
     1 "Yes: Private CS"
;
label define MV762BQ 
     0 "No"
     1 "Yes: Mission Facility (CS)"
;
label define MV762BR 
     9 "Missing"
;
label define MV762BS 
     0 "No"
     1 "Yes: Shop"
;
label define MV762BT 
     0 "No"
     1 "Yes: Church"
;
label define MV762BU 
     0 "No"
     1 "Yes: Friends, relatives"
;
label define MV762BV 
     0 "No"
     1 "Yes: Service Station (CS)"
;
label define MV762BW 
     0 "No"
     1 "Yes: Other retail (CS)"
;
label define MV762BX 
     0 "No"
     1 "Yes: Other"
;
label define MV762BZ 
     0 "No"
     1 "Yes: DK source for female condom"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV763D  
     9 "Missing"
;
label define MV763E  
     9 "Missing"
;
label define MV763F  
     9 "Missing"
;
label define MV763G  
     9 "Missing"
;
label define MV766A  
    98 "DK"
;
label define MV766B  
    98 "DK"
;
label define MV767A  
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse/cohabiting partner"
     2 "Girlfriend/fiancee"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   100 "< 1 Day"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   100 "< 1 Day"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   100 "< 1 Day"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     9 "Missing"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     9 "Missing"
;
label define MV770F  
     9 "Missing"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     9 "Missing"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     9 "Missing"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     9 "Missing"
;
label define MV770O  
     9 "Missing"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     9 "Missing"
;
label define MV770R  
     9 "Missing"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     9 "Missing"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784B  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784C  
     9 "Missing"
;
label define MV784D  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784E  
     9 "Missing"
;
label define MV784F  
     9 "Missing"
;
label define MV784G  
     0 "No"
     1 "Yes: Provincial Hospital (CS)"
;
label define MV784H  
     0 "No"
     1 "Yes: District/Rural hospital (CS)"
;
label define MV784I  
     9 "Missing"
;
label define MV784J  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784K  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784L  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784M  
     9 "Missing"
;
label define MV784N  
     9 "Missing"
;
label define MV784O  
     9 "Missing"
;
label define MV784P  
     0 "No"
     1 "Yes: Mission facility (CS)"
;
label define MV784Q  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784R  
     9 "Missing"
;
label define MV784S  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV784T  
     9 "Missing"
;
label define MV784U  
     9 "Missing"
;
label define MV784V  
     9 "Missing"
;
label define MV784X  
     0 "No"
     1 "Yes: Government hospital"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    10 "PUBLIC SECTOR"
    11 "Central hospital"
    12 "Provincial hospital"
    13 "District/rural hospital"
    14 "Rural health centre"
    15 "Municipal clinic"
    16 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private hospital/clinic"
    22 "New start centre"
    23 "Private VCT centre"
    24 "Private doctor"
    25 "Mission facility"
    26 "Other private medical"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     2 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know / no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know / depends"
;
label define MV851A  
     9 "Missing"
;
label define MV851B  
     9 "Missing"
;
label define MV851C  
     9 "Missing"
;
label define MV851D  
     9 "Missing"
;
label define MV851E  
     9 "Missing"
;
label define MV851F  
     9 "Missing"
;
label define MV851G  
     9 "Missing"
;
label define MV851H  
     9 "Missing"
;
label define MV851I  
     9 "Missing"
;
label define MV851J  
     9 "Missing"
;
label define MV851K  
     9 "Missing"
;
label define MV851L  
     9 "Missing"
;
label define SMLANGQ 
     1 "Shona"
     2 "Ndebele"
     3 "English"
     4 "Other"
;
label define SMLANGINT
     1 "Shona"
     2 "Ndebele"
     3 "English"
     6 "Other"
;
label define SMINTERP
     0 "No"
     1 "Yes"
;
label define SM102   
   100 "< 1 month"
   101 "1 month"
   200 "< 1 year"
   201 "1 year"
   995 "Always"
   996 "Visitor"
;
label define SM213   
     0 "No"
     1 "Yes"
;
label define SM215   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define SM119   
     0 "Did not attend"
    98 "Don't know/not sure"
    99 "Missing"
;
label define SM311C  
     1 "Agree"
     2 "Disagree"
     8 "Don't know"
;
label define SM313   
     1 "Most of the time"
     2 "Sometimes"
     3 "Does not protect"
     8 "Don't know / unsure"
;
label define SM315   
     9 "Missing"
;
label define SM418   
    98 "Don't know"
;
label define SM419   
     1 "Older"
     2 "Younger"
     3 "About the same age"
     8 "Don't know / don't remember"
;
label define SM420   
     1 "Ten or more years older"
     2 "Less than ten years older"
     3 "Older, unsure how much"
;
label define SM423AA 
     1 "Prevent STD/section"
     2 "Prevent pregnancy"
     3 "Prevent STD/section and pregnancy"
     4 "Partner requested/insisted"
     6 "Other"
;
label define SM423AB 
     1 "Prevent STD/section"
     2 "Prevent pregnancy"
     3 "Prevent STD/section and pregnancy"
     4 "Partner requested/insisted"
     6 "Other"
;
label define SM423AC 
     1 "Prevent STD/section"
     2 "Prevent pregnancy"
     3 "Prevent STD/section and pregnancy"
     4 "Partner requested/insisted"
     6 "Other"
;
label define SM428A  
    98 "Don't know"
;
label define SM429A  
     1 "Older"
     2 "Younger"
     3 "About the same age"
     8 "Don't know / don't remember"
;
label define SM430A  
     1 "Ten or more years older"
     2 "Less than ten years older"
     3 "Older, unsure how much"
;
label define SM428B  
    98 "Don't know"
;
label define SM429B  
     1 "Older"
     2 "Younger"
     3 "About the same age"
     8 "Don't know / don't remember"
;
label define SM430B  
     1 "Ten or more years older"
     2 "Less than ten years older"
     3 "Older, unsure how much"
;
label define SM428C  
    98 "Don't know"
;
label define SM429C  
     1 "Older"
     2 "Younger"
     3 "About the same age"
     8 "Don't know / don't remember"
;
label define SM430C  
     1 "Ten or more years older"
     2 "Less than ten years older"
     3 "Older, unsure how much"
;
label define SM441   
     0 "No"
     1 "Yes"
;
label define SM442   
     0 "No"
     1 "Yes"
     3 "Refused to answer"
;
label define SM443   
     0 "No"
     1 "Yes"
     3 "Refused to answer"
;
label define SM445   
     1 "Man himself"
     2 "Partner"
     3 "Someone else"
;
label define SM451   
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452A  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452B  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452C  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452D  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452E  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452F  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452G  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452H  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452I  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452J  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452K  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452L  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452M  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452X  
     0 "No"
     1 "Yes"
     8 "Unsure, DK"
;
label define SM452Y  
     0 "No, used a method"
     1 "Yes, did not use a method"
     8 "Unsure, DK"
;
label define SM456O  
     0 "No"
     1 "Yes"
;
label define SM456P  
     0 "No"
     1 "Yes"
;
label define SM456N  
     0 "No"
     1 "Yes"
;
label define SM459O  
     0 "No"
     1 "Yes"
;
label define SM459P  
     0 "No"
     1 "Yes"
;
label define SM459N  
     0 "No"
     1 "Yes"
;
label define SM461A  
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM461B  
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM461C  
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM461D  
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM461E  
     1 "Husband"
     2 "Wife"
     3 "Both"
     8 "DK, depends"
;
label define SM602   
     1 "Boy"
     2 "Girl"
;
label define SM603M  
    97 "Inconsistent"
    98 "DK"
;
label define SM603Y  
  9997 "Inconsistent"
  9998 "Don't know"
;
label define SM604   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM606   
     0 "Not in HH"
    95 "Mother deceased"
;
label define SM609   
     1 "Current spouse"
     2 "Former spouse"
     3 "Current live-in partner"
     4 "Former live-in partner"
     5 "Regular sexual partner"
     6 "Woman is girlfriend, fiancée"
     7 "Occasional sexual partner"
     8 "Friend, acquaintance"
    96 "Other"
;
label define SM610P  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM611P  
     1 "Free"
     2 "Insurance"
     3 "Respondent"
     4 "Child's mother"
     5 "Respondent and child's mother"
     6 "Respondent's family"
     7 "Child's mothers' family"
    96 "Other"
;
label define SM612P  
     1 "Not necessary"
     2 "Not customary"
     3 "Respondent did not allow"
     4 "Too costly"
     5 "Too far, no transport"
     6 "Poor service"
     7 "Lack of knowledge"
    96 "Other"
;
label define SM610D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM611D  
     1 "Free"
     2 "Insurance"
     3 "Respondent"
     4 "Child's mother"
     5 "Respondent and child's mother"
     6 "Respondent's family"
     7 "Child's mothers' family"
    96 "Other"
;
label define SM612D  
     1 "Not necessary"
     2 "Not customary"
     3 "Respondent did not allow"
     4 "Too costly"
     5 "Too far, no transport"
     6 "Poor service"
     7 "Lack of knowledge"
    96 "Other"
;
label define SM610PD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM611PD 
     1 "Free"
     2 "Insurance"
     3 "Respondent"
     4 "Child's mother"
     5 "Respondent and child's mother"
     6 "Respondent's family"
     7 "Child's mothers' family"
    96 "Other"
;
label define SM612PD 
     1 "Not necessary"
     2 "Not customary"
     3 "Respondent did not allow"
     4 "Too costly"
     5 "Too far, no transport"
     6 "Poor service"
     7 "Lack of knowledge"
    96 "Other"
;
label define SM613   
     0 "No"
     1 "Yes"
;
label define SM709A  
     0 "No"
     1 "Yes"
;
label define SM709B  
     0 "No"
     1 "Yes"
;
label define SM709C  
     0 "No"
     1 "Yes"
;
label define SM709D  
     0 "No"
     1 "Yes"
;
label define SM709E  
     0 "No"
     1 "Yes"
;
label define SM709F  
     0 "No"
     1 "Yes"
;
label define SM709G  
     0 "No"
     1 "Yes"
;
label define SM709H  
     0 "No"
     1 "Yes"
;
label define SM709I  
     0 "No"
     1 "Yes"
;
label define SM709J  
     0 "No"
     1 "Yes"
;
label define SM709K  
     0 "No"
     1 "Yes"
;
label define SM709L  
     0 "No"
     1 "Yes"
;
label define SM709M  
     0 "No"
     1 "Yes"
;
label define SM709N  
     0 "No"
     1 "Yes"
;
label define SM709W  
     0 "No"
     1 "Yes"
;
label define SM709X  
     0 "No"
     1 "Yes"
;
label define SM709Z  
     0 "No"
     1 "Yes"
;
label define SM710   
     1 "Low"
     2 "Medium"
     3 "High"
     4 "No risk"
     8 "Don't know"
;
label define SM722   
     0 "No"
     1 "Yes"
     3 "No husband/partner"
;
label define SM723   
     1 "Can't afford it"
     2 "Don't know where to go"
     3 "Testing site difficult to get to"
     4 "Afraid of test result"
     5 "Fatalistic/nothing can be done"
     6 "Concerned about confidentiality"
     7 "No risk/not sexually active"
    96 "Other"
    98 "Don't know"
;
label define SM727   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define SM728   
     0 "No"
     1 "Yes"
;
label define SM732A  
     1 "Should be allowed"
     2 "Should not be allowed"
     8 "Don't know, not sure, depends"
;
label define SM740   
     1 "Agree"
     2 "Disagree"
     8 "DK"
;
label define SM813   
     1 "Most of the time"
     2 "Sometimes"
     3 "Does not protect"
     8 "Don't know / unsure"
;
label define SM815   
     1 "Most of the time"
     2 "Sometimes"
     3 "Does not protect"
     8 "Don't know / unsure"
;
label define SMMC1   
    99 "Missing"
;
label define SMMC2   
    99 "Missing"
;
label define SMMC5   
    10 "10 years"
    12 "12 years"
    13 "13 years"
    15 "15 years"
;
label define SMM1    
     1 "Male"
     2 "Female"
     8 "DK"
;
label define SMM2    
     0 "Dead"
     1 "Alive"
     8 "DK"
;
label define SMM3    
    97 "97+"
    98 "Don't know"
;
label define SMM6    
    97 "97+"
    98 "Don't know"
;
label define SMM7    
    97 "97+"
    98 "Don't know"
;
label define SMM9    
     0 "Never pregnant"
     1 "Death not related"
     2 "Died while pregnant"
     3 "Died during delivery"
     4 "Since delivery"
     5 "6 weeks after Deliv."
     6 "2 months after Deliv"
    98 "Don't know"
;
label define SM913   
     0 "No"
     1 "Yes"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv130    MV130   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv483    MV483   
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv731    MV731   
label values mv740    MV740   
label values mv741    MV741   
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770d   MV770D  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770m   MV770M  
label values mv770p   MV770P  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784d   MV784D  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784s   MV784S  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values smlangq  SMLANGQ 
label values smlangint SMLANGINT
label values sminterp SMINTERP
label values sm102    SM102   
label values sm213    SM213   
label values sm215    SM215   
label values sm119    SM119   
label values sm311c   SM311C  
label values sm313    SM313   
label values sm418    SM418   
label values sm419    SM419   
label values sm420    SM420   
label values sm423aa  SM423AA 
label values sm423ab  SM423AB 
label values sm423ac  SM423AC 
label values sm428a   SM428A  
label values sm429a   SM429A  
label values sm430a   SM430A  
label values sm428b   SM428B  
label values sm429b   SM429B  
label values sm430b   SM430B  
label values sm428c   SM428C  
label values sm429c   SM429C  
label values sm430c   SM430C  
label values sm441    SM441   
label values sm442    SM442   
label values sm443    SM443   
label values sm445    SM445   
label values sm451    SM451   
label values sm452a   SM452A  
label values sm452b   SM452B  
label values sm452c   SM452C  
label values sm452d   SM452D  
label values sm452e   SM452E  
label values sm452f   SM452F  
label values sm452g   SM452G  
label values sm452h   SM452H  
label values sm452i   SM452I  
label values sm452j   SM452J  
label values sm452k   SM452K  
label values sm452l   SM452L  
label values sm452m   SM452M  
label values sm452x   SM452X  
label values sm452y   SM452Y  
label values sm456o   SM456O  
label values sm456p   SM456P  
label values sm456n   SM456N  
label values sm459o   SM459O  
label values sm459p   SM459P  
label values sm459n   SM459N  
label values sm461a   SM461A  
label values sm461b   SM461B  
label values sm461c   SM461C  
label values sm461d   SM461D  
label values sm461e   SM461E  
label values sm602    SM602   
label values sm603m   SM603M  
label values sm603y   SM603Y  
label values sm604    SM604   
label values sm606    SM606   
label values sm609    SM609   
label values sm610p   SM610P  
label values sm611p   SM611P  
label values sm612p   SM612P  
label values sm610d   SM610D  
label values sm611d   SM611D  
label values sm612d   SM612D  
label values sm610pd  SM610PD 
label values sm611pd  SM611PD 
label values sm612pd  SM612PD 
label values sm613    SM613   
label values sm709a   SM709A  
label values sm709b   SM709B  
label values sm709c   SM709C  
label values sm709d   SM709D  
label values sm709e   SM709E  
label values sm709f   SM709F  
label values sm709g   SM709G  
label values sm709h   SM709H  
label values sm709i   SM709I  
label values sm709j   SM709J  
label values sm709k   SM709K  
label values sm709l   SM709L  
label values sm709m   SM709M  
label values sm709n   SM709N  
label values sm709w   SM709W  
label values sm709x   SM709X  
label values sm709z   SM709Z  
label values sm710    SM710   
label values sm722    SM722   
label values sm723    SM723   
label values sm727    SM727   
label values sm728    SM728   
label values sm732a   SM732A  
label values sm740    SM740   
label values sm813    SM813   
label values sm815    SM815   
label values smmc5    SMMC5   
label values smm1_01  SMM1    
label values smm1_02  SMM1    
label values smm1_03  SMM1    
label values smm1_04  SMM1    
label values smm1_05  SMM1    
label values smm1_06  SMM1    
label values smm1_07  SMM1    
label values smm1_08  SMM1    
label values smm1_09  SMM1    
label values smm1_10  SMM1    
label values smm1_11  SMM1    
label values smm1_12  SMM1    
label values smm1_13  SMM1    
label values smm1_14  SMM1    
label values smm1_15  SMM1    
label values smm1_16  SMM1    
label values smm1_17  SMM1    
label values smm1_18  SMM1    
label values smm1_19  SMM1    
label values smm1_20  SMM1    
label values smm2_01  SMM2    
label values smm2_02  SMM2    
label values smm2_03  SMM2    
label values smm2_04  SMM2    
label values smm2_05  SMM2    
label values smm2_06  SMM2    
label values smm2_07  SMM2    
label values smm2_08  SMM2    
label values smm2_09  SMM2    
label values smm2_10  SMM2    
label values smm2_11  SMM2    
label values smm2_12  SMM2    
label values smm2_13  SMM2    
label values smm2_14  SMM2    
label values smm2_15  SMM2    
label values smm2_16  SMM2    
label values smm2_17  SMM2    
label values smm2_18  SMM2    
label values smm2_19  SMM2    
label values smm2_20  SMM2    
label values smm3_01  SMM3    
label values smm3_02  SMM3    
label values smm3_03  SMM3    
label values smm3_04  SMM3    
label values smm3_05  SMM3    
label values smm3_06  SMM3    
label values smm3_07  SMM3    
label values smm3_08  SMM3    
label values smm3_09  SMM3    
label values smm3_10  SMM3    
label values smm3_11  SMM3    
label values smm3_12  SMM3    
label values smm3_13  SMM3    
label values smm3_14  SMM3    
label values smm3_15  SMM3    
label values smm3_16  SMM3    
label values smm3_17  SMM3    
label values smm3_18  SMM3    
label values smm3_19  SMM3    
label values smm3_20  SMM3    
label values smm6_01  SMM6    
label values smm6_02  SMM6    
label values smm6_03  SMM6    
label values smm6_04  SMM6    
label values smm6_05  SMM6    
label values smm6_06  SMM6    
label values smm6_07  SMM6    
label values smm6_08  SMM6    
label values smm6_09  SMM6    
label values smm6_10  SMM6    
label values smm6_11  SMM6    
label values smm6_12  SMM6    
label values smm6_13  SMM6    
label values smm6_14  SMM6    
label values smm6_15  SMM6    
label values smm6_16  SMM6    
label values smm6_17  SMM6    
label values smm6_18  SMM6    
label values smm6_19  SMM6    
label values smm6_20  SMM6    
label values smm7_01  SMM7    
label values smm7_02  SMM7    
label values smm7_03  SMM7    
label values smm7_04  SMM7    
label values smm7_05  SMM7    
label values smm7_06  SMM7    
label values smm7_07  SMM7    
label values smm7_08  SMM7    
label values smm7_09  SMM7    
label values smm7_10  SMM7    
label values smm7_11  SMM7    
label values smm7_12  SMM7    
label values smm7_13  SMM7    
label values smm7_14  SMM7    
label values smm7_15  SMM7    
label values smm7_16  SMM7    
label values smm7_17  SMM7    
label values smm7_18  SMM7    
label values smm7_19  SMM7    
label values smm7_20  SMM7    
label values smm9_01  SMM9    
label values smm9_02  SMM9    
label values smm9_03  SMM9    
label values smm9_04  SMM9    
label values smm9_05  SMM9    
label values smm9_06  SMM9    
label values smm9_07  SMM9    
label values smm9_08  SMM9    
label values smm9_09  SMM9    
label values smm9_10  SMM9    
label values smm9_11  SMM9    
label values smm9_12  SMM9    
label values smm9_13  SMM9    
label values smm9_14  SMM9    
label values smm9_15  SMM9    
label values smm9_16  SMM9    
label values smm9_17  SMM9    
label values smm9_18  SMM9    
label values smm9_19  SMM9    
label values smm9_20  SMM9    
label values sm913_01 SM913   
label values sm913_02 SM913   
label values sm913_03 SM913   
label values sm913_04 SM913   
label values sm913_05 SM913   
label values sm913_06 SM913   
label values sm913_07 SM913   
label values sm913_08 SM913   
label values sm913_09 SM913   
label values sm913_10 SM913   
label values sm913_11 SM913   
label values sm913_12 SM913   
label values sm913_13 SM913   
label values sm913_14 SM913   
label values sm913_15 SM913   
label values sm913_16 SM913   
label values sm913_17 SM913   
label values sm913_18 SM913   
label values sm913_19 SM913   
label values sm913_20 SM913   
