infix using "C:\COUNTRIES\ZW52\ZWBR52FL.dct"

label variable caseid   "Case Identification"
label variable bidx     "Birth column number"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Sample weight"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Current age - respondent"
label variable v013     "Age 5-year groups"
label variable v014     "Completeness of information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "CMC start of calendar"
label variable v018     "Row of month of interview"
label variable v019     "Length of calendar"
label variable v019a    "Number of calendar columns"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample stratum number"
label variable v023     "Sample domain"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "Keyer identification"
label variable v030     "Field supervisor"
label variable v031     "Field editor"
label variable v032     "Office editor"
label variable v033     "Ultimate area selection pro-NA"
label variable v034     "Line number of husband"
label variable v040     "Cluster altitude in meters"
label variable v042     "Household selection for hemoglobin"
label variable v043     "Selection for women's statu-NA"
label variable v044     "Selection for domestic violence module"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "Childhood place of residenc-NA"
label variable v104     "Years lived in place of res."
label variable v105     "Type of place of previous res."
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v113     "Source of drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Has electricity"
label variable v120     "Has radio"
label variable v121     "Has television"
label variable v122     "Has refrigerator"
label variable v123     "Has bicycle"
label variable v124     "Has motorcycle/scooter"
label variable v125     "Has car/truck"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity                  -NA"
label variable v133     "Education in single years"
label variable v134     "De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members"
label variable v137     "Number of children 5 and under"
label variable v138     "Number of eligible women in HH"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of res."
label variable v141     "De jure place of residence"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Has telephone"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable awfactw  "All woman factor - wealth index"
label variable v155     "Literacy"
label variable v156     "Ever participated in a literacy program outside of primary"
label variable v157     "Frequency of reading newpaper or magazine"
label variable v158     "Frequency of listening to radio"
label variable v159     "Frequency of watching television"
label variable v160     "Toilet facilities shared"
label variable v161     "Type of cooking fuel"
label variable v166     "Results of salt iodine test-NA"
label variable v167     "Number of trips in last 12 months"
label variable v168     "Away for more than one month in last 12 months"
label variable v190     "Wealth index"
label variable v191     "Wealth index factor score (5 decimals)"
label variable ml101    "Type of bednet(s) slept under last night"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "Date of first birth (CMC)"
label variable v212     "Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "Time since last menstrual perd"
label variable v216     "Menstruated in last six weeks"
label variable v217     "Knowledge of ovulatory cycle"
label variable v218     "Number of living children"
label variable v219     "Living children + current preg"
label variable v220     "Living children + curr preg 6+"
label variable v221     "Marriage to first birth int."
label variable v222     "Last birth to interview"
label variable v223     "Completeness of curr preg. inf"
label variable v224     "Entries in birth history"
label variable v225     "Current pregnancy wanted"
label variable v226     "Time since last period (comp)"
label variable v227     "Flag for last period"
label variable v228     "Ever had a terminated preg."
label variable v229     "Month pregnancy ended"
label variable v230     "Year pregnancy ended"
label variable v231     "CMC pregnancy ended"
label variable v232     "Completeness of last term. inf"
label variable v233     "Months when pregnancy ended"
label variable v234     "Other such pregnancies"
label variable v235     "Index last child prior to cal."
label variable v237     "Birth between last & interview"
label variable v238     "Births in last three years"
label variable v239     "Pregnancies terminated before calendar beginning"
label variable v240     "Month of last termination prior to calendar"
label variable v241     "Year of last termination prior to calendar"
label variable v242     "CMC termination ended prior to calendar"
label variable v243     "Completeness of last termination date prior to calendar"
label variable v310     "Living children at first use"
label variable v311     "Children at first use (grpd)"
label variable v312     "Current contraceptive method"
label variable v313     "Current use by method type"
label variable v315     "Month of start of use of method"
label variable v316     "Year of start of use of method"
label variable v317     "Date of start of use of method (CMC)"
label variable v318     "Completeness of information"
label variable v319     "Years since sterilization"
label variable v320     "Age at sterilization"
label variable v321     "Marital duration at sterilization"
label variable v322     "Parity at sterilization"
label variable v323     "Brand of pill used"
label variable v323a    "Brand of condom used"
label variable v325a    "Cost of current method"
label variable v326     "Last source for current users"
label variable v327     "Last source for users by type"
label variable v337     "Months of use of current method"
label variable v359     "Last method disc. last 5 years"
label variable v360     "Reason of last discontinuation"
label variable v361     "Pattern of use"
label variable v362     "Intention to use"
label variable v363     "Preferred future method"
label variable v364     "Contraceptive use & intention"
label variable v367     "Wanted last child"
label variable v372     "Shown pill package"
label variable v372a    "Shown condom package       -NA"
label variable v375a    "Main reason not using a met-NA"
label variable v376     "Main reason not to use a meth."
label variable v376a    "Would ever use method if marr."
label variable v379     "Source known for any method-NA"
label variable v380     "Source known for any method-NA"
label variable v384a    "Heard FP on radio last months"
label variable v384b    "Heard FP on TV last months"
label variable v384c    "Heard FP newspaper last months"
label variable v393     "Visited by FP worker last 12m"
label variable v394     "Visited health facil. last 12m"
label variable v395     "At health facility, told of FP"
label variable v3a00a   "Source of FP for non-users:  government hosp."
label variable v3a00b   "Source of FP for non-users:  govt health cntr"
label variable v3a00c   "Source of FP for non-users:  FP clinic"
label variable v3a00d   "Source of FP for non-users:  mobile clinic"
label variable v3a00e   "Source of FP for non-users:-NA"
label variable v3a00f   "Source of FP for non-users: Rural health centre (CS)"
label variable v3a00g   "Source of FP for non-users:  ZNFPC CBD/Depot holder"
label variable v3a00h   "Source of FP for non-users:-NA"
label variable v3a00i   "Source of FP for non-users:  oth public sector"
label variable v3a00j   "Source of FP for non-users:  private hosp/clin"
label variable v3a00k   "Source of FP for non-users:  private pharmacy"
label variable v3a00l   "Source of FP for non-users:  private doctor"
label variable v3a00m   "Source of FP for non-users:-NA"
label variable v3a00n   "Source of FP for non-users:-NA"
label variable v3a00o   "Source of FP for non-users: Community Based Distribution (CBD) (CS)"
label variable v3a00p   "Source of FP for non-users: Missiong facility (CS)"
label variable v3a00q   "Source of FP for non-users:-NA"
label variable v3a00r   "Source of FP for non-users:  oth med.priv sect"
label variable v3a00s   "Source of FP for non-users:  shop"
label variable v3a00t   "Source of FP for non-users:  church"
label variable v3a00u   "Source of FP for non-users:  friend, relative"
label variable v3a00v   "Source of FP for non-users:  Service Station (CS)"
label variable v3a00w   "Source of FP for non-users:  Other retail (CS)"
label variable v3a00x   "Source of FP for non-users:  Other"
label variable v3a00y   "Source of FP for non-users:  no source"
label variable v3a00z   "Source of FP for non-users:  any source"
label variable v3a01    "Told sterilization would mean no more children"
label variable v3a02    "Told about side effects"
label variable v3a03    "Told about side effects by -NA"
label variable v3a04    "Told how to deal with side effects"
label variable v3a05    "Told about other FP methods"
label variable v3a06    "Told about other FP methods by health or FP worker"
label variable v3a07    "First source for current method"
label variable v3a08a   "Reason not using: Not married"
label variable v3a08b   "Reason not using: Not having sex"
label variable v3a08c   "Reason not using: Infrequent sex"
label variable v3a08d   "Reason not using: Menopausal/hysterectomy"
label variable v3a08e   "Reason not using: Subfecund/infecund"
label variable v3a08f   "Reason not using: Postpartum amenorrheic"
label variable v3a08g   "Reason not using: Breastfeeding"
label variable v3a08h   "Reason not using: Fatalistic"
label variable v3a08i   "Reason not using: Respondent opposed"
label variable v3a08j   "Reason not using: Husband/partner opposed"
label variable v3a08k   "Reason not using: Others opposed"
label variable v3a08l   "Reason not using: Religious prohibition"
label variable v3a08m   "Reason not using: Knows no method"
label variable v3a08n   "Reason not using: Knows no source"
label variable v3a08o   "Reason not using: Health concerns"
label variable v3a08p   "Reason not using: Fear of side effects"
label variable v3a08q   "Reason not using: Lack of access/too far"
label variable v3a08r   "Reason not using: Costs too much"
label variable v3a08s   "Reason not using: Inconvenient to use"
label variable v3a08t   "Reason not using: Interferes with bodys processes"
label variable v3a08u   "Reason not using: Country s-NA"
label variable v3a08v   "Reason not using: Country s-NA"
label variable v3a08w   "Reason not using: Country s-NA"
label variable v3a08x   "Reason not using: Other"
label variable v3a08z   "Reason not using: Don't know"
label variable v3a09a   "How many pill cycles did get last time"
label variable v3a09b   "How many condoms did get la-NA"
label variable v401     "Last birth ceasarean section"
label variable v404     "Currently breastfeeding"
label variable v405     "Currently amenorrheic"
label variable v406     "Currently abstaining"
label variable v407     "Times breastfed during night"
label variable v408     "Times breastfed during day"
label variable v409     "Gave child plain water"
label variable v409a    "Gave child sugar water     -NA"
label variable v410     "Gave child juice           -NA"
label variable v410a    "Gave child tea or coffe"
label variable v411     "Gave child tinned/powder or fresh milk"
label variable v411a    "Gave child baby formula"
label variable v412     "Gave child fresh milk      -NA"
label variable v412a    "Gave child baby cereal"
label variable v412b    "Gave child other porridge/gruel"
label variable v413     "Gave child other liquid"
label variable v413a    "Gave child sugary drink (CS liquid)"
label variable v413b    "Gave child CS liquid       -NA"
label variable v413c    "Gave child CS liquid       -NA"
label variable v413d    "Gave child CS liquid       -NA"
label variable v414a    "Gave child CS foods        -NA"
label variable v414b    "Gave child CS foods        -NA"
label variable v414c    "Gave child CS foods        -NA"
label variable v414d    "Gave child CS foods        -NA"
label variable v414e    "Gave child bread, noodles, other made from grains"
label variable v414f    "Gave child potatoes, cassave, or other tubers"
label variable v414g    "Gave child eggs"
label variable v414h    "Gave child meat (beef, pork, lamb, chicken, etc)"
label variable v414i    "Gave child pumpkin, carrots, squash (yellow or orange inside)"
label variable v414j    "Gave child any dark green leafy vegetables"
label variable v414k    "Gave child mangoes, papayas, other vitamin A fruits"
label variable v414l    "Gave child any other fruits"
label variable v414m    "Gave child liver, heart, other organs"
label variable v414n    "Gave child fish or shellfish"
label variable v414o    "Gave child food made from beans, peas, lentis, nuts"
label variable v414p    "Gave child cheese, yogurt , other milk products"
label variable v414q    "Gave child oil, fats, butter, products made of them"
label variable v414r    "Gave child chocolates, sweets, candies, pastries, etc"
label variable v414s    "Gave child other solid-semisolid food"
label variable v414t    "Gave child chicken, duck or other birds (CS)"
label variable v414u    "Gave child peanut butter or other food from nuts (CS)"
label variable v415     "Drank from bottle with nipple"
label variable v416     "Heard of oral rehydration  -NA"
label variable v417     "Entries in maternity table"
label variable v418     "Entries in health table"
label variable v419     "Entries in height/weight table"
label variable v420     "Measurer's code            -NA"
label variable v421     "Assistant measurer's code  -NA"
label variable v426     "When child put to breast"
label variable v437     "Respondent's weight (kilos-1d)"
label variable v438     "Respondent's height (cms-1d)"
label variable v439     "Ht/A Percentile (resp.)"
label variable v440     "Ht/A Standard deviations (resp"
label variable v441     "Ht/A Percent ref. median (resp"
label variable v442     "Wt/Ht Percent ref. median (DHS"
label variable v443     "Wt/Ht Percent ref. median (Fog"
label variable v444     "Wt/Ht Percent ref. median (WHO"
label variable v444a    "Wt/Ht Std deviations(resp) DHS"
label variable v445     "Body mass index for respondent"
label variable v446     "Rohrer's index for respondent"
label variable v447     "Result of measurement of resp."
label variable v447a    "Women's age in years from household report"
label variable v452a    "Under age 18 (HH report)"
label variable v452b    "Line no. of parent/caretaker"
label variable v452c    "Read consent statement"
label variable v453     "Hemoglobin level (g/dl - 1 decimal)"
label variable v454     "Currently pregnant (household report)"
label variable v455     "Result of measuring (Hemoglobin)"
label variable v456     "Hemoglobin level adjusted by altitude (g/dl - 1 decimal)"
label variable v457     "Anemia level"
label variable v458     "Agrees to referral         -NA"
label variable v459     "Have bednet for sleeping (household report)"
label variable v460     "Children under 5 slept under bednet last night (HH report)"
label variable v461     "Respondent slept under bednet"
label variable v462     "Washed hands before prepari-NA"
label variable v463a    "Smokes cigarettes"
label variable v463b    "Smokes pipe"
label variable v463c    "Chewing tobacco"
label variable v463d    "Smokes snuff"
label variable v463e    "Smokes country specific    -NA"
label variable v463f    "Smokes country specific    -NA"
label variable v463g    "Smokes country specific    -NA"
label variable v463x    "Smokes other"
label variable v463z    "Smokes nothing"
label variable v464     "Number of cigarettes in last 24 hours"
label variable v465     "Disposal of youngest child's stools when not using toilet"
label variable v466     "When child is seriously ill-NA"
label variable v467a    "Getting medical help for se-NA"
label variable v467b    "Getting medical help for self: getting permission to go"
label variable v467c    "Getting medical help for self: getting money needed for tx"
label variable v467d    "Getting medical help for self: distance to health facility"
label variable v467e    "Getting medical help for self: having to take transport"
label variable v467f    "Getting medical help for self: not wanting to go alone"
label variable v467g    "Getting medical help for self: concern no female health prov"
label variable v467h    "Getting medical help for self: concern no provider"
label variable v467i    "Getting medical help for self: concern no drugs available"
label variable v467j    "Getting medical help for se-NA"
label variable v467k    "Getting medical help for se-NA"
label variable v467l    "Getting medical help for se-NA"
label variable v467m    "Getting medical help for se-NA"
label variable v468     "Columns used for Last Birth Only variables"
label variable v471a    "Mother had tinned, powdered or fresh milk"
label variable v471b    "Mother had tea or coffe"
label variable v471c    "Mother had any other liquid"
label variable v471d    "Mother had plain water (CS)"
label variable v471e    "Mother had sugary drink (CS liquid)"
label variable v471f    "Mother had CS liquid       -NA"
label variable v471g    "Mother had CS liquid       -NA"
label variable v472a    "Mother had CS foods        -NA"
label variable v472b    "Mother had CS foods        -NA"
label variable v472c    "Mother had CS foods        -NA"
label variable v472d    "Mother had CS foods        -NA"
label variable v472e    "Mother had bread, noodles, other made from grains"
label variable v472f    "Mother had potatoes, cassave, or other tubers"
label variable v472g    "Mother had eggs"
label variable v472h    "Mother had meat (beef, pork, lamb, chicken, etc)"
label variable v472i    "Mother had pumpkin, carrots, squash (yellow or orange inside)"
label variable v472j    "Mother had any dark green leafy vegetables"
label variable v472k    "Mother had mangoes, papayas, other vitamin A fruits"
label variable v472l    "Mother had any other fruits"
label variable v472m    "Mother had liver, heart, other organs"
label variable v472n    "Mother had fish or shellfish"
label variable v472o    "Mother had food made from beans, peas, lentis, nuts"
label variable v472p    "Mother had cheese, yogurt , other milk products"
label variable v472q    "Mother had oil, fats, butter, products made of them"
label variable v472r    "Mother had chocolates, sweets, candies, pastries, etc"
label variable v472s    "Mother had other solid-semisolid food"
label variable v472t    "Mother had chicken, duck or other bird"
label variable v472u    "Mother had peanut butter or other food from nuts"
label variable v473a    "Read consent statement (HIV)"
label variable v473b    "Result of measuring (HIV)"
label variable v474     "Heard of Tuberculosis or TB"
label variable v474a    "Tuberculosis spread by: air when coughing or sneezing"
label variable v474b    "Tuberculosis spread by: sharing utensils"
label variable v474c    "Tuberculosis spread by: touching a person with TB"
label variable v474d    "Tuberculosis spread through food"
label variable v474e    "Tuberculosis spread by: sexual contact"
label variable v474f    "Tuberculosis spread by: mosquito bites"
label variable v474g    "Tuberculosis spread by: CS -NA"
label variable v474h    "Tuberculosis spread by: CS -NA"
label variable v474i    "Tuberculosis spread by: CS -NA"
label variable v474j    "Tuberculosis spread by: CS -NA"
label variable v474x    "Tuberculosis spread by: other"
label variable v474z    "Tuberculosis spread by: don't know"
label variable v475     "Can tuberculosis be cured"
label variable v476     "Keep secret when family member gets TB"
label variable v477     "Number of injections in last 12 months"
label variable v478     "Injections administered by a health worker"
label variable v479     "Source for injection by health worker"
label variable v480     "Syringe and needle from new, unopened package"
label variable v481     "Covered by health insurance"
label variable v481a    "Health insurance type: mutu-NA"
label variable v481b    "Health insurance type: provided by employer"
label variable v481c    "Health insurance type: soci-NA"
label variable v481d    "Health insurance type: private/commercial purchased"
label variable v481e    "Health insurance type: CS  -NA"
label variable v481f    "Health insurance type: CS"
label variable v481g    "Health insurance type: CS"
label variable v481h    "Health insurance type: CS  -NA"
label variable v481x    "Health insurance type: other"
label variable v482a    "Arrange care of biological -NA"
label variable v482b    "Primary caregiver of childr-NA"
label variable v482c    "Arrange care of non-biologi-NA"
label variable v501     "Current marital status"
label variable v502     "Currently/formerly/never marr."
label variable v503     "Number of unions"
label variable v504     "Husband lives in house"
label variable v505     "Number of other wives"
label variable v506     "Wife rank number"
label variable v507     "Month of first marriage"
label variable v508     "Year of first marriage"
label variable v509     "Date of first marriage (CMC)"
label variable v510     "Completeness of date inform."
label variable v511     "Age at first marriage"
label variable v512     "Years since first marriage"
label variable v513     "Marital duration (grouped)"
label variable v525     "Age at first intercourse"
label variable v527     "Time since last intercourse"
label variable v528     "Time since last intercourse(g)"
label variable v529     "Time since last intercourse(imputed)"
label variable v530     "Flag for V529"
label variable v531     "Age at first intercourse (imp)"
label variable v532     "Flag for V531"
label variable v535     "Have ever been married"
label variable v536     "Recent sexual activity"
label variable v537     "Months of abstinence"
label variable v538     "How previous marriage or union ended"
label variable v539     "Who received most of late husbands property"
label variable v540     "Respondent received any of late husband's assets or valuables"
label variable v541     "Intends to postpone intercourse until marriage"
label variable v602     "Fertility preference"
label variable v603     "Preferred waiting time"
label variable v604     "Preferred waiting time (grpd)"
label variable v605     "Desire for more children"
label variable v613     "Ideal number of children"
label variable v614     "Ideal number of children (grp)"
label variable v616     "Time for future birth"
label variable v621     "Husbands desire for children"
label variable v623     "Exposure"
label variable v624     "Unmet need"
label variable v625     "Exposure (definition 2)"
label variable v626     "Unmet need (definition 2)"
label variable v627     "Ideal number of boys"
label variable v628     "Ideal number of girls"
label variable v629     "Ideal number of either sex"
label variable v631     "Problem if became pregnant -NA"
label variable v632     "Decision maker for using contraception"
label variable v633a    "Reason for not having sex: Husband has STD"
label variable v633b    "Reason for not having sex: Husband has other women"
label variable v633c    "Reason for not having sex: -NA"
label variable v633d    "Reason for not having sex: Tired, mood"
label variable v633e    "Reason for not having sex: -NA"
label variable v633f    "Reason for not having sex: -NA"
label variable v633g    "Reason for not having sex: -NA"
label variable v634     "Husband knows that respondent is using contraception"
label variable v701     "Partner's education level"
label variable v702     "Highest year of education"
label variable v704     "Partner's occupation"
label variable v705     "Partner's occupation"
label variable v714     "Respondent currently working"
label variable v714a    "Have a job from which respondent was absent"
label variable v715     "Husbands education-single yrs"
label variable v716     "Respondent's occupation"
label variable v717     "Respondent's occupation"
label variable v719     "Work for family, others, self"
label variable v721     "Works at home or away"
label variable v729     "Partner's educational attainm."
label variable v730     "Partners age"
label variable v731     "Worked in last 12 months"
label variable v732     "Employment all year/seasonal"
label variable v739     "Who decides how to spend money"
label variable v740     "Type of land where resp. works"
label variable v741     "Type of earnings for work"
label variable v743a    "Final say on own health care"
label variable v743b    "Final say on making large household purchases"
label variable v743c    "Final say on making household purchases for daily needs"
label variable v743d    "Final say on visits to family or relatives"
label variable v743e    "Final say on food to be coo-NA"
label variable v743f    "Final say on deciding what to do with money husband earns"
label variable v744a    "Wife beating justified if she goes out without telling him"
label variable v744b    "Wife beating justified if she neglects the children"
label variable v744c    "Wife beating justified if she argues with him"
label variable v744d    "Wife beating justified if she refuses to have sex with him"
label variable v744e    "Wife beating justified if she burns the food"
label variable v746     "Earns more than partner"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "Age at death"
label variable b7       "Age at death (months-imputed)"
label variable b8       "Current age of child"
label variable b9       "Child lives with whom"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval"
label variable b12      "Succeeding birth interval"
label variable b13      "Flag for age at death"
label variable b15      "Live birth between births"
label variable b16      "Child's line number in household"
label variable midx     "Index to birth history"
label variable m1       "Tetanus injections bef. birth"
label variable m1a      "Tetanus injections before pregnancy"
label variable m1b      "Month last tetanus injection before pregnancy"
label variable m1c      "Year last tetanus injection before pregnancy"
label variable m1d      "Years ago received last tetanus injection before pregnancy"
label variable m1e      "Last tetanus injection before pregnancy (CMC)"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "Prenatal: auxiliary midwife-NA"
label variable m2d      "Prenatal: CS health profess-NA"
label variable m2e      "Prenatal: CS health profess-NA"
label variable m2f      "Prenatal: trained birth att."
label variable m2g      "Prenatal: trad.birth attendant"
label variable m2h      "Prenatal: relative         -NA"
label variable m2i      "Prenatal: Unsure about training (CS)"
label variable m2j      "Prenatal: CS other person  -NA"
label variable m2k      "Prenatal: other resp (uncoded)"
label variable m2l      "Prenatal: CS other         -NA"
label variable m2m      "Prenatal: CS other         -NA"
label variable m2n      "Prenatal: no one"
label variable m3a      "Assistance: doctor"
label variable m3b      "Assistance: nurse/midwife"
label variable m3c      "Assistance: auxiliary midwi-NA"
label variable m3d      "Assistance: CS health profe-NA"
label variable m3e      "Assistance: CS health profe-NA"
label variable m3f      "Assistance: trained birth att."
label variable m3g      "Assistance: trad.birth attend."
label variable m3h      "Assistance: relative, frien-NA"
label variable m3i      "Assistance: Unsure training (CS)"
label variable m3j      "Assistance: CS other person-NA"
label variable m3k      "Assistance: other resp (uncod)"
label variable m3l      "Assistance: CS other       -NA"
label variable m3m      "Assistance: CS other       -NA"
label variable m3n      "Assistance: no one"
label variable m4       "Duration of breastfeeding"
label variable m5       "Months of breastfeeding"
label variable m6       "Duration of amenorrhea"
label variable m7       "Months of amenorrhea"
label variable m8       "Duration of abstinence"
label variable m9       "Months of abstinence"
label variable m10      "Time wanted pregnancy"
label variable m11      "Time would have waited"
label variable m13      "Timing of 1st antenatal check"
label variable m14      "Antenatal visits for pregnancy"
label variable m15      "Place of delivery"
label variable m17      "Delivery by caesarian section"
label variable m18      "Size of child at birth"
label variable m19      "Birth weight (kilos - 3 dec.)"
label variable m19a     "Weight at birth recall"
label variable m27      "Flag for breastfeeding"
label variable m28      "Flag for amenorrhea"
label variable m29      "Flag for abstinence"
label variable m34      "When child put to breast"
label variable m35      "Times breastfed during night"
label variable m36      "Times breastfed during day"
label variable m38      "Drank from bottle with nipple"
label variable m39      "Times ate solid, semi-solid or soft food yesterday"
label variable m42a     "During pregnancy - weighed"
label variable m42b     "During pregnancy - height m-NA"
label variable m42c     "During pregnancy - blood pressure taken"
label variable m42d     "During pregnancy - urine sample taken"
label variable m42e     "During pregnancy - blood sample taken"
label variable m43      "Told about pregnancy complications"
label variable m44      "Told where to go for pregnancy complications"
label variable m45      "During pregancy, given or bought iron tablets/syrup"
label variable m46      "Days tablets or syrup taken"
label variable m47      "During pregnancy, had difficulty with daylight vision"
label variable m48      "During pregnancy, had difficulty with night blindness"
label variable m49a     "During pregnancy - took Fansidar for Malaria"
label variable m49b     "During pregnancy - took Chloroquine for Malaria"
label variable m49c     "During pregnancy - took Unk-NA"
label variable m49d     "During pregnancy - took country specific drug for Malaria"
label variable m49e     "During pregnancy - took Del-NA"
label variable m49f     "During pregnancy - took cou-NA"
label variable m49g     "During pregnancy - took cou-NA"
label variable m49x     "During pregnancy - took other drug for Malaria"
label variable m49z     "During pregnancy - took no drug for Malaria"
label variable m51a     "Respondent checkup after deliver timing"
label variable m54      "Received Vitamin A dose in first 2 months after delivery"
label variable m55a     "First 3 days, given milk other than breast milk"
label variable m55b     "First 3 days, given plain water"
label variable m55c     "First 3 days, given sugar/glucose water"
label variable m55d     "First 3 days, given gripe water"
label variable m55e     "First 3 days, given sugar/salt/water solution"
label variable m55f     "First 3 days, given fruit juice"
label variable m55g     "First 3 days, given infant formula"
label variable m55h     "First 3 days, given tea/infusions"
label variable m55i     "First 3 days, given honey"
label variable m55j     "First 3 days, given country-NA"
label variable m55k     "First 3 days, given country-NA"
label variable m55l     "First 3 days, given country-NA"
label variable m55m     "First 3 days, given country-NA"
label variable m55n     "First 3 days, given country-NA"
label variable m55x     "First 3 days, given other"
label variable m55z     "First 3 days, given nothing"
label variable m57a     "Antenatal care: your home"
label variable m57b     "Antenatal care: other home"
label variable m57c     "Antenatal care: CS home    -NA"
label variable m57d     "Antenatal care: CS home    -NA"
label variable m57e     "Antenatal care: govt. hospital"
label variable m57f     "Antenatal care: govt. health center"
label variable m57g     "Antenatal care: govt. health post"
label variable m57h     "Antenatal care: public mobi-NA"
label variable m57i     "Antenatal care: CS public  -NA"
label variable m57j     "Antenatal care: CS public  -NA"
label variable m57k     "Antenatal care: CS public  -NA"
label variable m57l     "Antenatal care: other public"
label variable m57m     "Antenatal care: pvt. hospital/clinic"
label variable m57n     "Antenatal care: pvt. mobile-NA"
label variable m57o     "Antenatal care: Mission facility (CS)"
label variable m57p     "Antenatal care: CS pvt.    -NA"
label variable m57q     "Antenatal care: CS pvt.    -NA"
label variable m57r     "Antenatal care: other private"
label variable m57s     "Antenatal care: CS other   -NA"
label variable m57t     "Antenatal care: CS other   -NA"
label variable m57u     "Antenatal care: CS other   -NA"
label variable m57v     "Antenatal care: CS other   -NA"
label variable m57x     "Antenatal care: other"
label variable m60      "Drugs for intestinal parasi-NA"
label variable m61      "Time spent at place of delivery"
label variable m62      "Anyone checked respondent health before discharge"
label variable m63      "How long before discharging respondent health check took place"
label variable m64      "Who checked respondent health before discharge"
label variable m65a     "Reason didn't deliver at health facility: cost too much"
label variable m65b     "Reason didn't deliver at health facility: facility not open"
label variable m65c     "Reason didn't deliver at health facility: too far/no transport"
label variable m65d     "Reason didn't deliver at health facility: don't trust facility/poor service"
label variable m65e     "Reason didn't deliver at health facility: no female provider"
label variable m65f     "Reason didn't deliver at health facility: husband/family didn't allow"
label variable m65g     "Reason didn't deliver at health facility: not necessary"
label variable m65h     "Reason didn't deliver at health facility: not customary"
label variable m65i     "Reason didn't deliver at health facility: Could not get to facility in time/unex"
label variable m65j     "Reason didn't deliver at he-NA"
label variable m65k     "Reason didn't deliver at he-NA"
label variable m65l     "Reason didn't deliver at he-NA"
label variable m65x     "Reason didn't deliver at health facility: other"
label variable m66      "After discharge/delivery at home anyone checked respondent health"
label variable m67      "How long after discharge/delivery at home respondent health check took place"
label variable m68      "Who checked respondent health after discharge/delivery at home"
label variable m69      "Where respondent check after discharge/delivery at home took place"
label variable m70      "Baby postnatal check within 2 months"
label variable m71      "How long after delivery postnatal check took place"
label variable m72      "Who performed postnatal checkup"
label variable m73      "Where was the baby checked for the first time"
label variable hidx     "Index to birth history"
label variable h1       "Has health card"
label variable h2       "Received BCG"
label variable h2d      "BCG day"
label variable h2m      "BCG month"
label variable h2y      "BCG year"
label variable h3       "Received DPT 1"
label variable h3d      "DPT 1 day"
label variable h3m      "DPT 1 month"
label variable h3y      "DPT 1 year"
label variable h4       "Received POLIO 1"
label variable h4d      "POLIO 1 day"
label variable h4m      "POLIO 1 month"
label variable h4y      "POLIO 1 year"
label variable h5       "Received DPT 2"
label variable h5d      "DPT 2 day"
label variable h5m      "DPT 2 month"
label variable h5y      "DPT 2 year"
label variable h6       "Received POLIO 2"
label variable h6d      "POLIO 2 day"
label variable h6m      "POLIO 2 month"
label variable h6y      "POLIO 2 year"
label variable h7       "Received DPT 3"
label variable h7d      "DPT 3 day"
label variable h7m      "DPT 3 month"
label variable h7y      "DPT 3 year"
label variable h8       "Received POLIO 3"
label variable h8d      "POLIO 3 day"
label variable h8m      "POLIO 3 month"
label variable h8y      "POLIO 3 year"
label variable h9       "Received MEASLES"
label variable h9d      "MEASLES day"
label variable h9m      "MEASLES month"
label variable h9y      "MEASLES year"
label variable h0       "Received POLIO 0           -NA"
label variable h0d      "POLIO 0 day                -NA"
label variable h0m      "POLIO 0 month              -NA"
label variable h0y      "POLIO 0 year               -NA"
label variable h10      "Ever had vaccination"
label variable h11      "Had diarrhea recently"
label variable h11b     "Blood in the stools"
label variable h12a     "Diarrhea: government hosp."
label variable h12b     "Diarrhea: govt health center"
label variable h12c     "Diarrhea: govt health post -NA"
label variable h12d     "Diarrhea: mobile clinic    -NA"
label variable h12e     "Diarrhea: comm.health worker"
label variable h12f     "Diarrhea: Provincial hospital (CS)"
label variable h12g     "Diarrhea: District/rural hospital (CS)"
label variable h12h     "Diarrhea: Municipal clinic (CS)"
label variable h12i     "Diarrhea: other public sector"
label variable h12j     "Diarrhea: private hosp/clin."
label variable h12k     "Diarrhea: private pharmacy"
label variable h12l     "Diarrhea: private doctor"
label variable h12m     "Diarrhea: private mobile cl-NA"
label variable h12n     "Diarrhea: comm.health worke-NA"
label variable h12o     "Diarrhea: Mission facility (CS)"
label variable h12p     "Diarrhea: CS med.priv secto-NA"
label variable h12q     "Diarrhea: CS med.priv secto-NA"
label variable h12r     "Diarrhea: other med.priv sect."
label variable h12s     "Diarrhea: shop"
label variable h12t     "Diarrhea: traditional pract."
label variable h12u     "Diarrhea: CS oth.priv secto-NA"
label variable h12v     "Diarrhea: CS oth.priv secto-NA"
label variable h12w     "Diarrhea: CS oth.priv secto-NA"
label variable h12x     "Diarrhea: Other"
label variable h12y     "Diarrhea: no treatment"
label variable h12z     "Diarrhea: medical treatment"
label variable h13      "Given oral rehydration"
label variable h13b     "Given a pre-packaged ORS li-NA"
label variable h14      "Given recommend. home solution"
label variable h15      "Given antibiotic pills or syrups"
label variable h15a     "Given antimotility"
label variable h15b     "Given an antibiotic injection"
label variable h15c     "Given an intravenous (IV)"
label variable h15d     "Given home remedy, herbal med."
label variable h15e     "Given zinc                 -NA"
label variable h15f     "Given other (not antibiotic, antimotility, zinc)"
label variable h15g     "Given unknown pill or syrup"
label variable h15h     "Given not antibiotic injection"
label variable h15i     "Given unknown injection"
label variable h15j     "Given CS                   -NA"
label variable h15k     "Given CS                   -NA"
label variable h15l     "Given CS                   -NA"
label variable h15m     "Given CS                   -NA"
label variable h20      "Given other treatment"
label variable h21a     "Given no treatment"
label variable h21      "Received any treatment"
label variable h22      "Had fever in last two weeks"
label variable h31      "Had cough in last two weeks"
label variable h31b     "Short, rapid breaths"
label variable h31c     "Problem in the chest or blocked or running nose"
label variable h31d     "Had fever/cough in last 2 weeks: Amount offered to drink"
label variable h31e     "Had fever/cough in last 2 weeks: Amount offered to eat"
label variable h32a     "Fever/cough: government hosp."
label variable h32b     "Fever/cough: govt health cntr"
label variable h32c     "Fever/cough: govt health po-NA"
label variable h32d     "Fever/cough: mobile clinic -NA"
label variable h32e     "Fever/cough: comm.health wrkr"
label variable h32f     "Fever/cough: Provincial hospital (CS)"
label variable h32g     "Fever/cough: District/rural hospital (CS)"
label variable h32h     "Fever/cough: Municipal clinic (CS)"
label variable h32i     "Fever/cough: oth public sector"
label variable h32j     "Fever/cough: private hosp/clin"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor-NA"
label variable h32m     "Fever/cough: private mobile-NA"
label variable h32n     "Fever/cough: comm.health wr-NA"
label variable h32o     "Fever/cough: Mission facility (CS)"
label variable h32p     "Fever/cough: CS med.priv se-NA"
label variable h32q     "Fever/cough: CS med.priv se-NA"
label variable h32r     "Fever/cough: oth med.priv sect"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional pract"
label variable h32u     "Fever/cough: CS oth.priv se-NA"
label variable h32v     "Fever/cough: CS oth.priv se-NA"
label variable h32w     "Fever/cough: CS oth.priv se-NA"
label variable h32x     "Fever/cough: Other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable h33      "Received Vitamin A1 (most recent)"
label variable h33d     "Vitamin A1 Day"
label variable h33m     "Vitamin A1 month"
label variable h33y     "Vitamin A1 year"
label variable h34      "Vitamin A in last 6 months"
label variable h35      "Any vaccinations in last 2 years part of campaign"
label variable h36a     "Vaccinated during Campaign -NA"
label variable h36b     "Vaccinated during Campaign -NA"
label variable h36c     "Vaccinated during Campaign -NA"
label variable h36d     "Vaccinated during Campaign -NA"
label variable h36e     "Vaccinated during Campaign -NA"
label variable h36f     "Vaccinated during Campaign -NA"
label variable h37a     "Fansidar taken for fever/cough"
label variable h37b     "Chloroquine taken for fever/cough"
label variable h37c     "Amodiaquine taken for fever-NA"
label variable h37d     "Quinine taken for fever/cough"
label variable h37e     "Combination with artemisinin taken for fever/cough"
label variable h37f     "CS antimalarial taken for f-NA"
label variable h37g     "CS antimalarial taken for f-NA"
label variable h37h     "Other antimalarial taken for fever/cough"
label variable h37i     "Pills/syrup taken for fever-NA"
label variable h37j     "Injection taken for fever/c-NA"
label variable h37k     "Aspirin taken for fever/cough"
label variable h37l     "Acetaminophen taken for fever/cough"
label variable h37m     "Ibuprofen taken for fever/cough"
label variable h37n     "Cotramoxazole (CS) taken for fever/cough"
label variable h37o     "Erythromycine(CS) taken for fever/cough"
label variable h37p     "Amoxicillin(CS) taken for fever/cough"
label variable h37x     "Other taken for fever/convulsion"
label variable h37y     "Nothing taken for fever/convulsion"
label variable h37z     "Don't know if or what was taken for fever/convulsion"
label variable h38      "Had diarrhea in last 2 weeks: Amount offered to drink"
label variable h39      "Had diarrhea in last 2 weeks: Amount offered to eat"
label variable h40      "Received Vitamin A2 (2nd most recent)"
label variable h40d     "Vitamin A2 Day"
label variable h40m     "Vitamin A2 month"
label variable h40y     "Vitamin A2 year"
label variable h41a     "Received vitamin A after mo-NA"
label variable h41b     "Ever received Vitamin A dose"
label variable h42      "Taking iron pills, sprinkle-NA"
label variable h43      "Drugs for intestinal parasi-NA"
label variable h44a     "Place first sought treatment dor diarrhea"
label variable h44b     "Days after diarrhea sought advice or treatment"
label variable h44c     "Still has diarrhea"
label variable h45      "Times zinc was given       -NA"
label variable h46a     "Place first sought treatment for fever"
label variable h46b     "Days after fever sought advice or treatment"
label variable hwidx    "Index to birth history"
label variable hw1      "Age in months"
label variable hw2      "Weight in kilograms (1 dec.)"
label variable hw3      "Height in centimeters (1 dec.)"
label variable hw4      "Ht/A Percentile"
label variable hw5      "Ht/A Standard deviations"
label variable hw6      "Ht/A Percent of ref. median"
label variable hw7      "Wt/A Percentile"
label variable hw8      "Wt/A Standard deviations"
label variable hw9      "Wt/A Percent of ref. median"
label variable hw10     "Wt/Ht Percentile"
label variable hw11     "Wt/Ht Standard deviations"
label variable hw12     "Wt/Ht Percent of ref. median"
label variable hw13     "Reason not measured"
label variable hw15     "Height: lying or standing"
label variable hw16     "Day of birth of child"
label variable hw17     "Date measured (day)"
label variable hw18     "Date measured (month)"
label variable hw19     "Date measured (year)"
label variable hw51     "Line no. of parent/caretaker"
label variable hw52     "Read consent statement"
label variable hw53     "Hemoglobin level (g/dl - 1 decimal)"
label variable hw55     "Result of measuring (Hemoglobin)"
label variable hw56     "Hemoglobin level adjusted by altitude(g/dl - 1 decimal)"
label variable hw57     "Anemia level"
label variable hw58     "Agrees to referral         -NA"
label variable hw70     "Ht/A Standard deviations (according to WHO)"
label variable hw71     "Wt/A Standard deviations (according to WHO)"
label variable hw72     "Wt/Ht Standard deviations (according to WHO)"
label variable hw73     "BMI Standard deviations (according to WHO)"
label variable idxml    "Index to birth history"
label variable ml0      "Type of bednet(s) child slept under last night"
label variable ml1      "Times took Fansidar during pregnancy"
label variable ml2      "Type of visit at source for antimalarial during pregnancy"
label variable ml11     "Child has fever now"
label variable ml12     "Child has had convulsions i-NA"
label variable ml13a    "Fansidar taken for fever/cough"
label variable ml13b    "Chloroquine taken for fever/cough"
label variable ml13c    "Amodiaquine taken for fever-NA"
label variable ml13d    "Quinine taken for fever/cough"
label variable ml13e    "Combination with artemisinin taken for fever/cough"
label variable ml13f    "CS antimalarial taken for f-NA"
label variable ml13g    "CS antimalarial taken for f-NA"
label variable ml13h    "Other antimalarial taken for fever/cough"
label variable ml13i    "Pills/syrup taken for fever-NA"
label variable ml13j    "Injection taken for fever/c-NA"
label variable ml13k    "Aspirin taken for fever/cough"
label variable ml13l    "Acetaminophen taken for fever/cough"
label variable ml13m    "Ibuprofen taken for fever/cough"
label variable ml13n    "Cotramoxazole (CS) taken for fever/cough"
label variable ml13o    "Erythromycine(CS) taken for fever/cough"
label variable ml13p    "Amoxicillin(CS) taken for fever/cough"
label variable ml13x    "Other taken for fever/convulsion"
label variable ml13y    "Nothing taken for fever/convulsion"
label variable ml13z    "Don't know if or what was taken for fever/convulsion"
label variable ml14a    "Injection for fever/convuls-NA"
label variable ml14b    "Suppository for fever/convu-NA"
label variable ml14y    "No suppository or injection-NA"
label variable ml14z    "Don't know if suppository o-NA"
label variable ml15a    "When started Fansidar"
label variable ml15b    "Days child took Fansidar"
label variable ml15c    "First source for Fansidar"
label variable ml16a    "When started Chloroquine"
label variable ml16b    "Days child took Chloroquine"
label variable ml16c    "First source for Chloroquine"
label variable ml17a    "When started Amodiaquine   -NA"
label variable ml17b    "Days child took Amodiaquine-NA"
label variable ml17c    "First source for Amodiaquin-NA"
label variable ml18a    "When started Quinine       -NA"
label variable ml18b    "Days child took Quinine    -NA"
label variable ml18c    "First source for Quinine"
label variable ml19a    "For fever/conv: Consulted traditional healer"
label variable ml19b    "For fever/conv: Gave tepid sponging"
label variable ml19c    "For fever/conv: Gave herbs"
label variable ml19d    "For fever/conv: CS         -NA"
label variable ml19e    "For fever/conv: CS         -NA"
label variable ml19f    "For fever/conv: CS         -NA"
label variable ml19x    "For fever/conv: Other"
label variable ml19y    "For fever/conv: Gave nothing"
label variable ml19z    "For fever/conv: Don't know if something else was done"
label variable ml20a    "When started combination wi-NA"
label variable ml20b    "Days child took combination-NA"
label variable ml20c    "First source for combinatio-NA"
label variable ml21a    "When started CS antimalaria-NA"
label variable ml21b    "Days child took CS antimala-NA"
label variable ml21c    "First source for CS antimal-NA"
label variable ml22a    "When started CS antimalaria-NA"
label variable ml22b    "Days child took CS antimala-NA"
label variable ml22c    "First source for CS antimal-NA"
label variable ml23a    "When started other anti-mal-NA"
label variable ml23b    "Days child took other anti--NA"
label variable ml23c    "First source for other anti-NA"
label variable ml24c    "First source for antibiotic-NA"
label variable slangq   "Language of questionnaire"
label variable slangint "Language of interview"
label variable sinterp  "Translator used"
label variable s119     "How often attended religious services in last month"
label variable s240     "Primary care giver"
label variable s241     "Care-giver of children under 18"
label variable s242     "Made care arrangements for children under 18"
label variable s336     "Male condom protects against pregnancy if used correctly"
label variable s338     "Female condom protects against pregnancy if used correctly"
label variable s630a    "Main reason used condom last intercourse"
label variable s630b    "Main reason used condom last intercourse"
label variable s630c    "Main reason used condom last intercourse"
label variable s643     "Brand condom used last time had sex"
label variable s644     "Number condoms got at that time"
label variable s645     "Cost of condoms"
label variable s646     "Source of condom for last sex"
label variable s649o    "Source for condoms: General Dealer"
label variable s649p    "Source for condoms: Supermarket"
label variable s649q    "Source for condoms: Tuck shop"
label variable s653o    "Source for condoms: General Dealer"
label variable s653p    "Source for female condoms: Supermarket"
label variable s653q    "Source for female condoms: Tuck shop"
label variable s723     "Husband STD, wife ask him to use condom"
label variable s909a    "Means of avoiding AIDS : Abstain from sex"
label variable s909b    "Means of avoiding AIDS : Use condoms"
label variable s909c    "Means of avoiding AIDS : Limit sex to 1 partner"
label variable s909d    "Means of avoiding AIDS : Limit number of partner"
label variable s909e    "Means of avoiding AIDS : Avoid prostitutes"
label variable s909f    "Means of avoiding AIDS : Avoid sex w/person with more than 1 partner"
label variable s909g    "Means of avoiding AIDS : Avoid sex with homosexuals"
label variable s909h    "Means of avoiding AIDS : Avoid sex with intravenous drug users"
label variable s909i    "Means of avoiding AIDS : Avoid blood transfusions"
label variable s909j    "Means of avoiding AIDS : Avoid injections"
label variable s909k    "Means of avoiding AIDS : Avoid sharing razors"
label variable s909l    "Means of avoiding AIDS : Avoid kissing"
label variable s909m    "Means of avoiding AIDS : Avoid mosquito bites"
label variable s909n    "Means of avoiding AIDS : Seek protection of traditional healer"
label variable s909w    "Means of avoiding AIDS : Other"
label variable s909x    "Means of avoiding AIDS : Other"
label variable s909z    "Means of avoiding AIDS : Don't know"
label variable s910     "Risk of getting AIDS"
label variable s920     "Asked for test"
label variable s932     "Tell husband/partner result of test"
label variable s933     "Main reason have not been tested for HIV"
label variable s937     "Husband/partner ever have HIV test"
label variable s938     "Husband tell you results of his HIV test"
label variable s942a    "Male teacher with AIDS virus allowed to continue teaching"
label variable s950     "Agree that 1 married partner can be HIV+ and not infect the other"
label variable s1012    "Male condom used correctly protect from diseases most of time"
label variable s1014    "Female condom used correctly protect from diseases"
label variable s1016    "Medical aid"
label variable s1017    "Type of medical aid"
label variable s1106hn  "How many times during the last 12 months"
label variable s1109    "Time abuse happened before marriage"
label variable s1112    "Husband/partner drunk how often abuse"
label variable s1113d   "Ever late or unable to go to work"
label variable s1114a   "Humiliate him in front of others"
label variable s1114an  "How may times during the last 12 months"
label variable s1114b   "Threaten to hurt or harm him or someone close to him"
label variable s1114bn  "How many times during the last 12 months"
label variable s1114c   "Insult him or make him feel bad about himself"
label variable s1114cn  "How many times during the last 12 months"
label variable s1114d   "Hit, slapped, kicked, or done anything else to physically hurt him"
label variable s1114dn  "How many times during the last 12 months"
label variable s1116    "Any of these things to husand/partner last 12 months"
label variable s1117a   "Ever physically hurt by someone"
label variable s1117b   "Ever emotionally hurt by someone"
label variable s1118a   "Ever emotionally hurt by:Mother / step-mother (where S1117A <> 1)"
label variable s1118b   "Ever emotionally hurt by:Father / step-father (where S1117A <> 1)"
label variable s1118c   "Ever emotionally hurt by:Sister / brother (where S1117A <> 1)"
label variable s1118d   "Ever emotionally hurt by:Daughter / son (where S1117A <> 1)"
label variable s1118e   "Ever emotionally hurt by:Other relative (where S1117A <> 1)"
label variable s1118f   "Ever emotionally hurt by:Former husband / partner (where S1117A <> 1)"
label variable s1118g   "Ever emotionally hurt by:Current boyfriend (where S1117A <> 1)"
label variable s1118h   "Ever emotionally hurt by:Former boyfriend (where S1117A <> 1)"
label variable s1118i   "Ever emotionally hurt by:Mother-in-law (where S1117A <> 1)"
label variable s1118j   "Ever emotionally hurt by:Father-in-law (where S1117A <> 1)"
label variable s1118k   "Ever emotionally hurt by:Other in-law (where S1117A <> 1)"
label variable s1118l   "Ever emotionally hurt by:Teacher (where S1117A <> 1)"
label variable s1118m   "Ever emotionally hurt by:Employer / someone at work (where S1117A <> 1)"
label variable s1118n   "Ever emotionally hurt by:Police / soldier (where S1117A <> 1)"
label variable s1118o   "Ever emotionally hurt by:Neighbour (where S1117A <> 1)"
label variable s1118p   "Ever emotionally hurt by:Friend (where S1117A <> 1)"
label variable s1118x   "Ever emotionally hurt by:Other (where S1117A <> 1)"
label variable s1134    "Main reason did not seek help"
label variable idx94    "Index to birth history"
label variable s436     "Time after labour pains began that arrived at health facility"
label variable s437     "Time at health facility before seen by health professional"
label variable s439     "Time spent at place of delivery"
label variable s449     "Health child checked in first 2 months after birth"
label variable idx95    "Index to birth history"
label variable s508p4   "Received POLIO 4"
label variable sd58p4   "POLIO 4 day"
label variable sm58p4   "POLIO 4 month"
label variable sy58p4   "POLIO 4 year"
label variable s508p5   "Received POLIO 5"
label variable sd58p5   "POLIO 5 day                -NA"
label variable sm58p5   "POLIO 5 month              -NA"
label variable sy58p5   "POLIO 5 year               -NA"
label variable s508d4   "Received DPT4"
label variable sd58d4   "DPT 4 day"
label variable sm58d4   "DPT 4 month"
label variable sy58d4   "DPT 4 year"
label variable s508h2   "Received Hepatitis 2"
label variable sd58h2   "Hepatitis 2 day"
label variable sm58h2   "Hepatitis 2 month"
label variable sy58h2   "Hepatitis 2 year"
label variable s508h3   "Received Hepatitis 3"
label variable sd58h3   "Hepatitis 3 day"
label variable sm58h3   "Hepatitis 3 month"
label variable sy58h3   "Hepatitis 3 year"
label variable s508h1   "Received Hepatitis 1"
label variable sd58h1   "Hepatitis 1 day"
label variable sm58h1   "Hepatitis 1 month"
label variable sy58h1   "Hepatitis 1 year"
label variable s508m2   "Received Measles 2"
label variable sd58m2   "Measles 2 day"
label variable sm58m2   "Measles 2 month"
label variable sy58m2   "Measles 2 year"
label variable s508pa   "Received Penultimate Vitamin A"
label variable sd58pa   "Penultimate Vitamin A day"
label variable sm58pa   "Penultimate Vitamin A month"
label variable sy58pa   "Penultimate Vitamin A year"
label variable s558a    "Received injection for fever/cough/rapid breathing"
label variable s558b    "Received suppository for fever/cough/rapid breathing"
label variable s549i    "Ampicillin (antibiotic) taken for fever/cough"
label variable s549j    "Chloramphenocol (antibiotic) taken for fever/cough"
label variable s549k    "Other antibiotic taken for fever/cough"
label variable s532c    "Other liquid given to treat diarrhea"

#delimit ;
label define V013    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V023    
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define V024    
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V028    
   999 "Missing"
;
label define V029    
    99 "Missing"
;
label define V030    
   999 "Missing"
;
label define V031    
   999 "Missing"
;
label define V032    
    99 "Missing"
;
label define V034    
     0 "Husband not in HH"
;
label define V042    
     0 "Not selected"
     1 "Selected"
;
label define V044    
     0 "Woman not selected"
     1 "Woman selected and interviewed"
     2 "Woman selected, but privacy not possible"
     3 "Woman selected, but not interviewed"
;
label define V101    
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V103    
     9 "Missing"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define V107    
    99 "Missing"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into tap in yard/plot"
    13 "Public tap"
    20 "OPEN WELL WATER"
    21 "Tube well or borehole"
    30 "COVERED WELL/BOREHOLE"
    31 "Protected dug well"
    32 "Unprotected dug well"
    40 "SURFACE WATER"
    41 "Protected spring"
    42 "Unprotected spring"
    51 "Rainwater"
    61 "Tanker truck"
    71 "Cart with small tank"
    81 "Surface water(river/dam/lake/pond/stream/canal/irrigation channel"
    91 "Bottled water"
    96 "Other"
    97 "Not dejure resident"
;
label define V115    
   996 "On premises"
   997 "Not dejure resident"
   998 "Don't know ***"
;
label define V116    
    10 "FLUSH TOILET"
    11 "Flushed to piped sewer system"
    12 "Flush to septic tank"
    13 "Flush to latrine"
    14 "Flush other"
    15 "Flush, don't know where"
    20 "PIT TOILET LATRINE"
    21 "Ventilated improved pit/latrine (VIP Blair toilet)"
    22 "Non-VIP pit latrine with slab"
    23 "Non-VIP pit latrine without slab"
    30 "NO FACILITY"
    31 "No facility/bush/field"
    90 "OTHER"
    91 "Composting toilet/Arbo loo"
    92 "Bucket toilet"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V119    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V120    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V121    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V122    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V123    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V124    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V125    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V127    
    10 "NATURAL"
    11 "Earth, sand/dung"
    20 "RUDIMENTARY"
    21 "Rudimentary wood planks"
    30 "FINISHED"
    31 "Parquet, polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V128    
    10 "NATURAL"
    11 "Cane/trunks"
    12 "Mud"
    20 "RUDIMENTARY"
    22 "Stone with mud"
    23 "Plywood"
    24 "Carton"
    25 "Reused wood"
    30 "FINISHED"
    31 "Cement"
    32 "Stone with lime/cement"
    33 "Bricks"
    34 "Cement blocks"
    35 "Wood planks"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V129    
    10 "NATURAL"
    11 "No roof"
    12 "Thatch"
    20 "RUDIMENTARY"
    21 "Rustic mat"
    23 "Wood planks"
    30 "FINISHED"
    31 "Metal"
    32 "Wood"
    33 "Asbestos"
    34 "Tiles"
    35 "Cement"
    96 "OTHER"
    97 "Not dejure resident"
;
label define V130    
     1 "Traditional"
     2 "Roman Catholic"
     3 "Protestant"
     4 "Pentecostal"
     5 "Apostolic Sect"
     6 "Other Christian"
     7 "Muslim"
     8 "None"
    96 "Other"
;
label define V131    
    99 "Missing"
;
label define V133    
    97 "Inconsistent"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
;
label define V139    
     0 "Abroad"
     1 "Manicaland"
     2 "Mashonaland Central"
     3 "Mashonaland East"
     4 "Mashonaland West"
     5 "Matebeleland North"
     6 "Matebeleland South"
     7 "Midlands"
     8 "Masvingo"
     9 "Harare"
    10 "Bulawayo"
    97 "Not dejure resident"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     7 "Not dejure resident"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     7 "Not dejure resident"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Grand-daughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    13 "Niece/nehew by blood"
    14 "Niece/nephew by marriage"
    98 "DK"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    97 "97+"
    98 "DK"
;
label define V153    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V155    
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define V156    
     0 "No"
     1 "Yes"
;
label define V157    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V158    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V159    
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define V160    
     0 "No"
     1 "Yes"
     7 "Not dejure resident"
;
label define V161    
     1 "Electricity"
     2 "Liquid propane gas"
     3 "Natural gas"
     4 "Biogas"
     5 "Paraffin/Kerosine"
     6 "Coal, lignite"
     7 "Charcoal"
     8 "Wood"
     9 "Straw/shrubs/grass"
    10 "Maize or other crop waste"
    11 "Animal dung"
    96 "Other"
    97 "Not dejure resident"
;
label define V167    
     0 "None"
;
label define V168    
     0 "No"
     1 "Yes"
;
label define V190    
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define ML101   
     0 "No bednet"
     1 "Only treated bednets"
     2 "Both treated and untreated bednets"
     3 "Only untreated bednets"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V217    
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
;
label define V227    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + amen. > interval"
     3 "N, but per. not ret."
     4 "95, but no birth"
     5 "95, but per.returned"
     6 "96, but per.returned"
     7 "N, last per. in preg"
     8 "96, had children"
     9 "N, per.bef.last birt"
;
label define V228    
     0 "No"
     1 "Yes"
;
label define V229    
    97 "Inconsistent"
    98 "DK"
;
label define V230    
  9997 "Inconsistent"
  9998 "DK"
;
label define V231    
  9997 "Inconsistent"
  9998 "DK"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
;
label define V234    
     0 "No"
     1 "Yes"
;
label define V235    
     0 "No prior child"
;
label define V237    
     0 "No"
     1 "Yes"
;
label define V239    
     0 "No"
     1 "Yes"
;
label define V240    
    97 "Inconsistent"
    98 "Don't know"
;
label define V241    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V242    
  9997 "Inconsistent"
  9998 "Don't know"
;
label define V243    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V310    
    99 "Missing"
;
label define V311    
     4 "4+"
     5 "Never used"
;
label define V312    
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
;
label define V313    
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
;
label define V318    
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
     9 "From calendar"
;
label define V319    
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
;
label define V320    
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45-49"
;
label define V321    
     0 "Single, before marriage"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define V322    
     5 "5+"
;
label define V323    
     1 "Ovrette"
     2 "Lo-Femenal"
     3 "Micronor"
     4 "Micronovum"
     5 "Marvellon"
     6 "Duofem"
     7 "Excluton"
    96 "Other"
    98 "Don't know"
;
label define V323A   
     1 "Choice assorted"
     2 "Durex"
     3 "Ecstasy"
     4 "Protecta"
     5 "Public sector dist."
     6 "Rough rider"
     7 "Other male condom"
     8 "Male condom, don't know"
     9 "Care"
    10 "Other female condom"
    12 "Female condom, don't know"
    98 "Don't know"
;
label define V325A   
9999995 "Free"
9999998 "Don't know"
;
label define V326    
    10 "PUBLIC"
    11 "Central hospital"
    12 "Provincial hospital"
    13 "District/rural hospital"
    14 "ZNFPC clinic"
    16 "MOH Mobile clinic"
    17 "ZNFPC CBD/Depot holder"
    18 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private Hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "CBD"
    25 "Mission facility"
    26 "Other private medical"
    30 "OTHER PRIVATE"
    31 "Church"
    32 "Friend/relative"
    33 "General dealer"
    34 "Supermarket"
    35 "Tuck shop"
    36 "Service station"
    37 "Other retail"
    96 "OTHER"
    98 "DK"
;
label define V327    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
;
label define V337    
    95 "All cal. {A core}"
    96 "96+ {B core}"
   997 "Inconsistent"
   998 "Don't know"
;
label define V359    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
;
label define V360    
     1 "Became pregnant"
     2 "Wanted to become prg"
     3 "Husband disapproved"
     4 "Side effects"
     5 "Health concerns"
     6 "Access, availability"
     7 "Wanted more eff.meth"
     8 "Inconvenient to use"
     9 "Infreq.sex,husb away"
    10 "Cost"
    11 "Fatalistic"
    12 "Diff.preg.,menopause"
    13 "Marital dissolution"
    14 "Other"
    98 "Don't know"
;
label define V361    
     1 "Currently using"
     2 "Used since last birth"
     3 "Used before last birth"
     4 "Never used"
;
label define V362    
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
;
label define V363    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Specific method 1"
    18 "Specific method 2"
    19 "Specific method 3"
    20 "Specific method 4"
    98 "Don't know"
;
label define V364    
     1 "Using modern method"
     2 "Using traditional method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define V367    
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
;
label define V372    
     0 "Package not seen"
     1 "Package seen"
;
label define V372A   
     9 "Missing"
;
label define V375A   
    99 "Missing"
;
label define V376    
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
;
label define V376A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V379    
    99 "Missing"
;
label define V380    
     9 "Missing"
;
label define V384A   
     0 "No"
     1 "Yes"
;
label define V384B   
     0 "No"
     1 "Yes"
;
label define V384C   
     0 "No"
     1 "Yes"
;
label define V393    
     0 "No"
     1 "Yes"
;
label define V394    
     0 "No"
     1 "Yes"
;
label define V395    
     0 "No"
     1 "Yes"
;
label define V3A00A  
     0 "No"
     1 "Government hospital"
;
label define V3A00B  
     0 "No"
     1 "Govt. health center"
;
label define V3A00C  
     0 "No"
     1 "Govt. health post"
;
label define V3A00D  
     0 "No"
     1 "Public mobile clinic"
;
label define V3A00E  
     9 "Missing"
;
label define V3A00F  
     0 "No"
     1 "Rural health centre(CS)"
;
label define V3A00G  
     0 "No"
     1 "ZNFPC CBD/Depot holder(CS)"
;
label define V3A00H  
     9 "Missing"
;
label define V3A00I  
     0 "No"
     1 "Other public sector"
;
label define V3A00J  
     0 "No"
     1 "Private hosp./clinic"
;
label define V3A00K  
     0 "No"
     1 "Private pharmacy"
;
label define V3A00L  
     0 "No"
     1 "Private doctor"
;
label define V3A00M  
     9 "Missing"
;
label define V3A00N  
     9 "Missing"
;
label define V3A00O  
     0 "No"
     1 "Community Based Distribution (CBD) (CS)"
;
label define V3A00P  
     0 "No"
     1 "Yes"
;
label define V3A00Q  
     9 "Missing"
;
label define V3A00R  
     0 "No"
     1 "Oth med. priv. sect."
;
label define V3A00S  
     0 "No"
     1 "Shop"
;
label define V3A00T  
     0 "No"
     1 "Traditional pract."
;
label define V3A00U  
     0 "No"
     1 "CS oth. priv. sector"
;
label define V3A00V  
     0 "No"
     1 "Service Station (CS)"
;
label define V3A00W  
     0 "No"
     1 "Other retail (CS)"
;
label define V3A00X  
     0 "No"
     1 "Other"
;
label define V3A00Y  
     0 "No: knows a source"
     1 "Yes: knows no source"
;
label define V3A00Z  
     0 "No"
     1 "Yes: knows some source"
;
label define V3A01   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V3A02   
     0 "No"
     1 "Yes"
;
label define V3A03   
     9 "Missing"
;
label define V3A04   
     0 "No"
     1 "Yes"
;
label define V3A05   
     0 "No"
     1 "Yes"
;
label define V3A06   
     0 "No"
     1 "Yes"
;
label define V3A07   
    10 "PUBLIC"
    11 "Government hospital/clinic"
    12 "Rural/Municipal clinic"
    13 "Rural Health centre"
    14 "ZNFPC clinic"
    16 "MOH Mobile clinic"
    17 "ZNFPC CBD/Depot holder"
    18 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private Hospital/clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "CBD"
    25 "Mission facility"
    26 "Other private medical"
    30 "OTHER PRIVATE"
    31 "Church"
    32 "Friend/relative"
    33 "General dealer"
    34 "Supermarket"
    35 "Tuck shop"
    36 "Service station"
    37 "Other retail"
    96 "OTHER"
    98 "DK"
;
label define V3A08A  
     0 "No"
     1 "Not married"
;
label define V3A08B  
     0 "No"
     1 "Not having sex"
;
label define V3A08C  
     0 "No"
     1 "Infrequent sex"
;
label define V3A08D  
     0 "No"
     1 "Menopausal/hysterectomy"
;
label define V3A08E  
     0 "No"
     1 "Subfecund/infecund"
;
label define V3A08F  
     0 "No"
     1 "Postpartum amenorrheic"
;
label define V3A08G  
     0 "No"
     1 "Breastfeeding"
;
label define V3A08H  
     0 "No"
     1 "Fatalistic"
;
label define V3A08I  
     0 "No"
     1 "Respondent opposed"
;
label define V3A08J  
     0 "No"
     1 "Husband/partner opposed"
;
label define V3A08K  
     0 "No"
     1 "Others opposed"
;
label define V3A08L  
     0 "No"
     1 "Religious prohibition"
;
label define V3A08M  
     0 "No"
     1 "Knows no method"
;
label define V3A08N  
     0 "No"
     1 "Knows no source"
;
label define V3A08O  
     0 "No"
     1 "Health concerns"
;
label define V3A08P  
     0 "No"
     1 "Fear of side effects"
;
label define V3A08Q  
     0 "No"
     1 "Lack of access/too far"
;
label define V3A08R  
     0 "No"
     1 "Costs too much"
;
label define V3A08S  
     0 "No"
     1 "Inconvenient to use"
;
label define V3A08T  
     0 "No"
     1 "Interferes with bodys processes"
;
label define V3A08U  
     9 "Missing"
;
label define V3A08V  
     9 "Missing"
;
label define V3A08W  
     9 "Missing"
;
label define V3A08X  
     0 "No"
     1 "Other"
;
label define V3A08Z  
     0 "No"
     1 "Don't know"
;
label define V3A09A  
   998 "Don't know"
;
label define V3A09B  
   999 "Missing"
;
label define V401    
     0 "No"
     1 "Yes"
;
label define V404    
     0 "No"
     1 "Yes"
;
label define V405    
     0 "No"
     1 "Yes"
;
label define V406    
     0 "No"
     1 "Yes"
;
label define V407    
    96 "On demand"
;
label define V408    
    96 "On demand"
;
label define V409    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V409A   
     9 "Missing"
;
label define V410    
     9 "Missing"
;
label define V410A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V411    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V411A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V412    
     9 "Missing"
;
label define V412A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V412B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V413B   
     9 "Missing"
;
label define V413C   
     9 "Missing"
;
label define V413D   
     9 "Missing"
;
label define V414A   
     9 "Missing"
;
label define V414B   
     9 "Missing"
;
label define V414C   
     9 "Missing"
;
label define V414D   
     9 "Missing"
;
label define V414E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414H   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414I   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414J   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414K   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414L   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414M   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414N   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414O   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414P   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414Q   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414R   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414S   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414T   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V414U   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V415    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V416    
     9 "Missing"
;
label define V420    
   999 "Missing"
;
label define V421    
   999 "Missing"
;
label define V426    
     0 "Immediately"
;
label define V437    
  9999 "Missing"
;
label define V438    
  9999 "Missing"
;
label define V439    
  9998 "Flagged cases"
;
label define V440    
  9998 "Flagged cases"
;
label define V441    
 99998 "Flagged cases"
;
label define V442    
 99998 "Flagged cases"
;
label define V443    
 99998 "Flagged cases"
;
label define V444    
 99998 "Flagged cases"
;
label define V444A   
  9998 "Flagged cases"
;
label define V445    
  9998 "Flagged cases"
;
label define V446    
  9998 "Flagged cases"
;
label define V447    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in HH"
;
label define V452A   
     1 "Under age 18"
     2 "Age 18 or older"
;
label define V452B   
     0 "Not in household"
;
label define V452C   
     1 "Granted"
     2 "Parent/other refused"
     3 "Respondent refused"
     4 "No adult present***"
;
label define V453    
   999 "Missing"
;
label define V454    
     0 "No/don't know"
     1 "Yes"
;
label define V455    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     5 "Technical problem **"
     6 "Other"
     7 "No measurement found in HH"
;
label define V456    
   999 "Missing"
;
label define V457    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define V458    
     9 "Missing"
;
label define V459    
     0 "No"
     1 "Yes"
;
label define V460    
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define V461    
     0 "No"
     1 "Yes"
;
label define V462    
     9 "Missing"
;
label define V463A   
     0 "No"
     1 "Yes"
;
label define V463B   
     0 "No"
     1 "Yes"
;
label define V463C   
     0 "No"
     1 "Yes"
;
label define V463D   
     0 "No"
     1 "Yes"
;
label define V463E   
     9 "Missing"
;
label define V463F   
     9 "Missing"
;
label define V463G   
     9 "Missing"
;
label define V463X   
     0 "No"
     1 "Yes, smokes nothing"
;
label define V463Z   
     0 "No"
     1 "Yes, smokes nothing"
;
label define V464    
    99 "Missing"
;
label define V465    
     1 "Always use toilet/latrine"
     2 "Put/rinsed in toilet/latrine"
     3 "Put/rinsed into drain or ditch"
     4 "Throw into garbage"
     5 "Buried"
     6 "Rinse away"
     7 "Use disposable diapers"
     8 "Use washable diapers"
     9 "Left in the open/not disposed of"
    96 "Other"
    98 "Don't know ***"
;
label define V466    
     9 "Missing"
;
label define V467A   
     9 "Missing"
;
label define V467B   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467C   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467D   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467E   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467F   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467G   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467H   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467I   
     0 "No problem"
     1 "Big problem"
     2 "Not a big problem"
;
label define V467J   
     9 "Missing"
;
label define V467K   
     9 "Missing"
;
label define V467L   
     9 "Missing"
;
label define V467M   
     9 "Missing"
;
label define V468    
     0 "See specific questions"
     1 "Only last birth"
     2 "All columns"
;
label define V471A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V471F   
     9 "Missing"
;
label define V471G   
     9 "Missing"
;
label define V472A   
     9 "Missing"
;
label define V472B   
     9 "Missing"
;
label define V472C   
     9 "Missing"
;
label define V472D   
     9 "Missing"
;
label define V472E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472F   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472G   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472H   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472I   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472J   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472K   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472L   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472M   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472N   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472O   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472P   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472Q   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472R   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472S   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472T   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V472U   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V473A   
     1 "Granted"
     2 "Parent/Other responsible refused"
     3 "Respondent refused"
     4 "No adult present"
;
label define V473B   
     1 "Blood taken"
     2 "Not present"
     3 "Refused"
     4 "Technical problem ***"
     5 "Sample not found in the lab data ***"
     6 "Other"
     7 "Specimen collected but could not be tested ***"
;
label define V474    
     0 "No"
     1 "Yes"
;
label define V474A   
     0 "No"
     1 "Yes"
;
label define V474B   
     0 "No"
     1 "Yes"
;
label define V474C   
     0 "No"
     1 "Yes"
;
label define V474D   
     0 "No"
     1 "Yes"
;
label define V474E   
     0 "No"
     1 "Yes"
;
label define V474F   
     0 "No"
     1 "Yes"
;
label define V474G   
     9 "Missing"
;
label define V474H   
     9 "Missing"
;
label define V474I   
     9 "Missing"
;
label define V474J   
     9 "Missing"
;
label define V474X   
     0 "No"
     1 "Yes"
;
label define V474Z   
     0 "No"
     1 "Yes"
;
label define V475    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V476    
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know / not sure / depends"
;
label define V477    
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define V478    
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define V479    
    10 "PUBLIC SECTOR"
    11 "Central hospital"
    12 "Provincial hospital"
    13 "District/rural hospital"
    14 "Rural health centre"
    15 "Municipal clinic"
    16 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private hospital/clinic"
    22 "New start centre"
    23 "Private VCT centre"
    24 "Private doctor"
    25 "Mission facility"
    26 "Other private medical"
    30 "OTHERS NON-MEDICAL"
    96 "Other"
;
label define V480    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V481    
     0 "No"
     1 "Yes"
;
label define V481A   
     9 "Missing"
;
label define V481B   
     0 "No"
     1 "Yes"
;
label define V481C   
     9 "Missing"
;
label define V481D   
     0 "No"
     1 "Yes"
;
label define V481E   
     9 "Missing"
;
label define V481F   
     0 "No"
     1 "Yes"
;
label define V481G   
     0 "No"
     1 "Yes"
;
label define V481H   
     9 "Missing"
;
label define V481X   
     0 "No"
     1 "Yes"
;
label define V482A   
     9 "Missing"
;
label define V482B   
     9 "Missing"
;
label define V482C   
     9 "Missing"
;
label define V501    
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
;
label define V502    
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
;
label define V503    
     1 "Once"
     2 "More than once"
;
label define V504    
     1 "Living with her"
     2 "Staying elsewhere"
;
label define V505    
     0 "No other wives"
    98 "Don't know"
;
label define V506    
    98 "Don't know"
;
label define V510    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V513    
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define V525    
     0 "Not had intercourse"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define V527    
   100 "<1 day ago"
   101 "Days: 1"
   201 "Weeks: 1"
   301 "Months: 1"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V528    
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define V529    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define V530    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + abst. > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but curr.preg."
     6 "96, but resumed sex"
     7 "N, last sex bef preg"
     8 "N, inconsis 4 weeks"
     9 "N, sex bef last birt"
;
label define V531    
     0 "Not had intercourse"
    97 "Inconsistent"
    98 "Don't know"
;
label define V532    
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define V535    
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
;
label define V536    
     0 "Never had intercourse"
     1 "Active in last 4 weeks"
     2 "Not active in last 4 weeks - postpartum abst."
     3 "Not active in last 4 weeks - not postpartum abst."
;
label define V537    
    60 "60+"
    96 "Before last birth"
    97 "Inconsistent"
    98 "DK"
;
label define V538    
     1 "Death / widowhood"
     2 "Divorce"
     3 "Separation"
;
label define V539    
     1 "Respondent"
     2 "Other wife"
     3 "Spouse's children"
     4 "Spouse's family"
     6 "Other"
     7 "No property"
;
label define V540    
     0 "No"
     1 "Yes"
;
label define V541    
     0 "No"
     1 "Yes"
     8 "Don't know / unsure"
;
label define V602    
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Declared infecund"
     6 "Never had sex"
;
label define V603    
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define V604    
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define V605    
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
;
label define V613    
    96 "Non-numeric response"
    98 "DK"
;
label define V614    
     6 "6+"
     7 "Non-numeric response"
;
label define V616    
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
;
label define V621    
     1 "Both want same"
     2 "Husband wants more"
     3 "Husband wants fewer"
     8 "DK"
;
label define V623    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
;
label define V624    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
;
label define V625    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
;
label define V626    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
;
label define V627    
    96 "Other"
    98 "DK"
;
label define V628    
    96 "Other"
    98 "DK"
;
label define V629    
    96 "Other"
    98 "DK"
;
label define V631    
     9 "Missing"
;
label define V632    
     1 "Mainly respondent"
     2 "Mainly husband, partner"
     3 "Joint decision"
     6 "Other"
;
label define V633A   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V633B   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V633C   
     9 "Missing"
;
label define V633D   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define V633E   
     9 "Missing"
;
label define V633F   
     9 "Missing"
;
label define V633G   
     9 "Missing"
;
label define V634    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V701    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
;
label define V702    
    98 "Don't know"
;
label define V704    
     0 "Not working"
    11 "Armed Forces"
   111 "Legislators"
   112 "Senior Government Officials"
   113 "Traditional Chiefs And Heads Of Villages"
   114 "Senior Officials Of Special Interest Groups"
   115 "Other Government And Senior Officials"
   121 "Directors And Chief Executives"
   122 "Managers And Company Secretaries"
   211 "Physicists And Related Professional"
   212 "Mathematicians, Statisticians And Related Professionals"
   213 "Computing Professionals And Associates"
   214 "Architects And Associated Professionals"
   215 "Engineers - All Types"
   221 "Life Science Professionals"
   222 "Medical Doctors - All Types Except Dentists"
   223 "Nursing And Midwifery Professionals"
   224 "Dentists"
   225 "Veterinarians - All Types"
   226 "Pharmaceuticals Chemists, Pharmacists, Pharmacologists"
   227 "Other Health Professionals"
   231 "College/ University And Higher Education Teaching"
   232 "Secondary Education Teaching Professionals"
   233 "Primary Education Teaching Professionals"
   234 "Special Education Teaching Professionals"
   235 "Other Teaching Professionals"
   236 "Pre-Primary Teachers Including Associates"
   237 "Adult Education And Literacy Teachers"
   241 "Business Professionals"
   242 "Legal Professionals"
   243 "Archivists, Librarians And Related Professionals"
   244 "Social Science And Related Professionals"
   245 "Writers And Creative Or Performance Artists"
   246 "Religion"
   247 "Artistic/ Entertainment And Sports Associate Professiona"
   311 "Physical And Engineering Science Technicians"
   313 "Optical And Electronic Machine Operators"
   314 "Ship And Aircraft Controllers And Technicians"
   315 "Safety Quality Inspectors"
   316 "Technicians - Uncertified"
   321 "Life Science Technicians And Related Professionals"
   322 "Modern Health Associated Professionals (Except Nurses)"
   323 "Medical Assistants"
   324 "Traditional Medicine Practitioners And Faith Healers"
   325 "Temporary (Untrained) Secondary Teachers"
   332 "Temporary (Untrained) Primary Teachers"
   334 "Other Teaching Associate Professionals"
   341 "Finance And Sales Associate Professionals"
   342 "Business Services Agents And Trade Brokers"
   343 "Administrative Associate Professionals"
   344 "Customs, Tax And Related (Govt.) Associate Professional"
   345 "Police Inspectors And Detectives"
   411 "Secretaries And Keyboard Operator Clerks"
   412 "Numerical Clerks"
   413 "Material-Recording And Transport Clerks"
   414 "Library/ Mail And Related Clerks"
   419 "Other Office Clerks"
   421 "Cashiers/ Tellers And Related Clerks"
   422 "Client Information Clerks"
   423 "Other Clerks"
   511 "Travel Attendants And Related Workers"
   512 "Housekeeping And Restaurant Services Workers (Based In I"
   513 "Personal Care And Related Workers"
   514 "Other Personal Services Workers Hairdresser"
   515 "Astrologers/ Fortune-Tellers And Related Workers"
   516 "Protective Services Workers"
   517 "Domestic Workers (Private Homes)"
   521 "Fashion And Other Models"
   522 "Shop Salespersons And Demonstrators"
   523 "Stall And Market Salespersons"
   524 "Businesspersons"
   611 "Commercial Farmers"
   614 "Forestry And Related Workers"
   615 "Fishery Workers, Hunters And Trappers"
   621 "Communal Subsistence Agricultural Workers"
   711 "Miners/ Short-Firers, Stone Cutters And Carvers"
   712 "Building Frame And Related Trades Workers"
   713 "Building Finishers And Related Trades Workers"
   714 "Painters/ Building Structure Cleaners And Related Trades"
   715 "Gold Panners"
   721 "Metal Moulders/ Welders/ Sheet-Metal Workers, Structural"
   722 "Blacksmiths/ Tool-Makers And Related Trades Workers"
   723 "Machinery Mechanics And Fitters"
   724 "Electrical And Electronic Equipment Mechanics And Fitter"
   725 "Workshop Attendants"
   731 "Precision Workers In Metal And Related Materials"
   732 "Potters, Glass-Makers And Related Trades Workers"
   733 "Handicraft Workers In Wood, Textile, Leather And Related"
   734 "Printing And Related Trades Workers"
   741 "Food Processing And Related Trades Workers"
   742 "Wood Treaters Cabinet-Makers And Related Trades Workers"
   743 "Textile, Garment And Related Trades Workers"
   744 "Pelt, Leather And Shoe Making Trades Workers"
   811 "Plant And Machine Operators (All Types)"
   828 "Plant And Machine Assemblers (All Types)"
   829 "Other Machine Operators And Assemblers"
   831 "Locomotive Engine Drivers And Related Workers"
   832 "Motor Vehicle Drivers"
   833 "Agricultural And Other Mobile Plant Operators"
   834 "Ships Deck Crews And Related Workers"
   911 "Street Vendors And Related Workers (Goods)"
   912 "Shoe Cleaning And Other Street Services-Elementary Occup"
   913 "Domestic And Related Helpers, Cleaners And Launderers (N"
   914 "Building Caretakers/ Window And Related Cleaners"
   915 "Messengers/ Porters/ Doorkeepers And Related Workers"
   916 "Garbage Collectors And Related Labourers"
   921 "Agricultural/ Fishery And Related Labourers"
   931 "Mining And Construction Labourers"
   932 "Manufacturing Labourers"
   933 "Transport Labourers And Freight Handlers"
   996 "Not Elsewhere Classified"
   998 "Don't know"
;
label define V705    
     0 "Did not work"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define V714    
     0 "No"
     1 "Yes"
;
label define V714A   
     0 "No"
     1 "Yes"
;
label define V715    
    97 "Inconsistent"
    98 "Don't know"
;
label define V716    
     0 "Not working"
    11 "Armed Forces"
   111 "Legislators"
   112 "Senior Government Officials"
   113 "Traditional Chiefs And Heads Of Villages"
   114 "Senior Officials Of Special Interest Groups"
   115 "Other Government And Senior Officials"
   121 "Directors And Chief Executives"
   122 "Managers And Company Secretaries"
   211 "Physicists And Related Professional"
   212 "Mathematicians, Statisticians And Related Professionals"
   213 "Computing Professionals And Associates"
   214 "Architects And Associated Professionals"
   215 "Engineers - All Types"
   221 "Life Science Professionals"
   222 "Medical Doctors - All Types Except Dentists"
   223 "Nursing And Midwifery Professionals"
   224 "Dentists"
   225 "Veterinarians - All Types"
   226 "Pharmaceuticals Chemists, Pharmacists, Pharmacologists"
   227 "Other Health Professionals"
   231 "College/ University And Higher Education Teaching"
   232 "Secondary Education Teaching Professionals"
   233 "Primary Education Teaching Professionals"
   234 "Special Education Teaching Professionals"
   235 "Other Teaching Professionals"
   236 "Pre-Primary Teachers Including Associates"
   237 "Adult Education And Literacy Teachers"
   241 "Business Professionals"
   242 "Legal Professionals"
   243 "Archivists, Librarians And Related Professionals"
   244 "Social Science And Related Professionals"
   245 "Writers And Creative Or Performance Artists"
   246 "Religion"
   247 "Artistic/ Entertainment And Sports Associate Professiona"
   311 "Physical And Engineering Science Technicians"
   313 "Optical And Electronic Machine Operators"
   314 "Ship And Aircraft Controllers And Technicians"
   315 "Safety Quality Inspectors"
   316 "Technicians - Uncertified"
   321 "Life Science Technicians And Related Professionals"
   322 "Modern Health Associated Professionals (Except Nurses)"
   323 "Medical Assistants"
   324 "Traditional Medicine Practitioners And Faith Healers"
   325 "Temporary (Untrained) Secondary Teachers"
   332 "Temporary (Untrained) Primary Teachers"
   334 "Other Teaching Associate Professionals"
   341 "Finance And Sales Associate Professionals"
   342 "Business Services Agents And Trade Brokers"
   343 "Administrative Associate Professionals"
   344 "Customs, Tax And Related (Govt.) Associate Professional"
   345 "Police Inspectors And Detectives"
   411 "Secretaries And Keyboard Operator Clerks"
   412 "Numerical Clerks"
   413 "Material-Recording And Transport Clerks"
   414 "Library/ Mail And Related Clerks"
   419 "Other Office Clerks"
   421 "Cashiers/ Tellers And Related Clerks"
   422 "Client Information Clerks"
   423 "Other Clerks"
   511 "Travel Attendants And Related Workers"
   512 "Housekeeping And Restaurant Services Workers (Based In I"
   513 "Personal Care And Related Workers"
   514 "Other Personal Services Workers Hairdresser"
   515 "Astrologers/ Fortune-Tellers And Related Workers"
   516 "Protective Services Workers"
   517 "Domestic Workers (Private Homes)"
   521 "Fashion And Other Models"
   522 "Shop Salespersons And Demonstrators"
   523 "Stall And Market Salespersons"
   524 "Businesspersons"
   611 "Commercial Farmers"
   614 "Forestry And Related Workers"
   615 "Fishery Workers, Hunters And Trappers"
   621 "Communal Subsistence Agricultural Workers"
   711 "Miners/ Short-Firers, Stone Cutters And Carvers"
   712 "Building Frame And Related Trades Workers"
   713 "Building Finishers And Related Trades Workers"
   714 "Painters/ Building Structure Cleaners And Related Trades"
   715 "Gold Panners"
   721 "Metal Moulders/ Welders/ Sheet-Metal Workers, Structural"
   722 "Blacksmiths/ Tool-Makers And Related Trades Workers"
   723 "Machinery Mechanics And Fitters"
   724 "Electrical And Electronic Equipment Mechanics And Fitter"
   725 "Workshop Attendants"
   731 "Precision Workers In Metal And Related Materials"
   732 "Potters, Glass-Makers And Related Trades Workers"
   733 "Handicraft Workers In Wood, Textile, Leather And Related"
   734 "Printing And Related Trades Workers"
   741 "Food Processing And Related Trades Workers"
   742 "Wood Treaters Cabinet-Makers And Related Trades Workers"
   743 "Textile, Garment And Related Trades Workers"
   744 "Pelt, Leather And Shoe Making Trades Workers"
   811 "Plant And Machine Operators (All Types)"
   828 "Plant And Machine Assemblers (All Types)"
   829 "Other Machine Operators And Assemblers"
   831 "Locomotive Engine Drivers And Related Workers"
   832 "Motor Vehicle Drivers"
   833 "Agricultural And Other Mobile Plant Operators"
   834 "Ships Deck Crews And Related Workers"
   911 "Street Vendors And Related Workers (Goods)"
   912 "Shoe Cleaning And Other Street Services-Elementary Occup"
   913 "Domestic And Related Helpers, Cleaners And Launderers (N"
   914 "Building Caretakers/ Window And Related Cleaners"
   915 "Messengers/ Porters/ Doorkeepers And Related Workers"
   916 "Garbage Collectors And Related Labourers"
   921 "Agricultural/ Fishery And Related Labourers"
   931 "Mining And Construction Labourers"
   932 "Manufacturing Labourers"
   933 "Transport Labourers And Freight Handlers"
   996 "Not Elsewhere Classified"
;
label define V717    
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
;
label define V719    
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define V721    
     1 "At home"
     2 "Away"
;
label define V729    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
;
label define V730    
    96 "96+"
    98 "DK"
;
label define V731    
     0 "No"
     1 "In the past year"
     2 "Currently working"
     3 "Have a job, but on leave last 7 days"
;
label define V732    
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define V739    
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
;
label define V740    
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define V741    
     0 "Not paid"
     1 "Cash only"
     2 "Cash and kind"
     3 "In kind only"
;
label define V743A   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743B   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743C   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743D   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
;
label define V743E   
     9 "Missing"
;
label define V743F   
     1 "Respondent alone"
     2 "Respondent and husband/partner"
     3 "Respondent and other person"
     4 "Husband/partner alone"
     5 "Someone else"
     6 "Other"
     7 "Husband/partner has no earnings"
;
label define V744A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744D   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V744E   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define V746    
     1 "More than him"
     2 "Less than him"
     3 "About the same"
     4 "Partner doesn't bring in money"
     8 "Don't know"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   100 "Died on day of birth"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
   997 "Inconsistent"
   998 "Don't know"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
;
label define B10     
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define B15     
     0 "No"
     1 "Yes"
;
label define B16     
     0 "Not listed in household"
;
label define M1      
     0 "Received no inject."
     7 "7+"
     8 "Don't know"
;
label define M1A     
     0 "Received no inject."
     7 "7+"
     8 "Don't know"
;
label define M1B     
    97 "Inconsistent"
    98 "Don't know month"
;
label define M1C     
  9997 "Inconsistent"
  9998 "Don't know year"
;
label define M1D     
    99 "Missing"
;
label define M1E     
  9996 "Can't be determined"
;
label define M2A     
     0 "No"
     1 "Yes: doctor"
;
label define M2B     
     0 "No"
     1 "Yes: nurse/midwife"
;
label define M2C     
     9 "Missing"
;
label define M2D     
     9 "Missing"
;
label define M2E     
     9 "Missing"
;
label define M2F     
     0 "No"
     1 "Yes: trained birth A"
;
label define M2G     
     0 "No"
     1 "Yes: trad.birth att."
;
label define M2H     
     9 "Missing"
;
label define M2I     
     0 "No"
     1 "Yes: Unsure about training (CS)"
;
label define M2J     
     9 "Missing"
;
label define M2K     
     0 "No"
     1 "Yes: other responses"
;
label define M2L     
     9 "Missing"
;
label define M2M     
     9 "Missing"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no one"
;
label define M3A     
     0 "No"
     1 "Yes: doctor"
;
label define M3B     
     0 "No"
     1 "Yes: nurse/midwife"
;
label define M3C     
     9 "Missing"
;
label define M3D     
     9 "Missing"
;
label define M3E     
     9 "Missing"
;
label define M3F     
     0 "No"
     1 "Yes: trained birth A"
;
label define M3G     
     0 "No"
     1 "Yes: trad.birth att."
;
label define M3H     
     9 "Missing"
;
label define M3I     
     0 "No"
     1 "Yes: Unsure training (CS)"
;
label define M3J     
     9 "Missing"
;
label define M3K     
     0 "No"
     1 "Yes: other responses"
;
label define M3L     
     9 "Missing"
;
label define M3M     
     9 "Missing"
;
label define M3N     
     0 "No: some assistance"
     1 "Yes: no one"
;
label define M4      
    94 "Never breastfed"
    95 "Still breastfeeding"
    96 "Breastfed until died"
    97 "Inconsistent"
    98 "DK"
;
label define M5      
    94 "Never breastfed"
    97 "Inconsistent"
    98 "DK"
;
label define M6      
    96 "Period not returned"
    97 "Inconsistent"
    98 "DK"
;
label define M7      
    97 "Inconsistent"
    98 "DK"
;
label define M8      
    96 "Still abstaining"
    97 "Inconsistent"
    98 "DK"
;
label define M9      
    97 "Inconsistent"
    98 "DK"
;
label define M10     
     1 "Then"
     2 "Later"
     3 "No more"
;
label define M11     
   998 "DK"
;
label define M13     
    98 "DK"
;
label define M14     
     0 "No antenatal visits"
    98 "DK"
;
label define M15     
    10 "HOMES"
    11 "Respondents home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Central hospital"
    22 "Provincial hospital"
    23 "District/rural hospital"
    24 "Rural/municipal clinic"
    25 "Rural health centre"
    26 "Other public"
    30 "PRIVATE SECTOR"
    31 "Private hospital/ clinic"
    32 "Other private medical"
    33 "Mission facility"
    96 "OTHER"
;
label define M17     
     0 "No"
     1 "Yes"
;
label define M18     
     1 "Very large"
     2 "Larger than average"
     3 "Average"
     4 "Smaller than average"
     5 "Very small"
     8 "DK"
;
label define M19     
  9996 "Not weighed at birth"
  9998 "DK"
;
label define M19A    
     0 "Not weighed"
     1 "From card"
     2 "From recall"
     9 "Special answers"
;
label define M27     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     3 "> age at death"
     4 "During preg in cal."
;
label define M28     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     4 "During preg in cal."
;
label define M29     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     4 "During preg in cal."
;
label define M34     
     0 "Immediately"
   101 "Hours: 1"
   201 "Days: 1"
;
label define M35     
    96 "On demand"
;
label define M36     
    96 "On demand"
;
label define M38     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define M39     
     0 "None"
     7 "7+"
     8 "DK"
;
label define M42A    
     0 "No"
     1 "Yes"
;
label define M42B    
     9 "Missing"
;
label define M42C    
     0 "No"
     1 "Yes"
;
label define M42D    
     0 "No"
     1 "Yes"
;
label define M42E    
     0 "No"
     1 "Yes"
;
label define M43     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M44     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M45     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M46     
   998 "Don't know"
;
label define M47     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M48     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49A    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49C    
     9 "Missing"
;
label define M49D    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49E    
     9 "Missing"
;
label define M49F    
     9 "Missing"
;
label define M49G    
     9 "Missing"
;
label define M49X    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define M49Z    
     0 "No"
     1 "Yes, took no drug"
     8 "Don't know"
;
label define M51A    
   100 "Same hour"
   101 "1 hour"
   200 "Same day"
   201 "1 day"
   300 "Same week"
   301 "1 week"
   998 "Don't know"
;
label define M54     
     0 "No"
     1 "Yes"
;
label define M55A    
     0 "No"
     1 "Yes"
;
label define M55B    
     0 "No"
     1 "Yes"
;
label define M55C    
     0 "No"
     1 "Yes"
;
label define M55D    
     0 "No"
     1 "Yes"
;
label define M55E    
     0 "No"
     1 "Yes"
;
label define M55F    
     0 "No"
     1 "Yes"
;
label define M55G    
     0 "No"
     1 "Yes"
;
label define M55H    
     0 "No"
     1 "Yes"
;
label define M55I    
     0 "No"
     1 "Yes"
;
label define M55J    
     9 "Missing"
;
label define M55K    
     9 "Missing"
;
label define M55L    
     9 "Missing"
;
label define M55M    
     9 "Missing"
;
label define M55N    
     9 "Missing"
;
label define M55X    
     0 "No"
     1 "Yes"
;
label define M55Z    
     0 "No"
     1 "Yes, given nothing"
;
label define M57A    
     0 "No"
     1 "Yes"
;
label define M57B    
     0 "No"
     1 "Yes"
;
label define M57C    
     9 "Missing"
;
label define M57D    
     9 "Missing"
;
label define M57E    
     0 "No"
     1 "Yes"
;
label define M57F    
     0 "No"
     1 "Yes"
;
label define M57G    
     0 "No"
     1 "Yes"
;
label define M57H    
     9 "Missing"
;
label define M57I    
     9 "Missing"
;
label define M57J    
     9 "Missing"
;
label define M57K    
     9 "Missing"
;
label define M57L    
     0 "No"
     1 "Yes"
;
label define M57M    
     0 "No"
     1 "Yes"
;
label define M57N    
     9 "Missing"
;
label define M57O    
     0 "No"
     1 "Yes"
;
label define M57P    
     9 "Missing"
;
label define M57Q    
     9 "Missing"
;
label define M57R    
     0 "No"
     1 "Yes"
;
label define M57S    
     9 "Missing"
;
label define M57T    
     9 "Missing"
;
label define M57U    
     9 "Missing"
;
label define M57V    
     9 "Missing"
;
label define M57X    
     0 "No"
     1 "Yes"
;
label define M60     
     9 "Missing"
;
label define M61     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M62     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define M63     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M64     
    10 "HEALTH PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional midwife trained"
    22 "Traditional midwife untrained"
    23 "Unsure about training"
    96 "Other"
;
label define M65A    
     0 "No"
     1 "Yes"
;
label define M65B    
     0 "No"
     1 "Yes"
;
label define M65C    
     0 "No"
     1 "Yes"
;
label define M65D    
     0 "No"
     1 "Yes"
;
label define M65E    
     0 "No"
     1 "Yes"
;
label define M65F    
     0 "No"
     1 "Yes"
;
label define M65G    
     0 "No"
     1 "Yes"
;
label define M65H    
     0 "No"
     1 "Yes"
;
label define M65I    
     0 "No"
     1 "Yes"
;
label define M65J    
     9 "Missing"
;
label define M65K    
     9 "Missing"
;
label define M65L    
     9 "Missing"
;
label define M65X    
     0 "No"
     1 "Yes"
;
label define M66     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define M67     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M68     
    10 "HEALTH PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional midwife trained"
    22 "Traditional midwife untrained"
    23 "Unsure about training"
    96 "Other"
;
label define M69     
    10 "HOME"
    11 "Respondent's home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Central hospital"
    22 "Provincial hospital"
    23 "District/rural hospital"
    24 "Rural/municipal clinic"
    25 "Rural health centre"
    26 "Other public"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital, clinic"
    32 "Mission facility"
    36 "Other private medical"
    96 "Other"
;
label define M70     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define M71     
   100 "Zero hours"
   201 "One day"
   301 "One week"
   998 "DK"
;
label define M72     
    10 "HEALTH PERSONNEL"
    11 "Doctor"
    12 "Nurse, midwife"
    13 "Auxiliary midwife"
    20 "OTHER PERSON"
    21 "Traditional midwife trained"
    22 "Traditional midwife untrained"
    23 "Unsure about training"
    96 "Other"
;
label define M73     
    10 "HOME"
    11 "Respondent's home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Central hospital"
    22 "Provincial hospital"
    23 "District/rural hospital"
    24 "Rural/municipal clinic"
    25 "Rural health centre"
    26 "Other public"
    30 "PRIVATE MEDICAL SECTOR"
    31 "Private hospital, clinic"
    32 "Mission facility"
    36 "Other private medical"
    96 "Other"
;
label define H1      
     0 "No card"
     1 "Yes, seen"
     2 "Yes, not seen"
     3 "No longer has card"
;
label define H2      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H2D     
    97 "Inconsistent"
    98 "DK"
;
label define H2M     
    97 "Inconsistent"
    98 "DK"
;
label define H2Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H3      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H3D     
    97 "Inconsistent"
    98 "DK"
;
label define H3M     
    97 "Inconsistent"
    98 "DK"
;
label define H3Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H4      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H4D     
    97 "Inconsistent"
    98 "DK"
;
label define H4M     
    97 "Inconsistent"
    98 "DK"
;
label define H4Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H5      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H5D     
    97 "Inconsistent"
    98 "DK"
;
label define H5M     
    97 "Inconsistent"
    98 "DK"
;
label define H5Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H6      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H6D     
    97 "Inconsistent"
    98 "DK"
;
label define H6M     
    97 "Inconsistent"
    98 "DK"
;
label define H6Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H7      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H7D     
    97 "Inconsistent"
    98 "DK"
;
label define H7M     
    97 "Inconsistent"
    98 "DK"
;
label define H7Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H8      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H8D     
    97 "Inconsistent"
    98 "DK"
;
label define H8M     
    97 "Inconsistent"
    98 "DK"
;
label define H8Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H9      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H9D     
    97 "Inconsistent"
    98 "DK"
;
label define H9M     
    97 "Inconsistent"
    98 "DK"
;
label define H9Y     
  9997 "Inconsistent"
  9998 "DK"
;
label define H0      
     9 "Missing"
;
label define H0D     
    99 "Missing"
;
label define H0M     
    99 "Missing"
;
label define H0Y     
  9999 "Missing"
;
label define H10     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H11     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H11B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H12A    
     0 "No"
     1 "Government hospital"
;
label define H12B    
     0 "No"
     1 "Govt. health center"
;
label define H12C    
     9 "Missing"
;
label define H12D    
     9 "Missing"
;
label define H12E    
     0 "No"
     1 "Community health wrk"
;
label define H12F    
     0 "No"
     1 "Provincial hospital (CS)"
;
label define H12G    
     0 "No"
     1 "District/rural hospital (CS)"
;
label define H12H    
     0 "No"
     1 "Municipal clinic (CS)"
;
label define H12I    
     0 "No"
     1 "Other public sector"
;
label define H12J    
     0 "No"
     1 "Private hosp./clinic"
;
label define H12K    
     0 "No"
     1 "Private pharmacy"
;
label define H12L    
     0 "No"
     1 "Private doctor"
;
label define H12M    
     9 "Missing"
;
label define H12N    
     9 "Missing"
;
label define H12O    
     0 "No"
     1 "Mission facility (CS)"
;
label define H12P    
     9 "Missing"
;
label define H12Q    
     9 "Missing"
;
label define H12R    
     0 "No"
     1 "Oth med.priv. sector"
;
label define H12S    
     0 "No"
     1 "Shop"
;
label define H12T    
     0 "No"
     1 "Traditional pract."
;
label define H12U    
     9 "Missing"
;
label define H12V    
     9 "Missing"
;
label define H12W    
     9 "Missing"
;
label define H12X    
     0 "No"
     1 "Other"
;
label define H12Y    
     0 "No: received treatm."
     1 "Yes: no treatment"
;
label define H12Z    
     0 "No"
     1 "Yes: medical treatm."
;
label define H13     
     0 "No"
     1 "Yes: ORS - spontan."
     2 "Yes: ORS - probed"
     8 "Don't know"
;
label define H13B    
     9 "Missing"
;
label define H14     
     0 "No"
     1 "Yes: RHS - spontan."
     2 "Yes: RHS - probed"
     8 "Don't know"
;
label define H15     
     0 "No"
     1 "Yes: oth pill, syrup"
     8 "Don't know"
;
label define H15A    
     0 "No"
     1 "Yes: antibiotics"
     8 "Don't know"
;
label define H15B    
     0 "No"
     1 "Yes: injection"
     8 "Don't know"
;
label define H15C    
     0 "No"
     1 "Yes: intravenous (IV"
     8 "Don't know"
;
label define H15D    
     0 "No"
     1 "Yes: home rem, herb."
     8 "Don't know"
;
label define H15E    
     9 "Missing"
;
label define H15F    
     0 "No"
     1 "Yes: CS other treatm"
     8 "Don't know"
;
label define H15G    
     0 "No"
     1 "Yes: CS other treatm"
     8 "Don't know"
;
label define H15H    
     0 "No"
     1 "Yes: CS other treatm"
     8 "Don't know"
;
label define H15I    
     0 "No"
     1 "Yes: CS other treatm"
     8 "Don't know"
;
label define H15J    
     9 "Missing"
;
label define H15K    
     9 "Missing"
;
label define H15L    
     9 "Missing"
;
label define H15M    
     9 "Missing"
;
label define H20     
     0 "No"
     1 "Yes"
;
label define H21A    
     0 "No: received treatm."
     1 "Yes: no treatment"
     8 "DK"
;
label define H21     
     0 "No"
     1 "Yes"
;
label define H22     
     0 "No"
     1 "Yes"
     8 "DK"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
;
label define H31B    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define H31C    
     1 "Chest only"
     2 "Nose only"
     3 "Both"
     6 "Other"
     8 "Don't know"
;
label define H31D    
     0 "Nothing to drink"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H31E    
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H32A    
     0 "No"
     1 "Government hospital"
;
label define H32B    
     0 "No"
     1 "Govt. health center"
;
label define H32C    
     9 "Missing"
;
label define H32D    
     9 "Missing"
;
label define H32E    
     0 "No"
     1 "Community health wrk"
;
label define H32F    
     0 "No"
     1 "Provincial hospital (CS)"
;
label define H32G    
     0 "No"
     1 "District/rural hospital (CS)"
;
label define H32H    
     0 "No"
     1 "Municipal clinic (CS)"
;
label define H32I    
     0 "No"
     1 "Other public sector"
;
label define H32J    
     0 "No"
     1 "Private hosp./clinic"
;
label define H32K    
     0 "No"
     1 "Private pharmacy"
;
label define H32L    
     9 "Missing"
;
label define H32M    
     9 "Missing"
;
label define H32N    
     9 "Missing"
;
label define H32O    
     0 "No"
     1 "Mission facility (CS)"
;
label define H32P    
     9 "Missing"
;
label define H32Q    
     9 "Missing"
;
label define H32R    
     0 "No"
     1 "Oth med. priv. sect."
;
label define H32S    
     0 "No"
     1 "Shop"
;
label define H32T    
     0 "No"
     1 "Traditional pract."
;
label define H32U    
     9 "Missing"
;
label define H32V    
     9 "Missing"
;
label define H32W    
     9 "Missing"
;
label define H32X    
     0 "No"
     1 "Other"
;
label define H32Y    
     0 "No: received treatm."
     1 "Yes: no treatment"
;
label define H32Z    
     0 "No"
     1 "Yes: medical treatm."
;
label define H33     
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H33D    
    97 "Inconsistent"
    98 "DK"
;
label define H33M    
    97 "Inconsistent"
    98 "DK"
;
label define H33Y    
  9997 "Inconsistent"
  9998 "DK"
;
label define H34     
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H35     
     0 "No"
     1 "Yes"
     2 "No vaccination in last 2 years"
     8 "Don't know"
;
label define H36A    
     9 "Missing"
;
label define H36B    
     9 "Missing"
;
label define H36C    
     9 "Missing"
;
label define H36D    
     9 "Missing"
;
label define H36E    
     9 "Missing"
;
label define H36F    
     9 "Missing"
;
label define H37A    
     0 "No"
     1 "Yes"
;
label define H37B    
     0 "No"
     1 "Yes"
;
label define H37C    
     9 "Missing"
;
label define H37D    
     0 "No"
     1 "Yes"
;
label define H37E    
     0 "No"
     1 "Yes"
;
label define H37F    
     9 "Missing"
;
label define H37G    
     9 "Missing"
;
label define H37H    
     0 "No"
     1 "Yes"
;
label define H37I    
     9 "Missing"
;
label define H37J    
     9 "Missing"
;
label define H37K    
     0 "No"
     1 "Yes"
;
label define H37L    
     0 "No"
     1 "Yes"
;
label define H37M    
     0 "No"
     1 "Yes"
;
label define H37N    
     0 "No"
     1 "Yes"
;
label define H37O    
     0 "No"
     1 "Yes"
;
label define H37P    
     0 "No"
     1 "Yes"
;
label define H37X    
     0 "No"
     1 "Yes"
;
label define H37Y    
     0 "No"
     1 "Yes, nothing taken"
;
label define H37Z    
     0 "No"
     1 "Yes, DK"
;
label define H38     
     0 "Nothing to drink"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H39     
     0 "Stopped food"
     1 "Never gave food"
     2 "Much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define H40     
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define H40D    
    97 "Inconsistent"
    98 "DK"
;
label define H40M    
    97 "Inconsistent"
    98 "DK"
;
label define H40Y    
  9997 "Inconsistent"
  9998 "DK"
;
label define H41A    
     9 "Missing"
;
label define H41B    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H42     
     9 "Missing"
;
label define H43     
     9 "Missing"
;
label define H44A    
    10 "PUBLIC SECTOR"
    11 "Central hospital"
    12 "Provincial hospital"
    13 "District/rural hospital"
    14 "Rural health centre"
    15 "Municipal clinic"
    16 "Village community/health worker"
    17 "Other public"
    20 "PRIVATE MEDICAL"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private mobile clinic"
    25 "Mission facility"
    26 "Other private"
    30 "PRIVATE NON MEDICAL SECTOR"
    31 "Shop"
    32 "Traditional practitioner"
    96 "Other"
;
label define H44B    
     0 "Same day"
    98 "Don't know"
;
label define H44C    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define H45     
    99 "Missing"
;
label define H46A    
    10 "PUBLIC SECTOR"
    11 "Government hospital"
    12 "Government health center"
    13 "Government health post"
    14 "Mobile clinic"
    15 "Field worker"
    16 "Other public"
    20 "PRIVATE MEDICAL SECTOR"
    21 "Private hospital, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private mobile clinic"
    25 "Field worker"
    27 "Other private"
    26 "Other private"
    30 "PRIVATE NON MEDICAL SECTOR"
    31 "Shop"
    32 "Traditional practitioner"
    96 "Other"
;
label define H46B    
     0 "Same day"
    98 "Don't know"
;
label define HW2     
   999 "Missing"
;
label define HW3     
  9999 "Missing"
;
label define HW4     
  9998 "Flagged cases"
;
label define HW5     
  9998 "Flagged cases"
;
label define HW6     
 99998 "Flagged cases"
;
label define HW7     
  9998 "Flagged cases"
;
label define HW8     
  9998 "Flagged cases"
;
label define HW9     
 99998 "Flagged cases"
;
label define HW10    
  9998 "Flagged cases"
;
label define HW11    
  9998 "Flagged cases"
;
label define HW12    
 99998 "Flagged cases"
;
label define HW13    
     0 "Measured"
     1 "Dead"
     2 "Sick"
     3 "Not present"
     4 "Refused"
     5 "Mother refused"
     6 "Other"
     7 "No measurement found in HH"
;
label define HW15    
     1 "Lying"
     2 "Standing"
;
label define HW16    
    97 "Inconsistent"
    98 "DK"
;
label define HW51    
     0 "Not in household"
;
label define HW52    
     1 "Granted"
     2 "Refused"
;
label define HW53    
   999 "Missing"
;
label define HW55    
     0 "Measured"
     1 "Dead"
     3 "Not present"
     4 "Refused"
     6 "Other"
     7 "No measurement found in HH"
;
label define HW56    
  9999 "Missing"
;
label define HW57    
     1 "Severe"
     2 "Moderate"
     3 "Mild"
     4 "Not anemic"
;
label define HW58    
     9 "Missing"
;
label define HW70    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HW71    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HW72    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define HW73    
  9996 "Height out of plausible limits"
  9997 "Age in days out of plausible limits"
  9998 "Flagged cases"
;
label define ML0     
     0 "No bednet"
     1 "Only treated bednets"
     2 "Both treated and untreated bednets"
     3 "Only untreated bednets"
;
label define ML1     
    98 "Don't know"
;
label define ML2     
     1 "Antenatal visit"
     2 "Another facility visit"
     6 "Other source"
;
label define ML11    
     0 "No"
     1 "Yes, fever only"
     2 "Yes, cough only"
     3 "Both fever and cough"
     8 "Don't know"
;
label define ML12    
     9 "Missing"
;
label define ML13A   
     0 "No"
     1 "Yes"
;
label define ML13B   
     0 "No"
     1 "Yes"
;
label define ML13C   
     9 "Missing"
;
label define ML13D   
     0 "No"
     1 "Yes"
;
label define ML13E   
     0 "No"
     1 "Yes"
;
label define ML13F   
     9 "Missing"
;
label define ML13G   
     9 "Missing"
;
label define ML13H   
     0 "No"
     1 "Yes"
;
label define ML13I   
     9 "Missing"
;
label define ML13J   
     9 "Missing"
;
label define ML13K   
     0 "No"
     1 "Yes"
;
label define ML13L   
     0 "No"
     1 "Yes"
;
label define ML13M   
     0 "No"
     1 "Yes"
;
label define ML13N   
     0 "No"
     1 "Yes"
;
label define ML13O   
     0 "No"
     1 "Yes"
;
label define ML13P   
     0 "No"
     1 "Yes"
;
label define ML13X   
     0 "No"
     1 "Yes"
;
label define ML13Y   
     0 "No"
     1 "Yes, nothing taken"
;
label define ML13Z   
     0 "No"
     1 "Yes, DK"
;
label define ML14A   
     9 "Missing"
;
label define ML14B   
     9 "Missing"
;
label define ML14Y   
     9 "Missing"
;
label define ML14Z   
     9 "Missing"
;
label define ML15A   
     0 "Same day as fever/convulsion"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML15B   
     7 "7+ days"
     8 "Don't know"
;
label define ML15C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML16A   
     0 "Same day as fever/convulsion"
     1 "Next day"
     2 "2 days after"
     3 "3+ days after"
     8 "Don't know"
;
label define ML16B   
     7 "7+ days"
     8 "Don't know"
;
label define ML16C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML17A   
     9 "Missing"
;
label define ML17B   
     9 "Missing"
;
label define ML17C   
     9 "Missing"
;
label define ML18A   
     9 "Missing"
;
label define ML18B   
     9 "Missing"
;
label define ML18C   
     0 "Other source"
     1 "At home"
     8 "Don't know"
;
label define ML19A   
     0 "No"
     1 "Yes"
;
label define ML19B   
     0 "No"
     1 "Yes"
;
label define ML19C   
     0 "No"
     1 "Yes"
;
label define ML19D   
     9 "Missing"
;
label define ML19E   
     9 "Missing"
;
label define ML19F   
     9 "Missing"
;
label define ML19X   
     0 "No"
     1 "Yes"
;
label define ML19Y   
     0 "No"
     1 "Yes"
;
label define ML19Z   
     0 "No"
     1 "Yes"
;
label define ML20A   
     9 "Missing"
;
label define ML20B   
     9 "Missing"
;
label define ML20C   
     9 "Missing"
;
label define ML21A   
     9 "Missing"
;
label define ML21B   
     9 "Missing"
;
label define ML21C   
     9 "Missing"
;
label define ML22A   
     9 "Missing"
;
label define ML22B   
     9 "Missing"
;
label define ML22C   
     9 "Missing"
;
label define ML23A   
     9 "Missing"
;
label define ML23B   
     9 "Missing"
;
label define ML23C   
     9 "Missing"
;
label define ML24C   
     9 "Missing"
;
label define SLANGQ  
     1 "Shona"
     2 "Ndebele"
     3 "English"
     6 "Other"
;
label define SLANGINT
     1 "Shona"
     2 "Ndebele"
     3 "English"
     6 "Other"
;
label define SINTERP 
     0 "No"
     1 "Yes"
;
label define S119    
     0 "Did not attend"
    98 "Don't know/not sure"
    99 "Missing"
;
label define S240    
     0 "No"
     1 "Yes"
;
label define S241    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S242    
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define S336    
     1 "Most of the time"
     2 "Sometimes"
     3 "Not at all"
     8 "Don't know/not sure"
;
label define S338    
     1 "Most of the time"
     2 "Sometimes"
     3 "Not at all"
     8 "Don't know/not sure"
;
label define S630A   
     1 "Prevent STD/HIV"
     2 "Prevent pregnancy"
     3 "Prevent both (STD/HIV and pregnancy)"
     4 "Partner insisted"
     6 "Other"
     8 "Don't know"
;
label define S630B   
     1 "Prevent STD/HIV"
     2 "Prevent pregnancy"
     3 "Prevent both (STD/HIV and pregnancy)"
     4 "Partner insisted"
     6 "Other"
     8 "Don't know"
;
label define S630C   
     1 "Prevent STD/HIV"
     2 "Prevent pregnancy"
     3 "Prevent both (STD/HIV and pregnancy)"
     4 "Partner insisted"
     6 "Other"
     8 "Don't know"
;
label define S643    
     1 "Choice assorted"
     2 "Durex"
     3 "Ecstasy"
     4 "Protecta"
     5 "Public sector dist."
     6 "Rough rider"
     7 "Other male condom"
     8 "Male condom, don't know"
     9 "Care"
    10 "Other female condom"
    12 "Female condom, don't know"
;
label define S644    
    98 "Don't know"
;
label define S645    
999995 "Free"
999998 "Don't know"
;
label define S646    
    11 "Government hospital/clinic"
    12 "Rural/Municipal clinic"
    13 "Rural health centre"
    14 "ZNFPC clinic"
    15 "MOH mobile clinic"
    16 "ZNFPC CBD/Depot holder"
    17 "Village/Farm health worker"
    18 "Other Public"
    21 "Mission facility"
    31 "Private hospital clinic"
    32 "Pharmacy"
    33 "Private doctor"
    34 "CBD"
    35 "Other Private Doctor"
    41 "General dealer"
    42 "Supermarket"
    43 "Tuck Shop"
    44 "Service station"
    45 "Other retail"
    46 "Church"
    47 "Friend/relative"
    96 "Other"
    98 "Don't know/not sure"
;
label define S649O   
     0 "No"
     1 "Yes"
;
label define S649P   
     0 "No"
     1 "Yes"
;
label define S649Q   
     0 "No"
     1 "Yes"
;
label define S653O   
     0 "No"
     1 "Yes"
;
label define S653P   
     0 "No"
     1 "Yes"
;
label define S653Q   
     0 "No"
     1 "Yes"
;
label define S723    
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S909A   
     0 "No"
     1 "Yes"
;
label define S909B   
     0 "No"
     1 "Yes"
;
label define S909C   
     0 "No"
     1 "Yes"
;
label define S909D   
     0 "No"
     1 "Yes"
;
label define S909E   
     0 "No"
     1 "Yes"
;
label define S909F   
     0 "No"
     1 "Yes"
;
label define S909G   
     0 "No"
     1 "Yes"
;
label define S909H   
     0 "No"
     1 "Yes"
;
label define S909I   
     0 "No"
     1 "Yes"
;
label define S909J   
     0 "No"
     1 "Yes"
;
label define S909K   
     0 "No"
     1 "Yes"
;
label define S909L   
     0 "No"
     1 "Yes"
;
label define S909M   
     0 "No"
     1 "Yes"
;
label define S909N   
     0 "No"
     1 "Yes"
;
label define S909W   
     0 "No"
     1 "Yes"
;
label define S909X   
     0 "No"
     1 "Yes"
;
label define S909Z   
     0 "No"
     1 "Yes"
;
label define S910    
     1 "Low"
     2 "Medium"
     3 "High"
     4 "No risk"
     8 "Don't know"
;
label define S920    
     1 "Asked for test"
     2 "Offered and accepted"
     3 "Required"
;
label define S932    
     0 "No"
     1 "Yes"
     3 "No husband/partner"
;
label define S933    
     1 "Can't afford it"
     2 "Don't know where to go"
     3 "Testing site difficult to get to"
     4 "Afraid of test result"
     5 "Fatalistic/nothing can be done"
     6 "Concerned about confidentiality"
     7 "No risk/not sexually active"
    96 "Other"
    98 "Don't know"
;
label define S937    
     0 "No"
     1 "Yes"
     8 "DK"
;
label define S938    
     0 "No"
     1 "Yes"
;
label define S942A   
     1 "Should be allowed"
     2 "Should not be allowed"
     8 "Don't know, not sure, depends"
;
label define S950    
     1 "Agree"
     2 "Disagree"
     8 "DK"
;
label define S1012   
     1 "Most of the time"
     2 "Sometimes"
     3 "Not at all"
     8 "Don't know/unsure"
;
label define S1014   
     1 "Most of the time"
     2 "Sometimes"
     3 "Not at all"
     8 "Don't know/unsure"
;
label define S1016   
     0 "No"
     1 "Yes"
;
label define S1017   
     1 "Privately pruchased by individual"
     2 "Through employer only"
     3 "Partially through employer"
     4 "None"
     6 "Other"
     8 "Don't know/unsure"
;
label define S1106HN 
     1 "Often"
     2 "Sometimes"
     3 "Not at all"
;
label define S1112   
     1 "Often"
     2 "Sometimes"
     3 "Never"
;
label define S1113D  
     0 "No"
     1 "Yes"
;
label define S1114A  
     0 "No"
     1 "Yes"
;
label define S1114AN 
     1 "Often"
     2 "Sometimes"
     3 "Not at all"
;
label define S1114B  
     0 "No"
     1 "Yes"
;
label define S1114BN 
     1 "Often"
     2 "Sometimes"
     3 "Not at all"
;
label define S1114C  
     0 "No"
     1 "Yes"
;
label define S1114CN 
     1 "Often"
     2 "Sometimes"
     3 "Not at all"
;
label define S1114D  
     0 "No"
     1 "Yes"
;
label define S1114DN 
     1 "Often"
     2 "Sometimes"
     3 "Not at all"
;
label define S1116   
     0 "No"
     1 "Yes"
;
label define S1117A  
     0 "No"
     1 "Yes"
     3 "Refused to answer / no response"
;
label define S1117B  
     0 "No"
     1 "Yes"
     3 "Refused to answer / no response"
;
label define S1118A  
     0 "No"
     1 "Yes"
;
label define S1118B  
     0 "No"
     1 "Yes"
;
label define S1118C  
     0 "No"
     1 "Yes"
;
label define S1118D  
     0 "No"
     1 "Yes"
;
label define S1118E  
     0 "No"
     1 "Yes"
;
label define S1118F  
     0 "No"
     1 "Yes"
;
label define S1118G  
     0 "No"
     1 "Yes"
;
label define S1118H  
     0 "No"
     1 "Yes"
;
label define S1118I  
     0 "No"
     1 "Yes"
;
label define S1118J  
     0 "No"
     1 "Yes"
;
label define S1118K  
     0 "No"
     1 "Yes"
;
label define S1118L  
     0 "No"
     1 "Yes"
;
label define S1118M  
     0 "No"
     1 "Yes"
;
label define S1118N  
     0 "No"
     1 "Yes"
;
label define S1118O  
     0 "No"
     1 "Yes"
;
label define S1118P  
     0 "No"
     1 "Yes"
;
label define S1118X  
     0 "No"
     1 "Yes"
;
label define S1134   
     1 "Don't know who to go to"
     2 "No use/fatalistic"
     3 "Part of life"
     4 "Afraid of divorce/separation"
     5 "Afraid of further abuse"
     6 "Afraid of getting abuser in trouble"
     7 "Embarrassed"
     8 "Don't want to disgrace the family"
    96 "Other"
;
label define S436    
    25 "25 hours or more"
    98 "Don't know"
;
label define S437    
    25 "25 hours or more"
    98 "Don't know"
;
label define S439    
   100 "< 1 hour after delivery"
   101 "1 hour after delivery"
   200 "< 1 day after delivery"
   201 "1 day after delivery"
   300 "< 1 week after delivery"
   301 "1 week after delivery"
   998 "Don't know"
;
label define S449    
     0 "No"
     1 "Yes"
;
label define S508P4  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58P4  
    97 "Inconsistent"
    98 "DK"
;
label define SM58P4  
    97 "Inconsistent"
    98 "DK"
;
label define SY58P4  
  9997 "Inconsistent"
  9998 "DK"
;
label define S508P5  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58P5  
    99 "Missing"
;
label define SM58P5  
    99 "Missing"
;
label define SY58P5  
  9999 "Missing"
;
label define S508D4  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58D4  
    97 "Inconsistent"
    98 "DK"
;
label define SM58D4  
    97 "Inconsistent"
    98 "DK"
;
label define SY58D4  
  9997 "Inconsistent"
  9998 "DK"
;
label define S508H2  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58H2  
    97 "Inconsistent"
    98 "DK"
;
label define SM58H2  
    97 "Inconsistent"
    98 "DK"
;
label define SY58H2  
  9997 "Inconsistent"
  9998 "DK"
;
label define S508H3  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58H3  
    97 "Inconsistent"
    98 "DK"
;
label define SM58H3  
    97 "Inconsistent"
    98 "DK"
;
label define SY58H3  
  9997 "Inconsistent"
  9998 "DK"
;
label define S508H1  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58H1  
    97 "Inconsistent"
    98 "DK"
;
label define SM58H1  
    97 "Inconsistent"
    98 "DK"
;
label define SY58H1  
  9997 "Inconsistent"
  9998 "DK"
;
label define S508M2  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58M2  
    97 "Inconsistent"
    98 "DK"
;
label define SM58M2  
    97 "Inconsistent"
    98 "DK"
;
label define SY58M2  
  9997 "Inconsistent"
  9998 "DK"
;
label define S508PA  
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
;
label define SD58PA  
    97 "Inconsistent"
    98 "DK"
;
label define SM58PA  
    97 "Inconsistent"
    98 "DK"
;
label define SY58PA  
  9997 "Inconsistent"
  9998 "DK"
;
label define S558A   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S558B   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define S549I   
     0 "No"
     1 "Yes"
;
label define S549J   
     0 "No"
     1 "Yes"
;
label define S549K   
     0 "No"
     1 "Yes"
;
label define S532C   
     0 "No"
     1 "Yes"
     8 "Don't know"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v020     V020    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v042     V042    
label values v044     V044    
label values v101     V101    
label values v102     V102    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v113     V113    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v122     V122    
label values v123     V123    
label values v124     V124    
label values v125     V125    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v153     V153    
label values v155     V155    
label values v156     V156    
label values v157     V157    
label values v158     V158    
label values v159     V159    
label values v160     V160    
label values v161     V161    
label values v167     V167    
label values v168     V168    
label values v190     V190    
label values ml101    ML101   
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v217     V217    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v237     V237    
label values v239     V239    
label values v240     V240    
label values v241     V241    
label values v242     V242    
label values v243     V243    
label values v311     V311    
label values v312     V312    
label values v313     V313    
label values v318     V318    
label values v319     V319    
label values v320     V320    
label values v321     V321    
label values v322     V322    
label values v323     V323    
label values v323a    V323A   
label values v325a    V325A   
label values v326     V326    
label values v327     V327    
label values v337     V337    
label values v359     V359    
label values v360     V360    
label values v361     V361    
label values v362     V362    
label values v363     V363    
label values v364     V364    
label values v367     V367    
label values v372     V372    
label values v376     V376    
label values v376a    V376A   
label values v384a    V384A   
label values v384b    V384B   
label values v384c    V384C   
label values v393     V393    
label values v394     V394    
label values v395     V395    
label values v3a00a   V3A00A  
label values v3a00b   V3A00B  
label values v3a00c   V3A00C  
label values v3a00d   V3A00D  
label values v3a00f   V3A00F  
label values v3a00g   V3A00G  
label values v3a00i   V3A00I  
label values v3a00j   V3A00J  
label values v3a00k   V3A00K  
label values v3a00l   V3A00L  
label values v3a00o   V3A00O  
label values v3a00p   V3A00P  
label values v3a00r   V3A00R  
label values v3a00s   V3A00S  
label values v3a00t   V3A00T  
label values v3a00u   V3A00U  
label values v3a00v   V3A00V  
label values v3a00w   V3A00W  
label values v3a00x   V3A00X  
label values v3a00y   V3A00Y  
label values v3a00z   V3A00Z  
label values v3a01    V3A01   
label values v3a02    V3A02   
label values v3a04    V3A04   
label values v3a05    V3A05   
label values v3a06    V3A06   
label values v3a07    V3A07   
label values v3a08a   V3A08A  
label values v3a08b   V3A08B  
label values v3a08c   V3A08C  
label values v3a08d   V3A08D  
label values v3a08e   V3A08E  
label values v3a08f   V3A08F  
label values v3a08g   V3A08G  
label values v3a08h   V3A08H  
label values v3a08i   V3A08I  
label values v3a08j   V3A08J  
label values v3a08k   V3A08K  
label values v3a08l   V3A08L  
label values v3a08m   V3A08M  
label values v3a08n   V3A08N  
label values v3a08o   V3A08O  
label values v3a08p   V3A08P  
label values v3a08q   V3A08Q  
label values v3a08r   V3A08R  
label values v3a08s   V3A08S  
label values v3a08t   V3A08T  
label values v3a08x   V3A08X  
label values v3a08z   V3A08Z  
label values v3a09a   V3A09A  
label values v401     V401    
label values v404     V404    
label values v405     V405    
label values v406     V406    
label values v407     V407    
label values v408     V408    
label values v409     V409    
label values v410a    V410A   
label values v411     V411    
label values v411a    V411A   
label values v412a    V412A   
label values v412b    V412B   
label values v413     V413    
label values v413a    V413A   
label values v414e    V414E   
label values v414f    V414F   
label values v414g    V414G   
label values v414h    V414H   
label values v414i    V414I   
label values v414j    V414J   
label values v414k    V414K   
label values v414l    V414L   
label values v414m    V414M   
label values v414n    V414N   
label values v414o    V414O   
label values v414p    V414P   
label values v414q    V414Q   
label values v414r    V414R   
label values v414s    V414S   
label values v414t    V414T   
label values v414u    V414U   
label values v415     V415    
label values v426     V426    
label values v439     V439    
label values v440     V440    
label values v441     V441    
label values v442     V442    
label values v443     V443    
label values v444     V444    
label values v444a    V444A   
label values v445     V445    
label values v446     V446    
label values v447     V447    
label values v452a    V452A   
label values v452b    V452B   
label values v452c    V452C   
label values v454     V454    
label values v455     V455    
label values v457     V457    
label values v459     V459    
label values v460     V460    
label values v461     V461    
label values v463a    V463A   
label values v463b    V463B   
label values v463c    V463C   
label values v463d    V463D   
label values v463x    V463X   
label values v463z    V463Z   
label values v465     V465    
label values v467b    V467B   
label values v467c    V467C   
label values v467d    V467D   
label values v467e    V467E   
label values v467f    V467F   
label values v467g    V467G   
label values v467h    V467H   
label values v467i    V467I   
label values v468     V468    
label values v471a    V471A   
label values v471b    V471B   
label values v471c    V471C   
label values v471d    V471D   
label values v471e    V471E   
label values v472e    V472E   
label values v472f    V472F   
label values v472g    V472G   
label values v472h    V472H   
label values v472i    V472I   
label values v472j    V472J   
label values v472k    V472K   
label values v472l    V472L   
label values v472m    V472M   
label values v472n    V472N   
label values v472o    V472O   
label values v472p    V472P   
label values v472q    V472Q   
label values v472r    V472R   
label values v472s    V472S   
label values v472t    V472T   
label values v472u    V472U   
label values v473a    V473A   
label values v473b    V473B   
label values v474     V474    
label values v474a    V474A   
label values v474b    V474B   
label values v474c    V474C   
label values v474d    V474D   
label values v474e    V474E   
label values v474f    V474F   
label values v474x    V474X   
label values v474z    V474Z   
label values v475     V475    
label values v476     V476    
label values v477     V477    
label values v478     V478    
label values v479     V479    
label values v480     V480    
label values v481     V481    
label values v481b    V481B   
label values v481d    V481D   
label values v481f    V481F   
label values v481g    V481G   
label values v481x    V481X   
label values v501     V501    
label values v502     V502    
label values v503     V503    
label values v504     V504    
label values v505     V505    
label values v506     V506    
label values v510     V510    
label values v513     V513    
label values v525     V525    
label values v527     V527    
label values v528     V528    
label values v529     V529    
label values v530     V530    
label values v531     V531    
label values v532     V532    
label values v535     V535    
label values v536     V536    
label values v537     V537    
label values v538     V538    
label values v539     V539    
label values v540     V540    
label values v541     V541    
label values v602     V602    
label values v603     V603    
label values v604     V604    
label values v605     V605    
label values v613     V613    
label values v614     V614    
label values v616     V616    
label values v621     V621    
label values v623     V623    
label values v624     V624    
label values v625     V625    
label values v626     V626    
label values v627     V627    
label values v628     V628    
label values v629     V629    
label values v632     V632    
label values v633a    V633A   
label values v633b    V633B   
label values v633d    V633D   
label values v634     V634    
label values v701     V701    
label values v702     V702    
label values v704     V704    
label values v705     V705    
label values v714     V714    
label values v714a    V714A   
label values v715     V715    
label values v716     V716    
label values v717     V717    
label values v719     V719    
label values v721     V721    
label values v729     V729    
label values v730     V730    
label values v731     V731    
label values v732     V732    
label values v739     V739    
label values v740     V740    
label values v741     V741    
label values v743a    V743A   
label values v743b    V743B   
label values v743c    V743C   
label values v743d    V743D   
label values v743f    V743F   
label values v744a    V744A   
label values v744b    V744B   
label values v744c    V744C   
label values v744d    V744D   
label values v744e    V744E   
label values v746     V746    
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values b15      B15     
label values b16      B16     
label values m1       M1      
label values m1a      M1A     
label values m1b      M1B     
label values m1c      M1C     
label values m1e      M1E     
label values m2a      M2A     
label values m2b      M2B     
label values m2f      M2F     
label values m2g      M2G     
label values m2i      M2I     
label values m2k      M2K     
label values m2n      M2N     
label values m3a      M3A     
label values m3b      M3B     
label values m3f      M3F     
label values m3g      M3G     
label values m3i      M3I     
label values m3k      M3K     
label values m3n      M3N     
label values m4       M4      
label values m5       M5      
label values m6       M6      
label values m7       M7      
label values m8       M8      
label values m9       M9      
label values m10      M10     
label values m11      M11     
label values m13      M13     
label values m14      M14     
label values m15      M15     
label values m17      M17     
label values m18      M18     
label values m19      M19     
label values m19a     M19A    
label values m27      M27     
label values m28      M28     
label values m29      M29     
label values m34      M34     
label values m35      M35     
label values m36      M36     
label values m38      M38     
label values m39      M39     
label values m42a     M42A    
label values m42c     M42C    
label values m42d     M42D    
label values m42e     M42E    
label values m43      M43     
label values m44      M44     
label values m45      M45     
label values m46      M46     
label values m47      M47     
label values m48      M48     
label values m49a     M49A    
label values m49b     M49B    
label values m49d     M49D    
label values m49x     M49X    
label values m49z     M49Z    
label values m51a     M51A    
label values m54      M54     
label values m55a     M55A    
label values m55b     M55B    
label values m55c     M55C    
label values m55d     M55D    
label values m55e     M55E    
label values m55f     M55F    
label values m55g     M55G    
label values m55h     M55H    
label values m55i     M55I    
label values m55x     M55X    
label values m55z     M55Z    
label values m57a     M57A    
label values m57b     M57B    
label values m57e     M57E    
label values m57f     M57F    
label values m57g     M57G    
label values m57l     M57L    
label values m57m     M57M    
label values m57o     M57O    
label values m57r     M57R    
label values m57x     M57X    
label values m61      M61     
label values m62      M62     
label values m63      M63     
label values m64      M64     
label values m65a     M65A    
label values m65b     M65B    
label values m65c     M65C    
label values m65d     M65D    
label values m65e     M65E    
label values m65f     M65F    
label values m65g     M65G    
label values m65h     M65H    
label values m65i     M65I    
label values m65x     M65X    
label values m66      M66     
label values m67      M67     
label values m68      M68     
label values m69      M69     
label values m70      M70     
label values m71      M71     
label values m72      M72     
label values m73      M73     
label values h1       H1      
label values h2       H2      
label values h2d      H2D     
label values h2m      H2M     
label values h2y      H2Y     
label values h3       H3      
label values h3d      H3D     
label values h3m      H3M     
label values h3y      H3Y     
label values h4       H4      
label values h4d      H4D     
label values h4m      H4M     
label values h4y      H4Y     
label values h5       H5      
label values h5d      H5D     
label values h5m      H5M     
label values h5y      H5Y     
label values h6       H6      
label values h6d      H6D     
label values h6m      H6M     
label values h6y      H6Y     
label values h7       H7      
label values h7d      H7D     
label values h7m      H7M     
label values h7y      H7Y     
label values h8       H8      
label values h8d      H8D     
label values h8m      H8M     
label values h8y      H8Y     
label values h9       H9      
label values h9d      H9D     
label values h9m      H9M     
label values h9y      H9Y     
label values h10      H10     
label values h11      H11     
label values h11b     H11B    
label values h12a     H12A    
label values h12b     H12B    
label values h12e     H12E    
label values h12f     H12F    
label values h12g     H12G    
label values h12h     H12H    
label values h12i     H12I    
label values h12j     H12J    
label values h12k     H12K    
label values h12l     H12L    
label values h12o     H12O    
label values h12r     H12R    
label values h12s     H12S    
label values h12t     H12T    
label values h12x     H12X    
label values h12y     H12Y    
label values h12z     H12Z    
label values h13      H13     
label values h14      H14     
label values h15      H15     
label values h15a     H15A    
label values h15b     H15B    
label values h15c     H15C    
label values h15d     H15D    
label values h15f     H15F    
label values h15g     H15G    
label values h15h     H15H    
label values h15i     H15I    
label values h20      H20     
label values h21a     H21A    
label values h21      H21     
label values h22      H22     
label values h31      H31     
label values h31b     H31B    
label values h31c     H31C    
label values h31d     H31D    
label values h31e     H31E    
label values h32a     H32A    
label values h32b     H32B    
label values h32e     H32E    
label values h32f     H32F    
label values h32g     H32G    
label values h32h     H32H    
label values h32i     H32I    
label values h32j     H32J    
label values h32k     H32K    
label values h32o     H32O    
label values h32r     H32R    
label values h32s     H32S    
label values h32t     H32T    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values h33      H33     
label values h33d     H33D    
label values h33m     H33M    
label values h33y     H33Y    
label values h34      H34     
label values h35      H35     
label values h37a     H37A    
label values h37b     H37B    
label values h37d     H37D    
label values h37e     H37E    
label values h37h     H37H    
label values h37k     H37K    
label values h37l     H37L    
label values h37m     H37M    
label values h37n     H37N    
label values h37o     H37O    
label values h37p     H37P    
label values h37x     H37X    
label values h37y     H37Y    
label values h37z     H37Z    
label values h38      H38     
label values h39      H39     
label values h40      H40     
label values h40d     H40D    
label values h40m     H40M    
label values h40y     H40Y    
label values h41b     H41B    
label values h44a     H44A    
label values h44b     H44B    
label values h44c     H44C    
label values h46a     H46A    
label values h46b     H46B    
label values hw4      HW4     
label values hw5      HW5     
label values hw6      HW6     
label values hw7      HW7     
label values hw8      HW8     
label values hw9      HW9     
label values hw10     HW10    
label values hw11     HW11    
label values hw12     HW12    
label values hw13     HW13    
label values hw15     HW15    
label values hw16     HW16    
label values hw51     HW51    
label values hw52     HW52    
label values hw55     HW55    
label values hw57     HW57    
label values hw70     HW70    
label values hw71     HW71    
label values hw72     HW72    
label values hw73     HW73    
label values ml0      ML0     
label values ml1      ML1     
label values ml2      ML2     
label values ml11     ML11    
label values ml13a    ML13A   
label values ml13b    ML13B   
label values ml13d    ML13D   
label values ml13e    ML13E   
label values ml13h    ML13H   
label values ml13k    ML13K   
label values ml13l    ML13L   
label values ml13m    ML13M   
label values ml13n    ML13N   
label values ml13o    ML13O   
label values ml13p    ML13P   
label values ml13x    ML13X   
label values ml13y    ML13Y   
label values ml13z    ML13Z   
label values ml15a    ML15A   
label values ml15b    ML15B   
label values ml15c    ML15C   
label values ml16a    ML16A   
label values ml16b    ML16B   
label values ml16c    ML16C   
label values ml18c    ML18C   
label values ml19a    ML19A   
label values ml19b    ML19B   
label values ml19c    ML19C   
label values ml19x    ML19X   
label values ml19y    ML19Y   
label values ml19z    ML19Z   
label values slangq   SLANGQ  
label values slangint SLANGINT
label values sinterp  SINTERP 
label values s119     S119    
label values s240     S240    
label values s241     S241    
label values s242     S242    
label values s336     S336    
label values s338     S338    
label values s630a    S630A   
label values s630b    S630B   
label values s630c    S630C   
label values s643     S643    
label values s644     S644    
label values s645     S645    
label values s646     S646    
label values s649o    S649O   
label values s649p    S649P   
label values s649q    S649Q   
label values s653o    S653O   
label values s653p    S653P   
label values s653q    S653Q   
label values s723     S723    
label values s909a    S909A   
label values s909b    S909B   
label values s909c    S909C   
label values s909d    S909D   
label values s909e    S909E   
label values s909f    S909F   
label values s909g    S909G   
label values s909h    S909H   
label values s909i    S909I   
label values s909j    S909J   
label values s909k    S909K   
label values s909l    S909L   
label values s909m    S909M   
label values s909n    S909N   
label values s909w    S909W   
label values s909x    S909X   
label values s909z    S909Z   
label values s910     S910    
label values s920     S920    
label values s932     S932    
label values s933     S933    
label values s937     S937    
label values s938     S938    
label values s942a    S942A   
label values s950     S950    
label values s1012    S1012   
label values s1014    S1014   
label values s1016    S1016   
label values s1017    S1017   
label values s1106hn  S1106HN 
label values s1112    S1112   
label values s1113d   S1113D  
label values s1114a   S1114A  
label values s1114an  S1114AN 
label values s1114b   S1114B  
label values s1114bn  S1114BN 
label values s1114c   S1114C  
label values s1114cn  S1114CN 
label values s1114d   S1114D  
label values s1114dn  S1114DN 
label values s1116    S1116   
label values s1117a   S1117A  
label values s1117b   S1117B  
label values s1118a   S1118A  
label values s1118b   S1118B  
label values s1118c   S1118C  
label values s1118d   S1118D  
label values s1118e   S1118E  
label values s1118f   S1118F  
label values s1118g   S1118G  
label values s1118h   S1118H  
label values s1118i   S1118I  
label values s1118j   S1118J  
label values s1118k   S1118K  
label values s1118l   S1118L  
label values s1118m   S1118M  
label values s1118n   S1118N  
label values s1118o   S1118O  
label values s1118p   S1118P  
label values s1118x   S1118X  
label values s1134    S1134   
label values s436     S436    
label values s437     S437    
label values s439     S439    
label values s449     S449    
label values s508p4   S508P4  
label values sd58p4   SD58P4  
label values sm58p4   SM58P4  
label values sy58p4   SY58P4  
label values s508p5   S508P5  
label values s508d4   S508D4  
label values sd58d4   SD58D4  
label values sm58d4   SM58D4  
label values sy58d4   SY58D4  
label values s508h2   S508H2  
label values sd58h2   SD58H2  
label values sm58h2   SM58H2  
label values sy58h2   SY58H2  
label values s508h3   S508H3  
label values sd58h3   SD58H3  
label values sm58h3   SM58H3  
label values sy58h3   SY58H3  
label values s508h1   S508H1  
label values sd58h1   SD58H1  
label values sm58h1   SM58H1  
label values sy58h1   SY58H1  
label values s508m2   S508M2  
label values sd58m2   SD58M2  
label values sm58m2   SM58M2  
label values sy58m2   SY58M2  
label values s508pa   S508PA  
label values sd58pa   SD58PA  
label values sm58pa   SM58PA  
label values sy58pa   SY58PA  
label values s558a    S558A   
label values s558b    S558B   
label values s549i    S549I   
label values s549j    S549J   
label values s549k    S549K   
label values s532c    S532C   
